function bm_kernel_gui

global REMORA

defaultPos = [0.25, 0.25, 0.3, 0.3];
REMORA.fig.bm.kernel = figure(...
    'NumberTitle','off', ...
    'Name','Kernel calculator',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on');

% button grid layouts
% 3 rows, 2 columns
r = 7; % rows      (extra space for separations btw sections)
c = 2;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
xbuff = w*.1;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;

% colors
bgColor = [1 1 1];  % white
bgColorGrayLight = [.92 .92 .92];  % gray
bgColorGray = [.86 .86 .86];  % gray

REMORA.bm.kernel_verify = [];
labelStr = 'Calculate kernel values';
btnPos=[x(1) y(2) w*2 h];
REMORA.bm.kernel_verify.headtext = uicontrol(REMORA.fig.bm.kernel, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');

% Set paths and strings
%***********************************

% Input Folder Text
labelStr = 'Input Folder';
btnPos=[x(1)+xbuff  y(3) w dy];
REMORA.bm.kernel_verify.kernelDirTxt = uicontrol(REMORA.fig.bm.kernel,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Input Folder Editable Text
labelStr=num2str(REMORA.bm.settings.kernelDir);
btnPos=[x(2)-xbuff y(3) w dy];
REMORA.bm.kernel_verify.kernelDirEdTxt = uicontrol(REMORA.fig.bm.kernel,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_kernel_control(''setKernelDir'')');

% Kernel identifier Text
labelStr = 'Kernel identifier';
btnPos=[x(1)+xbuff  y(4) w dy];
REMORA.bm.kernel_verify.kernelIDTxt = uicontrol(REMORA.fig.bm.kernel,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Kernel Identifier Editable Text
labelStr=num2str(REMORA.bm.settings.kernelID);
btnPos=[x(2)-xbuff y(4) w dy];
REMORA.bm.kernel_verify.kernelIDEdTxt = uicontrol(REMORA.fig.bm.kernel,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_kernel_control(''setKernelID'')');

% Kernel deployment Text
% labelStr = 'Deployment of kernel calls';
% btnPos=[x(1)+xbuff  y(5) w dy];
% REMORA.bm.kernel_verify.kernelDeplTxt = uicontrol(REMORA.fig.bm.kernel,...
%     'Style','text',...
%     'Units','normalized',...
%         'HorizontalAlignment','left',...
%     'Position',btnPos,...
%     'String',sprintf(labelStr,'Interpreter','tex'),...
%     'FontUnits','normalized', ...
%     'Visible','on');

% Kernel deployment Editable Text
% labelStr=num2str(REMORA.bm.settings.kernelDepl);
% btnPos=[x(2)-xbuff y(5) w dy];
% REMORA.bm.kernel_verify.kernelDeplEdTxt = uicontrol(REMORA.fig.bm.kernel,...
%     'Style','edit',...
%     'Units','normalized',...
%     'Position',btnPos,...
%     'BackgroundColor',bgColor,...
%     'HorizontalAlignment','left',...
%     'String',labelStr,...
%     'FontUnits','normalized', ...
%     'Visible','on',...
%     'Callback','bm_kernel_control(''setKernelDepl'')');

% Run button
labelStr = 'Calculate kernel';
btnPos=[x(1)+1/2*w y(7) w h];
REMORA.bm.kernel_verify.RunCalcEdTxt = uicontrol(REMORA.fig.bm.kernel,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',[.47,.67,.19],...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','bm_kernel_control(''RunKernelCalc'')');


