function lt_init_lEdit_window

global REMORA HANDLES PARAMS


defaultPos = [0.1,0.5,0.2,0.25];



if isfield(REMORA.fig, 'lt')
    % check if the figure already exists. If so, don't move it.
    if isfield(REMORA.fig.lt, 'lEdit_settings') && isvalid(REMORA.fig.lt.lEdit_settings)
        defaultPos = get(REMORA.fig.lt.lEdit_settings,'Position');
    else
        REMORA.fig.lt.lEdit_settings = figure;
    end
else
    REMORA.fig.lt.lEdit_settings = figure;
end

set(REMORA.fig.lt.lEdit_settings,'NumberTitle','off', ...
    'Name','Visualize Labels',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on',...
    'ToolBar', 'none');

figure(REMORA.fig.lt.lEdit_settings)




%%%%button grid
row = 12;
col = 1;
h = 1/row;
w = 1/col;
x = 0:w:1;
y = 1:-h:0;
xbuff = w*0.25;
ybuff = h*0.2;

%%%colors
bgColor = [1 1 1];
bgColorPurple = [0.8 0.6 0.6];
bgColorTeal = [0.2 0.6 0.4];
bgColorCoral = [1.0 0.6 0.4];
bgColorBlue = [0 0.8 1.0];
REMORA.lt.lEdit_verify = [];

%% title content
btnPos = [x(1) y(2) w h];
labelStr = 'Edit Open Labels';
REMORA.lt.lEdit_verify.headtext = uicontrol(REMORA.fig.lt.lEdit_settings, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');  %'BackgroundColor',bgColor3,...


%% label edit buttons

labelStr = 'Mark as False';
btnPos = [x(1) y(3) w*1.3 h];
REMORA.lt.lEdit_verify.falseCheck = uicontrol(REMORA.fig.lt.lEdit_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'on', ...
    'FontUnits','normalized', ...
    'Callback','lt_lEdit_control(''markFalse'')');

labelStr = 'Mark as Label 1';
btnPos = [x(1) y(4) w*1.3 h];
REMORA.lt.lEdit_verify.oneCheck = uicontrol(REMORA.fig.lt.lEdit_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'on', ...
    'FontUnits','normalized', ...
    'Callback','lt_lEdit_control(''mark1'')');

labelStr = 'Mark as Label 2';
btnPos = [x(1) y(5) w*1.3 h];
REMORA.lt.lEdit_verify.twoCheck = uicontrol(REMORA.fig.lt.lEdit_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'on', ...
    'FontUnits','normalized', ...
    'Callback','lt_lEdit_control(''mark2'')');

labelStr = 'Mark as Label 3';
btnPos = [x(1) y(6) w*1.3 h];
REMORA.lt.lEdit_verify.threeCheck = uicontrol(REMORA.fig.lt.lEdit_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'on', ...
    'FontUnits','normalized', ...
    'Callback','lt_lEdit_control(''mark3'')');

labelStr = 'Mark as Label 4';
btnPos = [x(1) y(7) w*1.3 h];
REMORA.lt.lEdit_verify.fourCheck = uicontrol(REMORA.fig.lt.lEdit_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'on', ...
    'FontUnits','normalized', ...
    'Callback','lt_lEdit_control(''mark4'')');

labelStr = 'Mark as Label 5';
btnPos = [x(1) y(8) w*1.3 h];
REMORA.lt.lEdit_verify.fiveCheck = uicontrol(REMORA.fig.lt.lEdit_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'on', ...
    'FontUnits','normalized', ...
    'Callback','lt_lEdit_control(''mark5'')');

labelStr = 'Mark as Label 6';
btnPos = [x(1) y(9) w*1.3 h];
REMORA.lt.lEdit_verify.sixCheck = uicontrol(REMORA.fig.lt.lEdit_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'on', ...
    'FontUnits','normalized', ...
    'Callback','lt_lEdit_control(''mark6'')');

labelStr = 'Mark as Label 7';
btnPos = [x(1) y(10) w*1.3 h];
REMORA.lt.lEdit_verify.sevCheck = uicontrol(REMORA.fig.lt.lEdit_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'on', ...
    'FontUnits','normalized', ...
    'Callback','lt_lEdit_control(''mark7'')');

labelStr = 'Mark as Label 8';
btnPos = [x(1) y(11) w*1.3 h];
REMORA.lt.lEdit_verify.eightCheck = uicontrol(REMORA.fig.lt.lEdit_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'on', ...
    'FontUnits','normalized', ...
    'Callback','lt_lEdit_control(''mark8'')');

%% save changed labels
labelStr = 'Save Changed Label Files';
btnPos = [x(1)+w/4 y(12) w/2 h];
REMORA.lt.lEdit.saveLabs = uicontrol(REMORA.fig.lt.lEdit_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorBlue,...
    'String',labelStr ,...
    'FontUnits','normalized', ...
    'Enable', 'on', ...
    'FontWeight','normal',...
    'Callback','lt_lEdit_control(''Save'')');