function lt_init_lVis_window

global REMORA HANDLES PARAMS


defaultPos = [0.1,0.1,0.3,0.25];



if isfield(REMORA.fig, 'lt')
    % check if the figure already exists. If so, don't move it.
    if isfield(REMORA.fig.lt, 'lVis_settings') && isvalid(REMORA.fig.lt.lVis_settings)
        defaultPos = get(REMORA.fig.lt.lVis_settings,'Position');
    else
        REMORA.fig.lt.lVis_settings = figure;
    end
else
    REMORA.fig.lt.lVis_settings = figure;
end

set(REMORA.fig.lt.lVis_settings,'NumberTitle','off', ...
    'Name','Visualize Labels',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on',...
    'ToolBar', 'none');

figure(REMORA.fig.lt.lVis_settings)




%%%%button grid
row = 15;
col = 3;
h = 1/row;
w = 1/col;
x = 0:w:1;
y = 1:-h:0;
xbuff = w*0.25;
ybuff = h*0.2;

%%%colors
bgColor = [1 1 1];
bgColorPurple = [0.8 0.6 0.6];
bgColorTeal = [0.2 0.6 0.4];
bgColorCoral = [1.0 0.6 0.4];
bgColorBlue = [0 0.8 1.0];
REMORA.lt.lVis_verify = [];

%% title content
btnPos = [x(1) y(2) w h];
labelStr = 'Load labels to visualize';
REMORA.lt.lVis_verify.headtext = uicontrol(REMORA.fig.lt.lVis_settings, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');  %'BackgroundColor',bgColor3,...


%%%work with LTSA
% if isfield(PARAMS, 'ltsa')
f_enable = 'on'; %get(HANDLES.ltsa.motion.fwd, 'Enable');
b_enable = 'on'; %get(HANDLES.ltsa.motion.back, 'Enable');
prev_enableLTSA = 'on';
next_enableLTSA = 'on';
% else
%     f_enable = 'off';
%     b_enable = 'off';
% end

%%work with rawFile -all set to on right now for ease
% if REMORA.lt.lVis_params.rawFile
f_enableRF = 'on'; %get(HANDLES.motion.fwd,'Enable');
next_enableRF = 'on'; %get(HANDLES.motion.nextfile,'Enable');
b_enableRF = 'on'; %get(HANDLES.motion.back,'Enable');
prev_enableRF = 'on'; %get(HANDLES.motion.prevfile,'Enable');
ref_enable = 'on'; %refresh button always enabled
% else
%     f_enableRF = 'off';
%     b_enableRF = 'off';
%     next_enableRF = 'off';
%     prev_enableRF = 'off';
% end


%% label loading functionality
labelStr = 'Load Labels 1';
btnPos=[x(1) y(3) w h];
REMORA.lt.lVis_verify.load1 = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'BackgroundColor',bgColorPurple,...
    'Callback','lt_lVis_control(''LoadLabels'',''labels1'')');

labelStr = 'Load Labels 2';
btnPos=[x(1) y(4) w h];
REMORA.lt.lVis_verify.load2 = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'BackgroundColor',bgColorPurple,...
    'Callback','lt_lVis_control(''LoadLabels'',''labels2'')');

labelStr = 'Load Labels 3';
btnPos=[x(1) y(5) w h];
REMORA.lt.lVis_verify.load3 = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'BackgroundColor',bgColorPurple,...
    'Callback','lt_lVis_control(''LoadLabels'',''labels3'')');

labelStr = 'Load Labels 4';
btnPos=[x(1) y(6) w h];
REMORA.lt.lVis_verify.load4 = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'BackgroundColor',bgColorPurple,...
    'Callback','lt_lVis_control(''LoadLabels'',''labels4'')');

labelStr = 'Load Labels 5';
btnPos=[x(1) y(7) w h];
REMORA.lt.lVis_verify.load5 = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'BackgroundColor',bgColorPurple,...
    'Callback','lt_lVis_control(''LoadLabels'',''labels5'')');

labelStr = 'Load Labels 6';
btnPos=[x(1) y(8) w h];
REMORA.lt.lVis_verify.load6 = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'BackgroundColor',bgColorPurple,...
    'Callback','lt_lVis_control(''LoadLabels'',''labels6'')');

labelStr = 'Load Labels 7';
btnPos=[x(1) y(9) w h];
REMORA.lt.lVis_verify.load7 = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'BackgroundColor',bgColorPurple,...
    'Callback','lt_lVis_control(''LoadLabels'',''labels7'')');

labelStr = 'Load Labels 8';
btnPos=[x(1) y(10) w h];
REMORA.lt.lVis_verify.load8 = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'BackgroundColor',bgColorPurple,...
    'Callback','lt_lVis_control(''LoadLabels'',''labels8'')');
%% display label buttons
labelStr = 'Display 1';
btnPos = [x(2)+xbuff y(3) w*1.3 h];
REMORA.lt.lVis_labels.label1Check = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'off', ...
    'FontUnits','normalized', ...
    'Callback','lt_lVis_control(''Display'',''labels1'')');

labelStr = 'Display 2';
btnPos = [x(2)+xbuff y(4) w*1.3 h];
REMORA.lt.lVis_labels.label2Check = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'off', ...
    'FontUnits','normalized', ...
    'Callback','lt_lVis_control(''Display'',''labels2'')');

labelStr = 'Display 3';
btnPos = [x(2)+xbuff y(5) w*1.3 h];
REMORA.lt.lVis_labels.label3Check = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'off', ...
    'FontUnits','normalized', ...
    'Callback','lt_lVis_control(''Display'',''labels3'')');

labelStr = 'Display 4';
btnPos = [x(2)+xbuff y(6) w*1.3 h];
REMORA.lt.lVis_labels.label4Check = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'off', ...
    'FontUnits','normalized', ...
    'Callback','lt_lVis_control(''Display'',''labels4'')');

labelStr = 'Display 5';
btnPos = [x(2)+xbuff y(7) w*1.3 h];
REMORA.lt.lVis_labels.label5Check = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'off', ...
    'FontUnits','normalized', ...
    'Callback','lt_lVis_control(''Display'',''labels5'')');

labelStr = 'Display 6';
btnPos = [x(2)+xbuff y(8) w*1.3 h];
REMORA.lt.lVis_labels.label6Check = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'off', ...
    'FontUnits','normalized', ...
    'Callback','lt_lVis_control(''Display'',''labels6'')');

labelStr = 'Display 7';
btnPos = [x(2)+xbuff y(9) w*1.3 h];
REMORA.lt.lVis_labels.label7Check = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'off', ...
    'FontUnits','normalized', ...
    'Callback','lt_lVis_control(''Display'',''labels7'')');

labelStr = 'Display 8';
btnPos = [x(2)+xbuff y(10) w*1.3 h];
REMORA.lt.lVis_labels.label8Check = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'off', ...
    'FontUnits','normalized', ...
    'Callback','lt_lVis_control(''Display'',''labels8'')');

%% LTSA buttons

labelStr = 'LTSA Motion';
btnPos = [x(2)-w/9 y(11)-2*ybuff w*1.2 h];
REMORA.lt.lVis_verify.LTSAmotion = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr ,...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');
%% back button

labelStr = '<';
btnPos = [x(1)+w/2 y(12)-ybuff w h];
REMORA.lt.lVis_labels.LTSAback = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorTeal,...
    'String',labelStr ,...
    'FontUnits','normalized', ...
    'Enable', b_enable, ...
    'FontWeight','bold',...
    'Callback','lt_lVis_control(''TakeItBack'')');

%% forward button
labelStr = '>';
btnPos = [x(2)+w/2 y(12)-ybuff w h];
REMORA.lt.lVis_labels.LTSAfwd = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorTeal,...
    'String',labelStr ,...
    'FontUnits','normalized', ...
    'Enable', f_enable, ...
    'FontWeight','bold',...
    'Callback','lt_lVis_control(''MoveAlong'')');

%% prev LTSA detection button
labelStr = 'prev';
btnPos = [x(1) y(12)-ybuff w/2 h];
REMORA.lt.lVis_labels.prevF_LTSA = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorTeal,...
    'String',labelStr ,...
    'FontUnits','normalized', ...
    'Enable', prev_enableLTSA, ...
    'FontWeight','normal',...
      'Callback','lt_lVis_control(''PrevLTSADetection'')');

%% next detection button
labelStr = 'next';
btnPos = [x(2)+1.5*w y(12)-ybuff w/2 h];
REMORA.lt.lVis_labels.nextF_LTSA = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorTeal,...
    'String',labelStr ,...
    'FontUnits','normalized', ...
    'Enable', next_enableLTSA, ...
    'FontWeight','normal',...
    'Callback','lt_lVis_control(''NextLTSADetection'')');

%% raw file buttons

labelStr = 'Raw File Motion';
btnPos = [x(2) y(13)-2*ybuff w h];
REMORA.lt.lVis_verify.RFmotion = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr ,...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');
%% back button
labelStr = '<';
btnPos = [x(1)+w/2 y(14)-ybuff w h];
REMORA.lt.lVis_labels.RFback = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorCoral,...
    'String',labelStr ,...
    'FontUnits','normalized', ...
    'Enable', b_enableRF, ...
    'FontWeight','bold',...
    'Callback','lt_lVis_control(''SmallStepBack'')');

%% forward button
labelStr = '>';
btnPos = [x(2)+w/2 y(14)-ybuff w h];
REMORA.lt.lVis_labels.RFfwd = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorCoral,...
    'String',labelStr ,...
    'FontUnits','normalized', ...
    'Enable', f_enableRF, ...
    'FontWeight','bold',...
    'Callback','lt_lVis_control(''OneStepForward'')');

%% prev detection button
labelStr = 'prev';
btnPos = [x(1) y(14)-ybuff w/2 h];
REMORA.lt.lVis_labels.prevF = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorCoral,...
    'String',labelStr ,...
    'FontUnits','normalized', ...
    'Enable', prev_enableRF, ...
    'FontWeight','normal',...
    'Callback','lt_lVis_control(''PrevDetection'')');

%% next detection button
labelStr = 'next';
btnPos = [x(2)+1.5*w y(14)-ybuff w/2 h];
REMORA.lt.lVis_labels.nextF = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorCoral,...
    'String',labelStr ,...
    'FontUnits','normalized', ...
    'Enable', next_enableRF, ...
    'FontWeight','normal',...
    'Callback','lt_lVis_control(''NextDetection'')');

%% refresh all open plots
labelStr = 'Refresh';
btnPos = [x(1)+1.25*w y(15)-2*ybuff w/2 h];
REMORA.lt.lVis_labels.refresh = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorBlue,...
    'String',labelStr ,...
    'FontUnits','normalized', ...
    'Enable', ref_enable, ...
    'FontWeight','normal',...
    'Callback','lt_lVis_control(''Refresh'')');
