function sh_init_visLabel_figure

global REMORA

defaultPos = [0.05,0.1,0.16,0.17];
REMORA.fig.sh.visLabel = figure( ...
    'NumberTitle','off', ...
    'Name','Visualize Labels',...
    'Units','normalized',...
    'MenuBar','none',...
    'Color',[.75 .875 1],...
    'Position',defaultPos, ...
    'Visible', 'on');

% initialize
REMORA.sh.detection.PlotLabels = false;
REMORA.sh.detection2.PlotLabels = false;
