function sh_init_batch_figure

global REMORA

defaultPos = [0.25,0.25,0.3,0.6];
REMORA.fig.sh.batch = figure( ...
    'NumberTitle','off', ...
    'Name','Ship Detector Batch - v1.0',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on');

% Detection Settings pulldown
REMORA.sh.menuBatch = uimenu(REMORA.fig.sh.batch,'Label','&Load Settings',...
    'Enable','on','Visible','on');

% Spectrogram load/save params
uimenu(REMORA.sh.menuBatch,'Label','&Select Detector Settings File',...
    'Callback','sh_gui_pulldown(''settingsLoadBatch'')');
