function [ok, flacFile, msg] = xwav2flac(xwavFile, varargin)
%XWAV2FLAC  Compress an x.wav to x.flac, keeping the harp header, and verify it.
%
%   ok = xwav2flac('file.x.wav')                        % keeps the x.wav
%   ok = xwav2flac(f, 'keepXwav', false)                % deletes it, if verified
%   [ok, out, msg] = xwav2flac(f, 'outdir', d)
%
% Options
%   'outdir'    where to write; default alongside the source
%   'keepXwav'  keep the original after a verified conversion (default true)
%   'flac'      path to the flac tool; found automatically if omitted
%   'verify'    verify before reporting success (default true)
%
% Typically halves the file. Real HARP recordings compress by 55-70%, which is
% the point: the audio is losslessly recoverable, so an archive can be stored
% compressed and the x.wav regenerated byte for byte if it is ever needed.
%
% WHAT IS VERIFIED, AND WHY IT MATTERS
%
% The x.wav is deleted only when keepXwav is false AND verification passed. A
% conversion can fail in a way that leaves a perfectly playable file:
%
%   * The audio could decode differently. flac --verify decodes each frame as
%     it encodes and compares, so the encoder itself catches this.
%
%   * The harp header could be dropped. This is the dangerous one. Without
%     --keep-foreign-metadata the file still plays, still reports the right
%     sample rate, and looks entirely healthy -- but the raw-file structure,
%     the gain and the deployment times are gone for good, and it can never
%     become an x.wav again. Nothing about the file announces this. So the
%     preserved header is read back and compared, byte for byte, with the
%     header of the file about to be deleted.
%
% Some conversion scripts retry without the metadata flag when the first
% attempt fails, which produces exactly that silent loss across part of a
% folder. This never does: if the header did not survive, the conversion is a
% failure and the x.wav stays.
%
% Use Extras/ck_xflac_metadata.m to audit folders converted by other means.
%
% See also FLAC_EXE, RDXFLACHD, XWAV_READ, CK_XFLAC_METADATA.

p = inputParser;
addParameter(p,'outdir','');
addParameter(p,'keepXwav',true);
addParameter(p,'flac','');
addParameter(p,'verify',true);
parse(p,varargin{:});
opt = p.Results;

ok = false; flacFile = ''; msg = '';

if ~exist(xwavFile,'file')
    msg = sprintf('no such file: %s', xwavFile);
    return
end

[exe, why] = flac_exe(opt.flac);
if isempty(exe)
    msg = why;
    return
end

[srcDir, stem, ext] = fileparts(xwavFile);
if ~strcmpi(ext,'.wav')
    msg = sprintf('%s is not a wav file', xwavFile);
    return
end
if isempty(opt.outdir); opt.outdir = srcDir; end
if ~exist(opt.outdir,'dir')
    msg = sprintf('no such directory: %s', opt.outdir);
    return
end
flacFile = fullfile(opt.outdir, [stem '.flac']);   % name.x.wav -> name.x.flac

%% ---- convert
% --channel-map=none is needed above two channels: the x.wav fmt chunk declares
% plain PCM, and the WAV spec wants WAVE_FORMAT_EXTENSIBLE past stereo, so flac
% otherwise refuses with "cannot assign channels". Harmless for mono, so it is
% always passed rather than only sometimes.
%
% --verify decodes while encoding and compares against the input, so a
% corrupted stream is caught here rather than years later.
verifyFlag = '';
if opt.verify; verifyFlag = '--verify '; end
cmd = sprintf('"%s" %s--channel-map=none --keep-foreign-metadata-if-present -f -s -o "%s" "%s"', ...
    exe, verifyFlag, flacFile, xwavFile);
[st, out] = system(cmd);
if st ~= 0 || ~exist(flacFile,'file')
    msg = sprintf('flac failed on %s: %s', [stem ext], strtrim(out));
    if exist(flacFile,'file'); delete(flacFile); end
    flacFile = '';
    return
end

%% ---- verify the header survived
if opt.verify
    [hdrOk, hdrMsg] = local_check_header(xwavFile, flacFile);
    if ~hdrOk
        msg = sprintf('%s: %s', [stem ext], hdrMsg);
        delete(flacFile);
        flacFile = '';
        return
    end
end

%% ---- only now is it safe to remove the original
if ~opt.keepXwav
    delete(xwavFile);
end

a = dir(flacFile);
ok = true;
msg = sprintf('%d bytes', a.bytes);
end


%% ================================================================== helpers
function [ok, msg] = local_check_header(xwavFile, flacFile)
%LOCAL_CHECK_HEADER  Do the flac's preserved chunks reproduce the x.wav header?
%
% The chunks flac stored, concatenated, should equal the leading bytes of the
% x.wav exactly -- that is what "preserved" means. Comparing them directly is a
% stronger check than parsing both and comparing fields, and it cannot be
% fooled by two headers that parse to the same values for different reasons.
ok = false;

try
    chunks = xflac_riff_chunks(flacFile);
catch e
    msg = ['cannot read flac metadata: ' e.message];
    return
end
if isempty(chunks)
    msg = 'the harp header was NOT preserved (no RIFF metadata in the flac)';
    return
end

hasHarp = false;
for k = 1:numel(chunks)
    b = chunks{k};
    if numel(b) >= 4 && strcmp(char(b(1:4))','harp'); hasHarp = true; break; end
end
if ~hasHarp
    msg = 'the harp chunk was NOT preserved';
    return
end

rebuilt = cat(1, chunks{:});

fid = fopen(xwavFile,'r');
if fid < 0
    msg = 'cannot reopen the x.wav to compare headers';
    return
end
original = fread(fid, numel(rebuilt), '*uint8');
fclose(fid);

if numel(original) ~= numel(rebuilt)
    msg = sprintf('header length differs: %d in the x.wav, %d preserved', ...
        numel(original), numel(rebuilt));
    return
end
if ~isequal(original, rebuilt)
    msg = sprintf('preserved header differs from the x.wav at %d of %d bytes', ...
        sum(original ~= rebuilt), numel(rebuilt));
    return
end

ok = true;
msg = '';
end
