function mypsd_visualize_gui
global REMORA

% Colors (match Compute HMD GUI)
bgColor       = [0.90, 0.94, 0.98];   % Main background
textColor     = [0.1, 0.2, 0.4];      % Label text
buttonColor   = [0.25, 0.45, 0.70];   % Buttons: darker blue
buttonFontColor = [1, 1, 1];          % White button text

% Base figure size (pixels)
figWidthPx = 750;
figHeightPx = 480;

REMORA.mypsdViz.gui.fig = figure('Name', 'TriHyb: Visualize HARP Hybrid Millidecade Products', ...
    'NumberTitle', 'off', 'MenuBar', 'none', ...
    'ToolBar', 'none', 'Color', bgColor, ...
    'Units', 'normalized', ...
    'Position', [0.3, 0.2, 0.42, 0.5]);

fig = REMORA.mypsdViz.gui.fig;
fontSize = 10;

% === Load logo and alpha ===
logoPath = fullfile(fileparts(mfilename('fullpath')), 'MBARC_logo.png');
[logoImg, ~, alpha] = imread(logoPath);
logoImg = flipud(logoImg);
if exist('alpha', 'var')
    alpha = flipud(alpha);
end

logoPanel = uipanel(fig, ...
    'Units', 'normalized', ...
    'Position', [0, 0.80, 0.28, 0.20], ...
    'BackgroundColor', bgColor, ...
    'BorderType', 'none');

logoAxes = axes('Parent', logoPanel, ...
    'Units', 'normalized', ...
    'Position', [0, 0, 1, 1], ...
    'Color', 'none');

hImg = image('CData', logoImg, 'Parent', logoAxes);
if exist('alpha', 'var')
    set(hImg, 'AlphaData', alpha);
end
set(logoAxes, 'YDir', 'normal');
axis(logoAxes, 'image');
axis(logoAxes, 'off');

% Title text
uicontrol(fig, 'Style', 'text', ...
    'String', 'Visualize HARP Hybrid Millidecade Products', ...
    'Units', 'normalized', ...
    'Position', [200/figWidthPx, 400/figHeightPx, 500/figWidthPx, 40/figHeightPx], ...
    'FontSize', 14, 'FontWeight', 'bold', ...
    'BackgroundColor', bgColor, ...
    'ForegroundColor', textColor, ...
    'HorizontalAlignment', 'center');

% Layout constants
yStep = 55 / figHeightPx;
yBase = 330 / figHeightPx;

    function createField(labelStr, fieldName, defaultVal, ypos, browseCallback)
        labelPos = [40 / figWidthPx, ypos, 170 / figWidthPx, 28 / figHeightPx];
        editPos = [220 / figWidthPx, ypos, 410 / figWidthPx, 28 / figHeightPx];
        btnPos = [640 / figWidthPx, ypos, 90 / figWidthPx, 28 / figHeightPx];

        uicontrol(fig, 'Style', 'text', 'String', labelStr, ...
            'Units', 'normalized', ...
            'Position', labelPos, ...
            'BackgroundColor', bgColor, 'ForegroundColor', textColor, ...
            'HorizontalAlignment', 'left', 'FontWeight', 'bold', ...
            'FontSize', fontSize);

        hEdit = uicontrol(fig, 'Style', 'edit', ...
            'Units', 'normalized', ...
            'Position', editPos, 'HorizontalAlignment', 'left', ...
            'String', defaultVal);

        if ~isempty(browseCallback)
            uicontrol(fig, 'Style', 'pushbutton', 'String', 'Browse', ...
                'Units', 'normalized', ...
                'Position', btnPos, ...
                'BackgroundColor', buttonColor, 'ForegroundColor', buttonFontColor, ...
                'FontWeight', 'bold', ...
                'Callback', @(~,~) browseCallback(hEdit));
        end

        REMORA.mypsdViz.gui.(fieldName) = hEdit;
    end

    function browse_dir(editHandle)
        path = uigetdir('', 'Select Directory');
        if isequal(path, 0)
            return;
        end
        set(editHandle, 'String', path);
    end

yCurrent = yBase;
createField('Path with .nc files:', 'ncPath', '', yCurrent, @browse_dir);

yCurrent = yCurrent - yStep;
createField('Figure Output Path:', 'figOutputPath', '', yCurrent, @browse_dir);

yCurrent = yCurrent - yStep - (10/figHeightPx);

% "Bin by" label
uicontrol(fig, 'Style', 'text', 'String', 'Bin by:', ...
    'Units', 'normalized', ...
    'Position', [40/figWidthPx, yCurrent, 170/figWidthPx, 28/figHeightPx], ...
    'BackgroundColor', bgColor, 'ForegroundColor', textColor, ...
    'HorizontalAlignment', 'left', 'FontWeight', 'bold', ...
    'FontSize', fontSize);

% Button group with radio buttons for bin resolution
binGroup = uibuttongroup(fig, 'Units', 'normalized', ...
    'Position', [220/figWidthPx, yCurrent - 90/figHeightPx, 480/figWidthPx, 120/figHeightPx], ...
    'BackgroundColor', bgColor, 'BorderType', 'none');

uicontrol(binGroup, 'Style', 'radiobutton', 'String', 'Hourly resolution', ...
    'Units', 'normalized', 'Position', [0, 0.66, 1, 0.33], ...
    'BackgroundColor', bgColor, 'ForegroundColor', textColor, ...
    'FontSize', fontSize, 'Tag', 'hourly');

uicontrol(binGroup, 'Style', 'radiobutton', 'String', 'Daily resolution', ...
    'Units', 'normalized', 'Position', [0, 0.33, 1, 0.33], ...
    'BackgroundColor', bgColor, 'ForegroundColor', textColor, ...
    'FontSize', fontSize, 'Tag', 'daily');

uicontrol(binGroup, 'Style', 'radiobutton', 'String', 'Keep one-minute resolution', ...
    'Units', 'normalized', 'Position', [0, 0, 1, 0.33], ...
    'BackgroundColor', bgColor, 'ForegroundColor', textColor, ...
    'FontSize', fontSize, 'Tag', 'oneminute');

set(binGroup, 'SelectedObject', []);  % force explicit choice below
binButtons = get(binGroup, 'Children');
dailyBtn = binButtons(strcmp(get(binButtons, 'Tag'), 'daily'));
set(binGroup, 'SelectedObject', dailyBtn);  % default selection

REMORA.mypsdViz.gui.binGroup = binGroup;

% Generate Figures button centered at bottom
uicontrol(fig, 'Style', 'pushbutton', ...
    'String', 'Generate Figures', ...
    'Units', 'normalized', ...
    'Position', [(figWidthPx/2 - 90)/figWidthPx, 25/figHeightPx, 180/figWidthPx, 40/figHeightPx], ...
    'BackgroundColor', [0.40, 0.75, 0.40], ...
    'ForegroundColor', buttonFontColor, ...
    'FontWeight', 'bold', 'FontSize', 11, ...
    'Callback', @mypsd_visualize_callback);

% Version label, bottom right corner of the GUI
uicontrol(fig, 'Style', 'text', ...
    'String', 'TriHyb (Version 1.2.0)', ...
    'Units', 'normalized', ...
    'Position', [500/figWidthPx, 2/figHeightPx, 240/figWidthPx, 16/figHeightPx], ...
    'FontSize', 8, ...
    'BackgroundColor', bgColor, ...
    'ForegroundColor', textColor, ...
    'HorizontalAlignment', 'right');

end
