function sp_ui_check_detParams(hObject,eventdata,hFigure)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% sp_ui_check_detParams.m
%
% Verify settings in GUI before running on entire drive.
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
global REMORA

if ishandle(hFigure) && isvalid(hFigure)
    close(hFigure)
end
defaultPos = [0.25,0.25,0.5,0.5];
if ~isfield(REMORA.fig,'spice_dt_verify') || ~isvalid(REMORA.fig.spice_dt_verify)
    % if the figure doesn't exist, make a new one.
    REMORA.fig.spice_dt_verify = figure;
else
    % otherwise clear the old one
    clf(REMORA.fig.spice_dt_verify)
end

set(REMORA.fig.spice_dt_verify, ...
    'NumberTitle','off', ...
    'Name','Spice Detector Batch - v1.0',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on');

% button grid layouts
% 14 rows, 4 columns
r = 24; % rows      (extra space for separations btw sections)
c = 4;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;


% colors
bgColor = [1 1 1];  % white
bgColorRed = [1 .6 .6];  % red
bgColorGray = [.86 .86 .86];  % gray
bgColor3 = [.75 .875 1]; % light green 
bgColor4 = [.76 .87 .78]; % light blue 
 
REMORA.spice_dt_verify = [];
REMORA.spice_dt_verify.spHelpStrings = sp_get_help_strings;
% Detection Parameters pulldown
REMORA.spice_dt_verify.filemenu = uimenu(REMORA.fig.spice_dt_verify,'Label','Save/Load Params',...
    'Enable','on','Visible','on');

% Spectrogram load/save params
uimenu(REMORA.spice_dt_verify.filemenu ,'Label','&Load detector settings',...
    'Callback',{@sp_dt_paramspd,'spice_settingsLoad','batchMode'});
uimenu(REMORA.spice_dt_verify.filemenu ,'Label','&Save detector settings',...
    'Callback',{@sp_dt_paramspd,'spice_settingsSave','batchMode'});



labelStr = 'Verify Detector Options';
btnPos=[x(1) y(2) 4*w h];
REMORA.spice_dt_verify.headtext = uicontrol(REMORA.fig.spice_dt_verify, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColor3,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',11,...
    'Visible','on'); 


% Set paths and strings
%***********************************
%% Base Folder Text
labelStr = 'Base Folder';
btnPos=[x(1) y(3) w dy];
REMORA.spice_dt_verify.baseDirTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.baseDir),...
   'Visible','on');%   'BackgroundColor',bgColor3,...

% Base Folder Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.baseDir);
btnPos=[x(2) y(3) (w*3)*.8 dy];
REMORA.spice_dt_verify.baseDirEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','sp_dt_control(''setBaseDir'')');

%% Output Folder Text
labelStr = 'Output Folder';
btnPos=[x(1) y(4) w dy];
REMORA.spice_dt_verify.outDirTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.outDir),...
   'Visible','on');%   'BackgroundColor',bgColor3,...

% Output Folder Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.outDir);
btnPos=[x(2) y(4) (w*3)*.8 dy];
REMORA.spice_dt_verify.outDirEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''setOutDir'')');

%% Transfer Function Text
labelStr = 'Transfer Function Path';
btnPos=[x(1) y(5) w dy];
REMORA.spice_dt_verify.TFPathTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.TFPath),...
   'Visible','on');%   'BackgroundColor',bgColor3,...

% Transfer Function Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.tfFullFile);
btnPos=[x(2) y(5) (w*3)*.8 dy];
REMORA.spice_dt_verify.TFPathEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''setTFPath'')');

%% Deployment Name Wildcard Text
labelStr = 'File Name Wildcard';
btnPos=[x(1) y(6) w dy];
REMORA.spice_dt_verify.deployNameTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.deployName),...
   'Visible','on');%   'BackgroundColor',bgColor3,...

% Deployment Name Wildcard Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.depl);
btnPos=[x(2) y(6) w dy];
REMORA.spice_dt_verify.deployNameEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','sp_dt_control(''setDeployName'')');

%% Channel Text
labelStr = 'Channel';
btnPos=[x(1) y(7) w dy];
REMORA.spice_dt_verify.channelTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.channel),...
   'Visible','on');%   'BackgroundColor',bgColor3,...

% Channel Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.channel);
btnPos=[x(2) y(7) (w/2) dy];
REMORA.spice_dt_verify.channelEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''setChannel'')');

%% Overwrite Checkbox
labelStr = 'Overwrite Existing Detection Files?';
btnPos=[x(3) y(7) w dy];
REMORA.spice_dt_verify.overwriteCheck = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'Value',REMORA.spice_dt.detParams.overwrite,...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.overwrite),...
   'Callback','sp_dt_control(''setOverwrite'')');%  

%% Commonly-modified parameters
labelStr = 'Commonly-Modified';
btnPos=[x(1) y(9) w*2 h];
REMORA.spice_dt_verify.headtext = uicontrol(REMORA.fig.spice_dt_verify, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColor4,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on'); 

%% Column Names
labelStr='Parameter';
btnPos=[x(1) y(10) w h];
REMORA.spice_dt_verify.headtext = uicontrol(REMORA.fig.spice_dt_verify, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColor3,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on'); 

labelStr='Min';
btnPos=[x(2) y(10) w/2 h];
REMORA.spice_dt_verify.headtext = uicontrol(REMORA.fig.spice_dt_verify, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColor3,...
    'String',labelStr, ...
    'FontUnits','normalized', ...    
    'FontWeight','bold',...
    'Visible','on'); 

labelStr='Max';
btnPos=[x(2)+w/2 y(10) w/2 h];
REMORA.spice_dt_verify.headtext = uicontrol(REMORA.fig.spice_dt_verify, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColor3,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on'); 


%% Peak2Peak Threshold Text
REMORA.fig.spice_dt_verify_bg1 = uibuttongroup(REMORA.fig.spice_dt_verify,...
    'Position',[x(1) y(12) w h*2],'BorderType','none');

if ~isfield(REMORA.spice_dt.detParams,'snrDet')
    REMORA.spice_dt.detParams.snrDet = 0;
end

labelStr = 'P-P RL Threshold (dBpp)';
btnPos=[0.1 .5 1 .5];
REMORA.spice_dt_verify.PPThresholdRadio = uicontrol(REMORA.fig.spice_dt_verify_bg1,...
   'Style','radiobutton',...
   'Units','normalized',...
   'Position',btnPos,...
   'Value',~REMORA.spice_dt.detParams.snrDet,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.PPThresholdTF),...
   'Callback','sp_dt_control(''setUsePPThreshBatch'')');%   'BackgroundColor',bgColor3,...

if ~REMORA.spice_dt.detParams.snrDet
    visiblePPThresh = 'on';
    visibleSNRThresh = 'off';
else
    visiblePPThresh = 'off';
    visibleSNRThresh = 'on';
end

% Peak2Peak Threshold Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.dBppThreshold);
btnPos=[x(2) y(11) w/2 h];
REMORA.spice_dt_verify.PPThresholdEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible',visiblePPThresh,...
    'Callback','sp_dt_control(''setPPThreshold'')');

labelStr = 'SNR RL Threshold (dB)';
btnPos=[0.1,0,1,.5];
REMORA.spice_dt_verify.SNRThresholdRadio = uicontrol(REMORA.fig.spice_dt_verify_bg1,...
   'Style','radiobutton',...
   'Units','normalized',...
   'Position',btnPos,...
   'Value',REMORA.spice_dt.detParams.snrDet,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.snrDetTF),...
   'Callback','sp_dt_control(''setUseSNRThreshBatch'')');%   'BackgroundColor',bgColor3,...

% SNR Threshold Editable Text
if ~isfield(REMORA.spice_dt.detParams,'snrThresh')
    REMORA.spice_dt.detParams.snrThresh = 10;
end

labelStr=num2str(REMORA.spice_dt.detParams.snrThresh);
btnPos=[x(2) y(12) w/2 h];
REMORA.spice_dt_verify.SNRThresholdEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible',visibleSNRThresh,...
    'Callback','sp_dt_control(''setSNRThreshold'')');

%% Bandpass Limits Text
labelStr = 'Bandpass Filter Edges (Hz)';
btnPos=[x(1)+.03 y(13)-ybuff w h];
REMORA.spice_dt_verify.BandPassText = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr),...
   'HorizontalAlignment','left',...
   'FontUnits','normalized', ...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.BandPass),...
   'Visible','on');%'BackgroundColor',bgColor3,...

% Minimum Bandpass Limit Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.bpRanges(1,1));
btnPos=[x(2) y(13) w/2 h];
REMORA.spice_dt_verify.MinBandPassEdText = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetMinBandpass'')');%'Enable', enbl, ...

% Maximum Bandpass Limit Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.bpRanges(1,2));
btnPos=[x(2)+(w/2) y(13) w/2 h];
REMORA.spice_dt_verify.MaxBandPassEdText = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetMaxBandpass'')');%    'Enable', enbl, ...

%% Click Duration Limits Text
labelStr = 'Click Duration Limits (us)';
btnPos=[x(1)+.03 y(14)-ybuff w h];
REMORA.spice_dt_verify.ClickDurLimText = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr),...
   'HorizontalAlignment','left',...
   'FontUnits','normalized', ...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.ClickDurLim),...
   'Visible','on');%'BackgroundColor',bgColor3,...

% Minimum Duration Limit Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.delphClickDurLims(1,1));
btnPos=[x(2) y(14) w/2 h];
REMORA.spice_dt_verify.MinClickDurEdText = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetMinClickDur'')');%'Enable', enbl, ...

% Maximum Duration Limit Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.delphClickDurLims(1,2));
btnPos=[x(2)+(w/2) y(14) w/2 h];
REMORA.spice_dt_verify.MaxClickDurEdText = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetMaxClickDur'')');%    'Enable', enbl, ...

%% Peak Frequency Limit Text
labelStr = 'Peak Freq Limits (kHz)';
btnPos=[x(1)+.03 y(15)-ybuff w h];
REMORA.spice_dt_verify.PeakFreqTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'HorizontalAlignment','left',...
   'FontUnits','normalized', ...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.PeakFreq),...
   'Visible','on');

% Minimum Peak Frequency Limit Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.cutPeakBelowKHz);
btnPos=[x(2) y(15) w/2 h];
REMORA.spice_dt_verify.MinPeakFreqEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetMinPeakFreq'')');%'Enable', enbl, ...

% Maximum Peak Frequency Limit Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.cutPeakAboveKHz);
btnPos=[x(2)+(w/2) y(15) w/2 h];
REMORA.spice_dt_verify.MaxPeakFreqEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetMaxPeakFreq'')'); %'Enable', enbl, ...

%% Envelope Energy Ratio Text
labelStr = 'Click Energy Envelope Ratio';
btnPos=[x(1)+.03 y(16)-ybuff w h];
REMORA.spice_dt_verify.dEvLimsTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'FontUnits','normalized',...
   'HorizontalAlignment','left',...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.dEnv),...
   'Visible','on');

% Minimum Envelope Limit Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.dEvLims(1));
btnPos=[x(2) y(16) w/2 h];
REMORA.spice_dt_verify.MinEvEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetMinEnvRatio'')');

% Maximum Envelope Limit Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.dEvLims(2));
btnPos=[x(2)+(w/2) y(16) w/2 h];
REMORA.spice_dt_verify.MaxEvEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetMaxEnvRatio'')');

%% Clipping Threshold Text
labelStr = 'Clip Threshold ( [0 - 1] )';
btnPos=[x(1)+.03 y(17)-ybuff w h];
REMORA.spice_dt_verify.clipThresholdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'HorizontalAlignment','left',...
   'FontUnits','normalized',...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.clipThreshold),...
   'Visible','on');

% Clipping Threshold Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.clipThreshold);
btnPos=[x(2)+(w/2) y(17) w/2 h];
REMORA.spice_dt_verify.clipThresholdEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetClipThreshold'')');

%% Post Processing Options
labelStr = 'Post-Processing Options';
btnPos=[x(1) y(18) w*2 h];
REMORA.spice_dt_verify.headtext = uicontrol(REMORA.fig.spice_dt_verify, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on'); 

%***********************************
% Remove Isolated Checkbox
%***********************************
labelStr = 'Remove Isolated Detections';
btnPos=[x(1)+w/8 y(19) w h];
REMORA.spice_dt_verify.rmIsolatedCheckbox = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'Value',REMORA.spice_dt.detParams.rmLonerClicks,...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.rmIsolated),...
   'Callback','sp_dt_control(''SetRmIsolated'')');

% Max gap to neighbor text
labelStr = 'Max Time Gap to Neighbor (sec)';
btnPos=[x(2) y(19)-ybuff w h];
REMORA.spice_dt_verify.maxNeighborTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'HorizontalAlignment','left',...
   'Position',btnPos,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'Visible','on');

labelStr=num2str(REMORA.spice_dt.detParams.maxNeighbor);
btnPos=[x(2)+(w*.75) y(19) w/4 h];
REMORA.spice_dt_verify.maxNeighborEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetMaxNeighbor'')');


%***********************************
% Remove Echos Checkbox
%***********************************
labelStr = 'Remove Echos';
btnPos=[x(1)+w/8 y(20) w h];
REMORA.spice_dt_verify.rmEchoCheckbox = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'Value',REMORA.spice_dt.detParams.rmEchos,...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.rmEchoTF),...
   'Callback','sp_dt_control(''SetRmEcho'')');

% Max gap to neighbor text
labelStr = 'Min. Gap Btwn Detections (sec)';
btnPos=[x(2) y(20)-ybuff w h];
REMORA.spice_dt_verify.lockoutTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'HorizontalAlignment','left',...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'Visible','on');

labelStr=num2str(REMORA.spice_dt.detParams.lockOut);
btnPos=[x(2)+(w*.75) y(20) w/4 h];
REMORA.spice_dt_verify.lockoutEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetLockout'')');


% Save Noise Checkbox
%***********************************
labelStr = 'Save Noise';
btnPos=[x(1)+w/8 y(21) w/2 h];
REMORA.spice_dt_verify.noiseCheckbox = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'Value',REMORA.spice_dt.detParams.saveNoise,...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.noiseTF),...
   'Callback','sp_dt_control(''SetNoise'')');
% Save for TPWS Checkbox
%***********************************
labelStr = 'Save for TPWS';
btnPos=[x(1)+w/8 y(22) w h];
REMORA.spice_dt_verify.saveForTPWSCheckbox = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'Value',REMORA.spice_dt.detParams.saveForTPWS,...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.saveForTPWSTF),...
   'Callback','sp_dt_control(''SetSaveforTPWS'')');

%% Modify with caution parameters
labelStr = 'Modify with Caution';
btnPos=[x(3) y(9) w*2 h];
REMORA.spice_dt_verify.headtext = uicontrol(REMORA.fig.spice_dt_verify, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorRed,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on'); 

%% Guided detection radio button
labelStr = 'Guided Detection (requires csv of times)';
btnPos=[x(3)+w/12 y(10) w*2 h];
REMORA.spice_dt_verify.GuidedDetCheckBox = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'Value',REMORA.spice_dt.detParams.guidedDetector,...
   'FontWeight','bold',...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.GuidedDetTF),...
   'Callback','sp_dt_control(''SetGuidedDetection'')');

% Guided detection
labelStr = 'File location';
btnPos=[x(3)+w/12 y(11)-ybuff w/2 h];
REMORA.spice_dt_verify.GuidedDetFileTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'HorizontalAlignment','left',...
   'String',labelStr,...
   'FontUnits','normalized',...
   'Visible','on');

% Guided detection Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.gDxls);
btnPos=[x(3)+(w/3)+(w/12) y(11) w*1.5 h];
REMORA.spice_dt_verify.GuidedDetFileEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetGuidedDetFile'')');

%% Wave file date regexp heading
labelStr = 'Wav File-Specific Parameters';
btnPos=[x(3)+w/12 y(13) w*2 h];
REMORA.spice_dt_verify.WavFileHeading = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'HorizontalAlignment','left',...
   'Position',btnPos,...
   'String',labelStr,...
   'FontWeight','bold',...
   'FontUnits','normalized', ...
   'Value',REMORA.spice_dt.detParams.guidedDetector,...
   'Visible','on');

% Wave file date regexp text
labelStr = 'Date/Time reg. exp. for filenames';
btnPos=[x(3) y(14)-ybuff w h];
REMORA.spice_dt_verify.WaveRegExpTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.WaveRegExp),...
   'Visible','on');

% Wave file Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.DateRegExp);
btnPos=[x(4) y(14) w/2 h];
REMORA.spice_dt_verify.WaveRegExpEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetWaveRegExp'')');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Buffers and thresholds heading
labelStr = 'Internal Buffers & Thresholds';
btnPos=[x(3)+w/12 y(16) w*2 h];
REMORA.spice_dt_verify.BufferHeading = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'HorizontalAlignment','left',...
   'Position',btnPos,...
   'String',labelStr,...
   'FontWeight','bold',...
   'FontUnits','normalized', ...
   'Value',REMORA.spice_dt.detParams.guidedDetector,...
   'Visible','on');

%% Low Res Buffer Text
labelStr = 'Low-res buffer (sec)';
btnPos=[x(3) y(17)-ybuff w h];
REMORA.spice_dt_verify.LRbufferTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.LRbuffer),...
   'Visible','on');

% Low Res Buffer Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.LRbuffer);
btnPos=[x(4) y(17) w/2 h];
REMORA.spice_dt_verify.LRBufferEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetLRBuffer'')');

%% Hi Res Buffer Text
labelStr = 'Hi-res buffer (sec)';
btnPos=[x(3) y(18)-ybuff w h];
REMORA.spice_dt_verify.HRBufferTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.HRBuffer),...
   'Visible','on');

% Hi Res Buffer Editable Text
labelStr = num2str(REMORA.spice_dt.detParams.HRbuffer);
btnPos=[x(4) y(18) w/2 h];
REMORA.spice_dt_verify.HRBufferEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetHRBuffer'')');

%% Merge Threshold Text
labelStr = 'Detection Merge Threshold (microsec)';
btnPos=[x(3) y(19)-ybuff w h];
REMORA.spice_dt_verify.mergeThresholdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.mergeThreshold),...
   'FontUnits','normalized', ...
   'Visible','on');

% Merge Threshold Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.mergeThr);
btnPos=[x(4) y(19) w/2 h];
REMORA.spice_dt_verify.mergeThresholdEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetMergeThreshold'')');

%% Start/End Energy Threshold Text
labelStr = 'Energy Percentile for Detection Onset';
btnPos=[x(3) y(20)-ybuff w h];
REMORA.spice_dt_verify.energyPercTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.energyPerc),...
   'Visible','on');

% Energy Percentile Threshold Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.energyPrctile);
btnPos=[x(4) y(20) w/2 h];
REMORA.spice_dt_verify.energyPercEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetEnergyPercentile'')');

%% Envelope Energy Threshold Text
labelStr = 'Envelope Duration Energy Threshold';
btnPos=[x(3) y(21)-ybuff w h];
REMORA.spice_dt_verify.energyThrTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'Visible','on');

% Energy Threshold Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.energyThr);
btnPos=[x(4) y(21) w/2 h];
REMORA.spice_dt_verify.energyThrEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetEnergyThr'')');

%% Band pass filter order
labelStr = 'Band-Pass Filter Order';
btnPos=[x(3) y(22)-ybuff w h];
REMORA.spice_dt_verify.BPfilterTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.BPfilterOrder),...
   'Visible','on');

% Band pass filter order Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.filterOrder);
btnPos=[x(4) y(22) w/2 h];
REMORA.spice_dt_verify.BPfilterEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetFilterOrder'')');

labelStr = 'Whiten';
btnPos=[x(4) y(23) w/2 h];
if ~isfield(REMORA.spice_dt.detParams,'whiten')
    REMORA.spice_dt.detParams.whiten = 0;
end
REMORA.spice_dt_verify.whitenCheck = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Value',REMORA.spice_dt.detParams.whiten,...
    'Visible','on',...
    'Callback','sp_dt_control(''SetWhiten'')');

%% Parpool size
labelStr = 'Parallel Pool Size';
if ~isfield(REMORA.spice_dt.detParams,'parpool')
    REMORA.spice_dt.detParams.parpool = 1;
end

btnPos=[x(3) y(23)-ybuff w h];
REMORA.spice_dt_verify.parpoolTxt = uicontrol(REMORA.fig.spice_dt_verify,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'TooltipString',sprintf(REMORA.spice_dt_verify.spHelpStrings.Parpool),...
   'Visible','on');

% Parpool size Editable Text
labelStr=num2str(REMORA.spice_dt.detParams.parpool);
btnPos=[x(4) y(23) w/2 h];
REMORA.spice_dt_verify.parpoolEdTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_control(''SetParpool'')');

%% Run button
labelStr = 'Run Detector';
btnPos=[x(2)+w/2 y(24) w h];
REMORA.spice_dt_verify.runTxt = uicontrol(REMORA.fig.spice_dt_verify,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',[.47,.67,.19],...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','sp_dt_control(''RunBatchDetection'')');

% % REMORA.spice_dt.SettingsControls = [REMORA.spice_dt_verify.PPThresholdTxt,...
% %     REMORA.spice_dt_verify.PPThresholdEdTxt,...
% %     REMORA.spice_dt_verify.ClickDurLimText,...
% %     REMORA.spice_dt_verify.MinClickDurEdText, REMORA.spice_dt_verify.MaxClickDurEdText,...
% %     REMORA.spice_dt_verify.PeakFreqTxt, ...  
% %     REMORA.spice_dt_verify.MinPeakFreqEdTxt, REMORA.spice_dt_verify.MaxPeakFreqEdTxt, ...  
% %     REMORA.spice_dt_verify.dEvLimsTxt,...
% %     REMORA.spice_dt_verify.MinEvEdTxt,REMORA.spice_dt_verify.MaxEvEdTxt,...
% %     REMORA.spice_dt_verify.clipThresholdTxt,REMORA.spice_dt_verify.clipThresholdEdTxt];

% set(REMORA.fig.spice_dt,'Visible','on');

end