function spice_dt_initcontrol
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% spice_dt_initcontrol.m
%
% initialize Detector Control Window GUI:
%   push buttons, sliders, radio buttons, editable text boxes, info text display
%
% ripped off from initcontrol triton v1.61
% mss 060905
%%
% Do not modify the following line, maintained by CVS
% $Id: dt_initcontrol.m,v 1.2 2008/01/11 21:31:49 msoldevilla Exp $
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
global REMORA PARAMS HANDLES DATA

% button grid layouts
% 14 rows, 4 columns
r = 16; % rows      (extra space for separations btw sections)
c = 2;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.25;
dx = 0.008;

% y position (relative units)
y = [0.9375];
y = horzcat(y, [.8594:-0.0625:0]);

% x position (relative units)
x = [0, w];

% colors
bgColor = [1 1 1];  % white
bgColor2 = [.75 1 .875]; % light green for LTSA
bgColor3 = [.75 .875 1]; % light blue for XWAV

% is an xwav file open? (There are some callbacks that depend on this!)
if isfield(PARAMS, 'xhd')
    enbl = 'on';
    f_enbl = get(HANDLES.motion.fwd, 'Enable');
    b_enbl = get(HANDLES.motion.back, 'Enable');
else
    enbl = 'off';
    f_enbl = 'off';
    b_enbl = 'off';
end

% load default settings
if PARAMS.ftype == 1 % if current file is wav
    settings_detector_wav_default
    REMORA.spice_dt.detParams = detParams;
else
    settings_detector_xwav_default
    REMORA.spice_dt.detParams = detParams;
end

% fill in some info from loaded file
detParams.channel = PARAMS.ch;
detParams.tfFullFile = PARAMS.tf.filename;
detParams.countThresholdTemp = prctile(DATA(:,detParams.channel),99.9);

detParams.xfrOffsetTemp = min(PARAMS.tf.uppc); % need to truncate this to fit feqs of interest
detParams.dBppThreshold = round(20*log10(detParams.countThreshold*2)+detParams.xfrOffsetTemp);

if PARAMS.filter
    detParams.bpRanges = [PARAMS.ff1,PARAMS.ff2];
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% handles for each of the spectrogram control objects
if ~isfield(REMORA.spice_dt, 'fig')
    REMORA.spice_dt.fig = struct;
    
    % Detection Parameters pulldown
    REMORA.spice_dt.fig.filemenu = uimenu(REMORA.fig.spice_dt,'Label','Save/Load Params',...
        'Enable','on','Visible','on');
    
    % Spectrogram load/save params
    uimenu(REMORA.spice_dt.fig.filemenu,'Label','&Load detector settings',...
        'Callback','spice_dt_paramspd(''spice_settingsLoad'')');
    uimenu(REMORA.spice_dt.fig.filemenu,'Label','&Save detector settings',...
        'Callback','spice_dt_paramspd(''spice_settingsSave'')');
end



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
%
% Spectrogram Controls
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
% ToDo:
% checkboxes for low and hi-res
%***********************************
% Spectrogram heading
%***********************************
labelStr='SPICE Detector Options';
btnPos=[x(1) y(1) 2*w h];
REMORA.spice_dt.headtext = uicontrol(REMORA.fig.spice_dt, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColor3,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'Visible','on'); 
%***********************************
%  Peak2Peak Threshold Text
%***********************************
labelStr = 'Threshold (dB_P_P)';
btnPos=[x(2) y(2) w h];
REMORA.spice_dt.PPThresholdTxt = uicontrol(REMORA.spice_fig.dt,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'BackgroundColor',bgColor3,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'Visible','on');
%***********************************
% Peak2Peak Threshold Editable Text
%***********************************
labelStr=num2str(REMORA.spice_dt.detParams.dBppThreshold);
btnPos=[x(2) y(3) w h];
REMORA.spice_dt.PPThresholdEdTxt = uicontrol(REMORA.fig.spice_dt,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dtcontrol(''setPPThreshold'')');
%***********************************
% Click Duration Limits Text
%***********************************
labelStr = 'Click Duration Limits (\musec)';
btnPos=[x(1)+dx y(4) (1-dx)*w h];
REMORA.spice_dt.ClickDurLimText = uicontrol(REMORA.fig.spice_dt,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'BackgroundColor',bgColor3,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'Visible','on');
%***********************************
% Minimum Duration Limit Editable Text
%***********************************
labelStr=num2str(REMORA.spice_dt.detParams.delphClickDurLims(1,1));
btnPos=[x(1)+dx y(5) (1-dx)*w h];
REMORA.spice_dt.MinClickDurEdText = uicontrol(REMORA.fig.dt,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Enable', enbl, ...
    'Callback','dtcontrol(''SetMinClickDur'')');

%***********************************
% Maximum Duration Limit Editable Text
%***********************************
labelStr=num2str(REMORA.spice_dt.detParams.delphClickDurLims(1,2));
btnPos=[x(1)+dx y(5) (1-dx)*w h];
REMORA.spice_dt.MaxClickDurEdText = uicontrol(REMORA.fig.dt,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Enable', enbl, ...
    'Callback','dtcontrol(''SetMaxClickDur'')');
%***********************************
% Peak Frequency Limit Text
%***********************************
labelStr = 'Peak Freq Limits (kHz)';
btnPos=[x(2) y(4) w h];
REMORA.spice_dt.PeakFreqTxt = uicontrol(REMORA.fig.dt,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'BackgroundColor',bgColor3,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'Visible','on');
%***********************************
% Minimum Peak Frequency Limit Editable Text
%***********************************
labelStr=num2str(REMORA.spice_dt.detParams.cutPeakBelowKHz);
btnPos=[x(2) y(5) w h];
REMORA.spice_dt.MinPeakFreqEdTxt = uicontrol(REMORA.fig.spice_dt,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Enable', enbl, ...
    'Callback','dtcontrol(''SetMinPeakFreq'')');
%***********************************
% Maximum Peak Frequency Limit Editable Text
%***********************************
labelStr=num2str(REMORA.spice_dt.detParams.cutPeakAboveKHz);
btnPos=[x(2) y(5) w h];
REMORA.spice_dt.MaxPeakFreqEdTxt = uicontrol(REMORA.fig.spice_dt,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Enable', enbl, ...
    'Callback','dtcontrol(''SetMaxPeakFreq'')');
%***********************************
% Envelope Limit Text
%***********************************
labelStr = 'Click Envelope Duration Limit(\musec)';
btnPos=[x(2) y(4) w h];
REMORA.spice_dt.dEvLimsTxt = uicontrol(REMORA.fig.spice_dt,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'BackgroundColor',bgColor3,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'Visible','on');
%***********************************
% Minimum Envelope Limit Editable Text
%***********************************
labelStr=num2str(REMORA.spice_dt.detParams.dEnvLims(1));
btnPos=[x(2) y(5) w h];
REMORA.spice_dt.MinPeakFreqEdTxt = uicontrol(REMORA.fig.spice_dt,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Enable', enbl, ...
    'Callback','dtcontrol(''SetMinPeakEnvDur'')');
%***********************************
% Maximum Envelope Limit Editable Text
%***********************************
labelStr=num2str(REMORA.spice_dt.detParams.dEnvLims(2));
btnPos=[x(2) y(5) w h];
REMORA.spice_dt.MaxPeakFreqEdTxt = uicontrol(REMORA.fig.spice_dt,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Enable', enbl, ...
    'Callback','dtcontrol(''SetMaxPeakEnvDur'')');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%***********************************
% Clipping Threshold Text
%***********************************
labelStr = 'Clip threshold (fraction of max possible amplitude (0,1))';
btnPos=[x(1)+dx y(6) (1-dx)*w h];
REMORA.spice_dt.clipThresholdTxt = uicontrol(REMORA.fig.spice_dt,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'BackgroundColor',bgColor3,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'Visible','on');
%***********************************
% Clipping Threshold Editable Text
%***********************************
labelStr=num2str(REMORA.spice_dt.detParams.clipThreshold);
btnPos=[x(1)+dx y(7) (1-dx)*w h];
REMORA.spice_dt.clipThresholdEdTxt = uicontrol(REMORA.fig.spice_dt,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dtcontrol(''SetClipThreshold'')');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Noise Subtraction Options
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%***********************************
% Mean Subtraction Text
%***********************************
% btnPos=[x(1) y(2) w h];
% labelStr = 'Mean Subtraction Duration (s)';
% REMORA.dt.MeanSubDurTxt = uicontrol(REMORA.fig.dt,...
%    'Style','text',...
%    'Units','normalized',...
%    'Position',btnPos,...
%    'BackgroundColor',bgColor3,...
%    'String',labelStr,...
%    'FontUnits','normalized', ...
%    'Visible','on');
%***********************************
% Mean Subtraction Editable Text
%***********************************
% btnPos = [x(1) y(3) w h];
% labelStr=num2str(REMORA.dt.params.MeanAve_s);
% REMORA.dt.MeanSubDurEdtxt = uicontrol(REMORA.fig.dt,...
%     'Style','edit',...
%     'Units','normalized',...
%     'Position',btnPos,...
%     'BackgroundColor',bgColor,...
%     'String',labelStr,...
%     'FontUnits','normalized', ...
%     'Visible','on',...
%     'Callback','dtcontrol(''MeanSubtractionDuration'')');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Figure Window Motion
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
w_third = (2*w)/3;
%*********************************
% The BACK button setup
%*********************************
labelStr='<';
btnPos=[x(1) y(15) w_third 2*h];
REMORA.spice_dt.back = uicontrol(REMORA.fig.spice_dt, ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',btnPos, ...
   'BackgroundColor',bgColor3,...
   'String',labelStr, ...
   'FontUnits','points', ...
   'FontSize', 8, ...
   'Enable', b_enbl, ...
   'Callback','spice_dt_motion(''back'')');
%*********************************
% The REFRESH button setup
%*********************************
labelStr='Refresh';
btnPos=[x(1)+w_third y(15) w_third 2*h];
REMORA.spice_dt.refresh = uicontrol(REMORA.fig.spice_dt, ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',btnPos, ...
   'BackgroundColor',bgColor3,...
   'String',labelStr, ...
   'FontUnits','points', ...
   'FontSize', 8, ...
   'Callback','spice_dt_motion(''refresh'')');
%*********************************
% The FORWARD button setup
%*********************************
labelStr='>';
btnPos=[x(2)+(w_third/2) y(15) w_third 2*h];
REMORA.spice_dt.fwd = uicontrol(REMORA.fig.spice_dt, ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',btnPos, ...
   'BackgroundColor',bgColor3,...
   'String',labelStr, ...     
   'FontUnits','points', ...
   'FontSize', 8, ...
   'Enable', f_enbl, ...
   'Callback','spice_dt_motion(''forward'')'); 


REMORA.spice_dt.SettingsControls = [REMORA.dt.MinBBFreqTxt, REMORA.dt.MinBBFreqEdtxt, ...
    REMORA.dt.MaxBBFreqTxt, REMORA.dt.MaxBBFreqEdtxt, ...
    REMORA.dt.MinBBSatTxt, REMORA.dt.MinBBSatEdtxt, ...  
    REMORA.dt.MaxBBSatTxt, REMORA.dt.MaxBBSatEdtxt, ...  
    REMORA.dt.BBThresholdTxt, REMORA.dt.BBThresholdEdtxt];

% set(REMORA.fig.dt,'Visible','on');



