function dt_initcontrol
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 
% dt_initcontrol.m
%
% initialize Detector Control Window GUI:
%   push buttons, sliders, radio buttons, editable text boxes, info text display
%
% ripped off from initcontrol triton v1.61
% mss 060905
%%
% Do not modify the following line, maintained by CVS
% $Id: dt_initcontrol.m,v 1.2 2008/01/11 21:31:49 msoldevilla Exp $
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
global REMORA PARAMS HANDLES

% button grid layouts
% 14 rows, 4 columns
r = 16; % rows      (extra space for separations btw sections)
c = 2;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.25;
dx = 0.008;

% y position (relative units)
y = [0.9375];
y = horzcat(y, [.8594:-0.0625:0]);

% x position (relative units)
x = [0, w];

% colors
bgColor = [1 1 1];  % white
bgColor2 = [.75 1 .875]; % light green for LTSA
bgColor3 = [.75 .875 1]; % light blue for XWAV

% is an xwav file open? (There are some callbacks that depend on this!)
if isfield(PARAMS, 'xhd')
    enbl = 'on';
    f_enbl = get(HANDLES.motion.fwd, 'Enable');
    b_enbl = get(HANDLES.motion.back, 'Enable');
else
    enbl = 'off';
    f_enbl = 'off';
    b_enbl = 'off';
end

1;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% handles for each of the spectrogram control objects
if ~isfield(REMORA.dt, 'fig')
    REMORA.dt.fig = struct;
    
    % Detection Parameters pulldown
    REMORA.dt.fig.filemenu = uimenu(REMORA.fig.dt,'Label','Save/Load Params',...
        'Enable','on','Visible','on');
    
    % Spectrogram load/save params
    uimenu(REMORA.dt.fig.filemenu,'Label','&Load Specgram ParamFile',...
        'Callback','dt_paramspd(''STparamload'')');
    uimenu(REMORA.dt.fig.filemenu,'Label','&Save Specgram ParamFile',...
        'Callback','dt_paramspd(''STparamsave'')');
end



%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 
%
% Spectrogram Controls
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% 

%***********************************
% Spectrogram heading
%***********************************
labelStr='Spectrogram Detector Options';
btnPos=[x(1) y(1) 2*w h];
REMORA.dt.headtext = uicontrol(REMORA.fig.dt, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColor3,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'Visible','on'); 
%***********************************
% Broadband Threshold Text
%***********************************
labelStr = 'Threshold (dB)';
btnPos=[x(2) y(2) w h];
REMORA.dt.BBThresholdTxt = uicontrol(REMORA.fig.dt,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'BackgroundColor',bgColor3,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'Visible','on');
%***********************************
% Broadband Threshold Editable Text
%***********************************
labelStr=num2str(REMORA.dt.params.Thresholds(2));
btnPos=[x(2) y(3) w h];
REMORA.dt.BBThresholdEdtxt = uicontrol(REMORA.fig.dt,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dtcontrol(''BBThreshold'')');
%***********************************
% Minimum Broadband Frequency Text
%***********************************
labelStr = 'Min Freq (Hz)';
btnPos=[x(1)+dx y(4) (1-dx)*w h];
REMORA.dt.MinBBFreqTxt = uicontrol(REMORA.fig.dt,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'BackgroundColor',bgColor3,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'Visible','on');
%***********************************
% Minimum Broadband Frequency Editable Text
%***********************************
labelStr=num2str(REMORA.dt.params.Ranges(2,1));
btnPos=[x(1)+dx y(5) (1-dx)*w h];
REMORA.dt.MinBBFreqEdtxt = uicontrol(REMORA.fig.dt,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Enable', enbl, ...
    'Callback','dtcontrol(''MinBroadbandFreq'')');
%***********************************
% Maximum Broadband Frequency Text
%***********************************
labelStr = 'Max Freq (Hz)';
btnPos=[x(2) y(4) w h];
REMORA.dt.MaxBBFreqTxt = uicontrol(REMORA.fig.dt,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'BackgroundColor',bgColor3,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'Visible','on');
%***********************************
% Maximum Broadband Frequency Editable Text
%***********************************
labelStr=num2str(REMORA.dt.params.Ranges(2,2));
btnPos=[x(2) y(5) w h];
REMORA.dt.MaxBBFreqEdtxt = uicontrol(REMORA.fig.dt,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Enable', enbl, ...
    'Callback','dtcontrol(''MaxBroadbandFreq'')');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Broadband bandwidth Info
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%***********************************
% Minimum Broadband Saturation Text
%***********************************
labelStr = 'Min Saturation (Hz)';
btnPos=[x(1)+dx y(6) (1-dx)*w h];
REMORA.dt.MinBBSatTxt = uicontrol(REMORA.fig.dt,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'BackgroundColor',bgColor3,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'Visible','on');
%***********************************
% Minimum Broadband Saturation Editable Text
%***********************************
labelStr=num2str(REMORA.dt.params.MinClickSaturation);
btnPos=[x(1)+dx y(7) (1-dx)*w h];
REMORA.dt.MinBBSatEdtxt = uicontrol(REMORA.fig.dt,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dtcontrol(''MinBBSaturation'')');
%***********************************
% Maximum Broadband Saturation Text
%***********************************
labelStr = 'Max Saturation (Hz)';
btnPos=[x(2) y(6) w h];
REMORA.dt.MaxBBSatTxt = uicontrol(REMORA.fig.dt,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'BackgroundColor',bgColor3,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'Visible','on');
%***********************************
% Maximum Broadband Bandwidth Editable Text
%***********************************
labelStr=num2str(REMORA.dt.params.MaxClickSaturation);
btnPos=[x(2) y(7) w h];
REMORA.dt.MaxBBSatEdtxt = uicontrol(REMORA.fig.dt,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dtcontrol(''MaxBBSaturation'')');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Noise Subtraction Options
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%***********************************
% Mean Subtraction Text
%***********************************
btnPos=[x(1) y(2) w h];
labelStr = 'Mean Subtraction Duration (s)';
REMORA.dt.MeanSubDurTxt = uicontrol(REMORA.fig.dt,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'BackgroundColor',bgColor3,...
   'String',labelStr,...
   'FontUnits','normalized', ...
   'Visible','on');
%***********************************
% Mean Subtraction Editable Text
%***********************************
btnPos = [x(1) y(3) w h];
labelStr=num2str(REMORA.dt.params.MeanAve_s);
REMORA.dt.MeanSubDurEdtxt = uicontrol(REMORA.fig.dt,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dtcontrol(''MeanSubtractionDuration'')');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Figure Window Motion
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
w_third = (2*w)/3;
%*********************************
% The BACK button setup
%*********************************
labelStr='<';
btnPos=[x(1) y(15) w_third 2*h];
REMORA.dt.back = uicontrol(REMORA.fig.dt, ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',btnPos, ...
   'BackgroundColor',bgColor3,...
   'String',labelStr, ...
   'FontUnits','points', ...
   'FontSize', 8, ...
   'Enable', b_enbl, ...
   'Callback','dt_motion(''back'')');
%*********************************
% The REFRESH button setup
%*********************************
labelStr='Refresh';
btnPos=[x(1)+w_third y(15) w_third 2*h];
REMORA.dt.refresh = uicontrol(REMORA.fig.dt, ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',btnPos, ...
   'BackgroundColor',bgColor3,...
   'String',labelStr, ...
   'FontUnits','points', ...
   'FontSize', 8, ...
   'Callback','dt_motion(''refresh'')');
%*********************************
% The FORWARD button setup
%*********************************
labelStr='>';
btnPos=[x(2)+(w_third/2) y(15) w_third 2*h];
REMORA.dt.fwd = uicontrol(REMORA.fig.dt, ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',btnPos, ...
   'BackgroundColor',bgColor3,...
   'String',labelStr, ...     
   'FontUnits','points', ...
   'FontSize', 8, ...
   'Enable', f_enbl, ...
   'Callback','dt_motion(''forward'')'); 


REMORA.dt.BBControls = [REMORA.dt.MinBBFreqTxt, REMORA.dt.MinBBFreqEdtxt, ...
    REMORA.dt.MaxBBFreqTxt, REMORA.dt.MaxBBFreqEdtxt, ...
    REMORA.dt.MinBBSatTxt, REMORA.dt.MinBBSatEdtxt, ...  
    REMORA.dt.MaxBBSatTxt, REMORA.dt.MaxBBSatEdtxt, ...  
    REMORA.dt.BBThresholdTxt, REMORA.dt.BBThresholdEdtxt];

% set(REMORA.fig.dt,'Visible','on');



