function dt_mkTPWS_gui

global REMORA
% button grid layouts
% 14 rows, 4 columns
% button grid layouts
% 14 rows, 4 columns
r = 18; % rows      (extra space for separations btw sections)
c = 4;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
% y position (relative units)
y = 1:-h:0;
xbuff = w*.1;

% x position (relative units)
x = 0:w:1;


% colors
bgColor = [1 1 1];  % white
bgColor3 = [.75 .875 1];
bgColor4 = [.76 .87 .78];
bgColorGray = [.86 .86 .86];  % gray
bgColorGrayLight = [.9 .9 .9];  % gray

% Setup variables:
defaultPos = [0.4,0.4,0.5,0.45];

dt_TPWS_initSettings
REMORA.dt.TPWS = default;
% open and setup figure window

REMORA.fig.dt_TPWS_verify = figure( ...
    'NumberTitle','off', ...
    'Name','Make TPWS from detections',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on');

REMORA.dt_TPWS_verify = [];
labelStr = 'Specify Detection Information';
btnPos=[0 y(2) w*c h];
REMORA.dt_TPWS_verify.headtext = uicontrol(REMORA.fig.dt_TPWS_verify, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',11,...
    'Visible','on',...
    'BackgroundColor',bgColor3);

%***********************************
% Detection Files Folder Text
%***********************************

labelStr = 'Detection Files Folder';
btnPos=[x(1)+xbuff y(3) w dy];
REMORA.dt_TPWS_verify.detDirTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','left',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Detection Files Folder Editable Text
labelStr = '';
btnPos=[x(2) y(3) w*2.5 dy];% btnPos=[x(1)+xbuff y(3) (w*c)*.7 dy];
REMORA.dt_TPWS_verify.detDirEdTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setDetDir'')');

% Detection Files Extension Popupmenu
labelStr = {'.cTg','.pgdf','.cHR','other'};
btnPos=[x(2)  y(4) (w*c)*.2 dy];
REMORA.dt_TPWS_verify.detFileExtPopup = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Value',1,...
    'Callback','dt_TPWS_control(''setDetFileExt'')');

%***********************************
% Audio Files Folder Text
%***********************************

% Audio Files Folder Text
labelStr = 'Audio File Folder';
btnPos=[x(1)+xbuff y(5)-ybuff*2 w dy];
REMORA.dt_TPWS_verify.recDirTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

% Audio Files Folder Editable Text
labelStr = '';
btnPos=[x(2) y(5)-ybuff*2 w*2.5 dy];
REMORA.dt_TPWS_verify.recDirEdTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setRecDir'')');

% Audio Files Extension Popupmenu
labelStr = {'x.wav','.wav'};
btnPos=[x(2)  y(6)-ybuff*2 (w*c)*.2 dy];
REMORA.dt_TPWS_verify.recFileExtPopup = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Value',1,...
    'Callback','dt_TPWS_control(''setRecFileExt'')');

%***********************************
% Output Folder Text
%***********************************

% Output Folder Text
labelStr = 'Output Folder';
btnPos=[x(1)+xbuff y(8) w dy];
REMORA.dt_TPWS_verify.outDirTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

% Output Folder Editable Text
labelStr = '';
btnPos=[x(2)  y(8) w*2.5 dy];
REMORA.dt_TPWS_verify.outDirEdTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setTPWSOutDir'')');

% Detection Files Folder Checkbox
labelStr = 'Create TPWS per subfolder (recommended if large number of detections)';
btnPos=[x(2)  y(9) (w*c)*2.5 dy];
REMORA.dt_TPWS_verify.byFolderCheckBox = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'Value',1,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setByFolder'')');

%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Commonly-Modified
labelStr = 'Commonly-Modified';
btnPos=[x(1) y(11) w*2 h];
REMORA.dt_TPWS_verify.modifyHeading = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontWeight','bold',...
    'FontUnits','normalized', ...
    'Visible','on',...
    'BackgroundColor',bgColor3);

% Parameter Text
labelStr = 'Parameter';
btnPos=[x(1) y(12) w h];
REMORA.dt_TPWS_verify.parameterHeading = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'BackgroundColor',bgColorGrayLight);

% Minimum Parameter Text
labelStr = 'Min';
btnPos=[x(2) y(12) w/2 h];
REMORA.dt_TPWS_verify.minHeading = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'BackgroundColor',bgColorGrayLight);

% Maximum Parameter Text
labelStr = 'Max';
btnPos=[x(2)+w/2 y(12) w/2 h];
REMORA.dt_TPWS_verify.maxHeading = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'BackgroundColor',bgColorGrayLight);

%***********************************
% Bandpass Filter Edges Text
%***********************************

% Bandpass Filter Edges Text
labelStr = 'Bandpass Filter Edges (Hz)';
btnPos=[x(1)+xbuff y(13) w h];
REMORA.dt_TPWS_verify.bpEdgeTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on');

% Minimum Parameter Text
labelStr = default.bpRanges(1);
btnPos=[x(2) y(13) w/2 h];
REMORA.dt_TPWS_verify.bpEdgeMinEdTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setbpEdgeMin'')');

% Maximum Parameter Text
labelStr = default.bpRanges(2);
btnPos=[x(2)+w/2 y(13) w/2 h];
REMORA.dt_TPWS_verify.bpEdgeMaxEdTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'BackgroundColor',bgColor,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setbpEdgeMax'')');

%***********************************
% Frame Length Text
%***********************************

% Frame Length Text
labelStr = 'Frame Length (ms)';
btnPos=[x(1)+xbuff y(14) w h];
REMORA.dt_TPWS_verify.frameTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on');

% Frame Length Value
labelStr = default.frameLength;
btnPos=[x(2)+w/2 y(14) w/2 h];
REMORA.dt_TPWS_verify.frameEdTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setFrame'')');

%***********************************
% Timeseries Length Text
%***********************************

% Timeseries Length Text
labelStr = 'Timeseries Length (ms)';
btnPos=[x(1)+xbuff y(15) w h];
REMORA.dt_TPWS_verify.timeseriesTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on');

% Timeseries Length Value
labelStr = default.timeseriesLength;
btnPos=[x(2)+w/2 y(15) w/2 h];
REMORA.dt_TPWS_verify.timeseriesEdTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setTimeseriesLength'')');

%% Optional settings
labelStr = 'Optional settings';
btnPos=[x(3)+xbuff/5 y(11) w*2 h];
REMORA.dt_TPWS_verify.optionalHeading = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontWeight','bold',...
    'BackgroundColor',bgColor,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'BackgroundColor',bgColor3);

%***********************************
% Transfer Function Text
%***********************************

% Transfer Function Text
labelStr = 'Transfer Function Path';
btnPos=[x(3)+xbuff y(12) w dy];
REMORA.dt_TPWS_verify.tfPathTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

% Transfer Function Editable Text
labelStr = '';
btnPos=[x(4)  y(12) w*.9 dy];
REMORA.dt_TPWS_verify.tfPathEdTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setTFPath'')');

%***********************************
% Filter String Text
%***********************************

% Filter String Text
labelStr = 'Partial String to Match';
btnPos=[x(3)+xbuff y(13) w dy];
REMORA.dt_TPWS_verify.filterStringTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','left',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

%  Filter String Editable Text
labelStr = '';
btnPos=[x(4)  y(13) w*.9 dy];% btnPos=[x(2)-xbuff/2 y(11) w*.9 dy];
REMORA.dt_TPWS_verify.filterStringEdTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setTPWSFilterString'')');

%***********************************
% Received Level Text
%***********************************

% Min RL Text
labelStr = 'Min. RL Threshold (dBpp)';
btnPos=[x(3)+xbuff y(14) w*1.5 dy];
REMORA.dt_TPWS_verify.minRLTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','left',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

%  Min RL Editable Text
labelStr = '';
btnPos=[x(4)  y(14) w/2*.8 dy];
REMORA.dt_TPWS_verify.minRLEdTxt = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setTPWSminRL'')');

%***********************************
% Trim Detections By Selected Features Text
%***********************************

% Trim Detections By Selected Features Checkbox
labelStr = 'Exclude Non-target Detections By Selected Features';
btnPos=[x(3)+xbuff y(15) w*2 h];
REMORA.dt_TPWS_verify.exclDetCheckbox = uicontrol(REMORA.fig.dt_TPWS_verify,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'Value',default.exclDetections,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setExclDet'')');

labelStr = 'Make TPWS Files';
btnPos=[x(2)+w/2  y(18) w 1.5*h];
REMORA.dt_TPWS_verify.refresh = uicontrol(REMORA.fig.dt_TPWS_verify, ...
    'Style','pushbutton', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColor4,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',11,...
    'Callback','dt_TPWS_control(''run_mkTPWS'')');


