function dt_mkTPWS_gui

global REMORA
% button grid layouts
% 14 rows, 4 columns
% button grid layouts
% 14 rows, 4 columns
r = 18; % rows      (extra space for separations btw sections)
c = 4;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
% y position (relative units)
y = 1:-h:0;
xbuff = w*.1;

% x position (relative units)
x = 0:w:1;


% colors
bgColor = [1 1 1];  % white
bgColor3 = [.75 .875 1]; % light green 
bgColorGray = [.86 .86 .86];  % gray
bgColorGrayLight = [.9 .9 .9];  % gray

% Setup variables:
defaultPos = [0.4,0.4,0.4,0.4];
% open and setup figure window

REMORA.fig.dt_mkTPWS = figure( ...
    'NumberTitle','off', ...
    'Name','Make TPWS from detections',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on');

REMORA.dt_mkTPWS = [];
labelStr = 'Specify Detection Information';
btnPos=[0 y(2) w*c h];
REMORA.dt_mkTPWS.headtext = uicontrol(REMORA.fig.dt_mkTPWS, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',11,...
    'Visible','on',...
    'BackgroundColor',bgColorGray); 

%***********************************
% Detection Files Folder Text
%***********************************

labelStr = 'Detection Files Folder';
btnPos=[x(1)+xbuff y(3) w dy];
REMORA.dt_mkTPWS.detDirTxt = uicontrol(REMORA.fig.dt_mkTPWS,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'HorizontalAlignment','left',...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');

% Detection Files Folder Editable Text
labelStr = 'Browse';
btnPos=[x(4)+w/2+xbuff y(3) w/3 dy];
handles.pushButton = uicontrol(REMORA.fig.dt_mkTPWS,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorGrayLight,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','right',...
    'Visible','on',...
    'Callback',@browse_Callback);

% Detection Files Folder Editable Text
labelStr = '';
btnPos=[x(2) y(3) w*2.5 dy];% btnPos=[x(1)+xbuff y(3) (w*c)*.7 dy];
REMORA.dt_mkTPWS.detDirEdTxt = uicontrol(REMORA.fig.dt_mkTPWS,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setDetDir'')');

% Detection Files Folder Checkbox
labelStr = 'Run on Subfolders';
btnPos=[x(2)  y(4) (w*c)*.7 dy];
REMORA.dt_mkTPWS.subDirCheckBox = uicontrol(REMORA.fig.dt_mkTPWS,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setSubDirTF'')');

% Detection Files Extension Popupmenu
labelStr = {'.cTg','.pgdf','.cHR','other'};
btnPos=[x(2)  y(5) (w*c)*.2 dy];
REMORA.dt_mkTPWS.detExtPopup = uicontrol(REMORA.fig.dt_mkTPWS,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Value',1,...
    'Callback','dt_TPWS_control(''setDetFileExt'')');

%***********************************
% Audio Files Folder Text
%***********************************

% Audio Files Folder Text
labelStr = 'Audio File Folder';
btnPos=[x(1)+xbuff y(7) w dy];
REMORA.dt_mkTPWS.xwavDirTxt = uicontrol(REMORA.fig.dt_mkTPWS,...
   'Style','text',...
   'Units','normalized',...
   'HorizontalAlignment','left',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');%   'BackgroundColor',bgColor3,...

% Audio Files Folder Editable Text
labelStr = '';
btnPos=[x(2) y(7) w*2.5 dy];
REMORA.dt_mkTPWS.xwavDirEdTxt = uicontrol(REMORA.fig.dt_mkTPWS,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setXwavDir'')');

% Audio Files Extension Popupmenu
labelStr = {'x.wav','.wav','other'};
btnPos=[x(2)  y(8) (w*c)*.2 dy];
REMORA.dt_mkTPWS.xwavExtPopup = uicontrol(REMORA.fig.dt_mkTPWS,...
    'Style','popupmenu',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Value',1,...
    'Callback','dt_TPWS_control(''setXwavFileExt'')');

%***********************************
% Output Folder Text
%***********************************

% Output Folder Text
labelStr = 'Output Folder';
btnPos=[x(1)+xbuff y(10) w dy];
REMORA.dt_mkTPWS.outDirTxt = uicontrol(REMORA.fig.dt_mkTPWS,...
   'Style','text',...
   'Units','normalized',...
   'HorizontalAlignment','left',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');%   'BackgroundColor',bgColor3,...

% Output Folder Editable Text
labelStr = '';
btnPos=[x(2)  y(10) w*2.5 dy];
REMORA.dt_mkTPWS.outDirEdTxt = uicontrol(REMORA.fig.dt_mkTPWS,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setTPWSOutDir'')');
%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Optional settings
labelStr = 'Optional settings:';
btnPos=[x(1)+xbuff y(12) w h];
REMORA.dt_mkTPWS.optionalHeading = uicontrol(REMORA.fig.dt_mkTPWS,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontWeight','bold',...
    'FontUnits','normalized', ...
    'Visible','on');

%***********************************
% Transfer Function Text
%***********************************

% Transfer Function Text
labelStr = 'Transfer Function Path';
btnPos=[x(1)+xbuff y(13) w dy];
REMORA.dt_mkTPWS.tfPathTxt = uicontrol(REMORA.fig.dt_mkTPWS,...
   'Style','text',...
   'Units','normalized',...
   'HorizontalAlignment','left',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');%   'BackgroundColor',bgColor3,...

% Transfer Function Editable Text
labelStr = '';
btnPos=[x(2)  y(13) w*2.5 dy];
REMORA.dt_mkTPWS.tfPathEdTxt = uicontrol(REMORA.fig.dt_mkTPWS,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setTFPath'')');

%***********************************
% Filter String Text
%***********************************

% Filter String Text
labelStr = 'Partial String to Match';
btnPos=[x(1)+xbuff y(14) w dy];
REMORA.dt_mkTPWS.filterStringTxt = uicontrol(REMORA.fig.dt_mkTPWS,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'HorizontalAlignment','left',...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');%   'BackgroundColor',bgColor3,...

%  Filter String Editable Text
labelStr = '';
btnPos=[x(2)  y(14) w*.9 dy];% btnPos=[x(2)-xbuff/2 y(11) w*.9 dy];
REMORA.dt_mkTPWS.filterStringEdTxt = uicontrol(REMORA.fig.dt_mkTPWS,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setTPWSFilterString'')');

%***********************************
% Received Level Text
%***********************************

% Min RL Text
labelStr = 'Min. RL Threshold (dBpp)';
btnPos=[x(1)+xbuff y(15) w*1.5 dy];
REMORA.dt_mkTPWS.minRLTxt = uicontrol(REMORA.fig.dt_mkTPWS,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'HorizontalAlignment','left',...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');%   'BackgroundColor',bgColor3,...

%  Min RL Editable Text
labelStr = '';
btnPos=[x(2)  y(15) w/2*.8 dy];
REMORA.dt_mkTPWS.minRLEdTxt = uicontrol(REMORA.fig.dt_mkTPWS,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','dt_TPWS_control(''setTPWSminRL'')');

%***********************************
% Store Features Text
%***********************************

% Detection Files Folder Checkbox
labelStr = 'Store Discriminative Features';
btnPos=[x(1)+xbuff  y(16) (w*c)*.7 dy];
REMORA.dt_mkTPWS.featCheckBox = uicontrol(REMORA.fig.dt_mkTPWS,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Value',0,...
    'Callback','dt_TPWS_control(''setStoreFeat'')');

labelStr = 'Make TPWS Files';
btnPos=[x(2)+w/2  y(18) w 1.5*h];
REMORA.dt_mkTPWS.refresh = uicontrol(REMORA.fig.dt_mkTPWS, ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',btnPos, ...
   'BackgroundColor',bgColor3,...
   'String',labelStr, ...
   'FontUnits','points', ...
   'FontWeight','bold',...
   'FontSize',11,...
   'Callback','dt_TPWS_control(''run_mkTPWS'')');




% --- Executes on button press in browse.
function browse_Callback(hObject, handles)
% hObject    handle to browse (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
dir = uigetdir();
if ~ isnumeric(dir)
    % User selected something
    set(hObject,'UserData',dir)
end
