function ex_init_detector_params_window

global REMORA

defaultPos = [0.25,0.35,0.38,0.4];
if isfield(REMORA.fig, 'fw')
    % Check if the figure already exists. If so, don't move it.
    if isfield(REMORA.fig.fw, 'detector') && isvalid(REMORA.fig.fw.detector)
        defaultPos = get(REMORA.fig.fw.detector,'Position');
    else
        REMORA.fig.fw.detector = figure;
    end
else 
    REMORA.fig.efw.detector = figure;
end

clf

set(REMORA.fig.fw.detector,'NumberTitle','off', ...
    'Name','Explosion Detector - v1.0',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on',...
    'ToolBar', 'none');

figure(REMORA.fig.fw.detector)

% Load/save settings pulldown:

if ~isfield(REMORA.fig.fw,'EXfileMenu') || ~isvalid(REMORA.fig.fw.EXfileMenu)
    REMORA.fig.fw.EXfileMenu = uimenu(REMORA.fig.fw.detector,'Label',...
        'Save/Load Settings','Enable','on','Visible','on');
    
    % Spectrogram load/save params:
    uimenu(REMORA.fig.fw.EXfileMenu,'Label','&Load Settings',...
        'Callback','fw_detector_control(''fw_detector_settingsLoad'')');
    uimenu(REMORA.fig.fw.EXfileMenu,'Label','&Save Settings',...
        'Callback','fw_detector_control(''fw_detector_settingsSave'')');
end

% Button grid layouts
% 14 rows, 2 columns
r = 15; % Rows (Extra space for separations between sections)
c = 2;  % Columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
% Y Position (Rrelative Units)
y = 1:-h:0;

% X Position (Relative Units)
x = 0:w:1;

% Colors
bgColor = [1 1 1];  % White
bgColorRed = [1 .6 .6];  % Red
% bgColorGray = [.86 .86 .86];  % Gray
bgColor3 = [.75 .875 1]; % Light Green 
bgColor4 = [.76 .87 .78]; % Light Blue 

REMORA.fw.verify = [];

REMORA.fw.params_help = fw_get_help_strings;

% Title:

labelStr = 'Fin Whale Index Detector Settings';
btnPos=[x(1) y(2) 2*w h];
REMORA.fw.detector.headtext = uicontrol(REMORA.fig.fw.detector, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',12,...
    'Visible','on');
% Set paths and strings
%***********************************
%% User text
labelSr = 'User ID';
btnPos=[x(1) y(3)-ybuff w/2 h];
REMORA.fw.verify.useridTxt = uicontrol(REMORA.fig.fw.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.fw.params_help.useridHelp)); 

% User ID Editable Text
labelStr=num2str(REMORA.fw.detect_params.userid);
btnPos=[x(1)+w/2 y(3) w h];
REMORA.fw.verify.useridEdTxt = uicontrol(REMORA.fig.fw.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','fw_detector_control(''setUserID'')');
%% Base Folder Text
labelStr = 'LTSA Directory';
btnPos=[x(1) y(4)-ybuff w/2 h];
REMORA.fw.verify.baseDirTxt = uicontrol(REMORA.fig.fw.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.fw.params_help.baseDirHelp));
%  'BackgroundColor',bgColor3,...

% Base Folder Editable Text
labelStr=num2str(REMORA.fw.detect_params.baseDir);
btnPos=[x(1)+w/2 y(4) w h];
REMORA.fw.verify.baseDirEdTxt = uicontrol(REMORA.fig.fw.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','fw_detector_control(''setbaseDir'')');

labelStr = 'Search Sub-Folders';
btnPos=[x(1)+w/2 y(5) w h];
REMORA.fw.verify.recursSearch = uicontrol(REMORA.fig.fw.detector,...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'Value',REMORA.fw.detect_params.recursSearch,...
   'FontUnits','normalized', ...
   'Visible','on',...
   'Callback','fw_detector_control(''recursSearch'')');

%% Output Folder Text
labelStr = 'Output Folder';
btnPos=[x(1) y(6)-ybuff w/2 h];
REMORA.fw.verify.outDirTxt = uicontrol(REMORA.fig.fw.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.fw.params_help.outDirHelp));%   'BackgroundColor',bgColor3,...

% Output Folder Editable Text
labelStr=num2str(REMORA.fw.detect_params.outDir);
btnPos=[x(1)+w/2 y(6) w h];
REMORA.fw.verify.outDirEdTxt = uicontrol(REMORA.fig.fw.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','fw_detector_control(''setOutDir'')');

%% Fin Whale Index Detector Settings Header
labelStr = 'Fin Whale Index Detector Parameters';
btnPos=[x(1) y(7) 2*w h-ybuff];
REMORA.fw.verify.detectParmTxt = uicontrol(REMORA.fig.fw.detector, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorRed,...
    'String',labelStr, ...
    'FontWeight','bold',...    
    'FontSize',11,...
    'FontUnits','points',...
    'Visible','on');

%% Bin size Text
labelStr = 'Bin size (minutes)';
btnPos=[x(1) y(9)-ybuff w/2 h];
REMORA.fw.verify.binsizeTxt = uicontrol(REMORA.fig.fw.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.fw.params_help.binsizeHelp));

% Bin size Editable Text
labelStr=num2str(REMORA.fw.detect_params.binsize);
btnPos=[x(1)+w/2 y(9) w/4 h];
REMORA.fw.verify.binsizeEdTxt = uicontrol(REMORA.fig.fw.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','fw_detector_control(''setBin'')');

%% Granularity Text
labelStr = 'Granularity';
btnPos=[x(1) y(10)-ybuff w/2 h];
REMORA.fw.verify.granularityTxt = uicontrol(REMORA.fig.fw.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.fw.params_help.granularityHelp));

% Granularity drop-down box
labelStr={'call','encounter','binned'};
btnPos=[x(1)+w/2 y(10) w/4 h];
REMORA.fw.verify.granularity = uicontrol(REMORA.fig.fw.detector,...
    'Style','popup',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','fw_detector_control(''setGranularity'')');
%% Threshold Text
labelStr = 'Threshold';
btnPos=[x(1) y(11)-ybuff w/2 h];
REMORA.fw.verify.thresholdTxt = uicontrol(REMORA.fig.fw.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.fw.params_help.thresholdHelp));

% Threshold Editable Text
labelStr=num2str(REMORA.fw.detect_params.threshold);
btnPos=[x(1)+w/2 y(11) w/4 h];
REMORA.fw.verify.threshEdTxt = uicontrol(REMORA.fig.fw.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','fw_detector_control(''setThresh'')');

%% Call Frequency Text
labelStr = 'Call Frequency';
btnPos=[x(1) y(12)-ybuff w/2 h];
REMORA.fw.verify.callfreqTxt = uicontrol(REMORA.fig.fw.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.fw.params_help.thresholdOffsetHelp));

% Threshold Editable Text
labelStr=num2str(REMORA.fw.detect_params.c2_offset);
btnPos=[x(1)+w/2 y(12) w/4 h];
REMORA.fw.verify.callfreqEdTxt = uicontrol(REMORA.fig.fw.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','fw_detector_control(''setCallFreq'')');

%% Lower noise band Text
labelStr = 'Lower Noise Band';
btnPos=[x(1) y(13)-ybuff w/2 h];
REMORA.fw.verify.minNoiseTxt = uicontrol(REMORA.fig.fw.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.fw.params_help.minNoiseHelp));

% Minimum Time Distance Editable Text
labelStr=num2str(REMORA.fw.detect_params.nfreq1);
btnPos=[x(1)+w/2 y(13) w/4 h];
REMORA.fw.verify.minNoiseEdTxt = uicontrol(REMORA.fig.fw.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','fw_detector_control(''setLowNoise'')');

%% # Higher noise band Text
labelStr = 'Higher Noise Band';
btnPos=[x(1) y(14)-ybuff w/2 h];
REMORA.fw.verify.highNoiseTxt = uicontrol(REMORA.fig.fw.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.fw.params_help.highNoiseHelp));

% Higher noise band Editable Text
labelStr=num2str(REMORA.fw.detect_params.nfreq2);
btnPos=[x(1)+w/2 y(14) w/4 h];
REMORA.fw.verify.highNoiseEdText = uicontrol(REMORA.fig.fw.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','fw_detector_control(''setHighNoise'')');

%% Run Button
labelStr = 'Run Fin Whale Index Detector';
btnPos=[x(2)-w/2 y(15) w h];

REMORA.fw.verify.runTxt = uicontrol(REMORA.fig.fw.detector,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor3,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','fw_detector_control(''runFinWhaleIndexDetector'')');
