function bp_init_batch_gui
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% sh_init_batch_gui.m
%
% Verify settings in GUI before running on entire drive.
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
global REMORA

% button grid layouts
% 14 rows, 4 columns
r = 17; % rows      (extra space for separations btw sections)
c = 2;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
xbuff = w*.1;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;

% colors
bgColor = [1 1 1];  % white
bgColorGrayLight = [.92 .92 .92];  % gray
bgColorGray = [.86 .86 .86];  % gray

REMORA.bp_verify = [];
labelStr = 'Fin Whale Index Detector Settings';
btnPos=[x(1) y(2) w*2 h];
REMORA.bp_verify.headtext = uicontrol(REMORA.fig.bp.detector, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');


% Set paths and strings
%***********************************
%% User text
labelStr = 'User ID';
btnPos=[x(1)+xbuff*2 y(3) w dy];
REMORA.bp.verify.useridTxt = uicontrol(REMORA.fig.bp.detector,...
   'Style','text',...
   'Units','normalized',...
   'HorizontalAlignment','left',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');

% User ID Editable Text
labelStr=num2str(REMORA.bp.settings.userid);
btnPos=[x(2)-w/4 y(3) w/4 dy];
REMORA.bp.verify.useridEdTxt = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','bp_detector_control(''setUserID'')');
%%
% Input Folder Text
labelStr = 'LTSA directory';
btnPos=[x(1)+xbuff*2  y(4) w dy];
REMORA.bp_verify.inDirTxt = uicontrol(REMORA.fig.bp.detector,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Input Folder Editable Text
labelStr=num2str(REMORA.bp.settings.inDir);
btnPos=[x(2)-w/4 y(4) w*1.2 dy];
REMORA.bp_verify.inDirEdTxt = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bp_detector_control(''setInDir'')');

% Transfer Function File Text
labelStr = 'Transfer Function';
btnPos=[x(1)+xbuff*2 y(5) w dy];
REMORA.bp_verify.tffileTxt = uicontrol(REMORA.fig.bp.detector,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Transfer Function File Editable Text
labelStr=num2str(REMORA.bp.settings.tffile);
btnPos=[x(2)-w/4 y(5) w*1.2 dy];
REMORA.bp_verify.tffileEdTxt = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bp_detector_control(''setTFfile'')');

% Output Folder Text
labelStr = 'Output Folder';
btnPos=[x(1)+xbuff*2  y(6) w dy];
REMORA.bp_verify.OutDirTxt = uicontrol(REMORA.fig.bp.detector,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Output Folder Editable Text
labelStr=num2str(REMORA.bp.settings.outDir);
btnPos=[x(2)-w/4 y(6) w*1.2 dy];
REMORA.bp_verify.OutDirEdTxt = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bp_detector_control(''setOutDir'')');

% Link to Tethys checkbox
labelStr = 'Link to Tethys';
btnPos=[x(2)-w/4 y(7) w dy];
REMORA.bp_verify.tethysCheck = uicontrol(REMORA.fig.bp.detector,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'Value',REMORA.bp.settings.Tethys,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bp_detector_control(''checkTethys'')');

    
%% Detector settings
labelStr = 'Adjustable Detector Settings';
btnPos=[x(1) y(8) w*2 h];
REMORA.bp_verify.headtext = uicontrol(REMORA.fig.bp.detector, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');


% col names
labelStr='Parameter';
btnPos=[x(1)-xbuff*4 y(9) w*1.5 h];
REMORA.bp_verify.headtext = uicontrol(REMORA.fig.bp.detector, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGrayLight,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');

labelStr='Value';
btnPos=[x(2)-xbuff*3.5 y(9) w*1.5 h];
REMORA.bp_verify.headtext = uicontrol(REMORA.fig.bp.detector, ...
    'Style','text', ...
    'Units','normalized', ...
    'HorizontalAlignment','center',...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGrayLight,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');


%***********************************
% Threshold Text
%***********************************

%  Threshold Text
labelStr = 'Threshold (dB)';
btnPos=[x(1)+xbuff*2 y(10)-ybuff w*2 h];
REMORA.bp_verify.ThreshText = uicontrol(REMORA.fig.bp.detector,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Threshold Editable Text
labelStr=num2str(REMORA.bp.settings.thresh(1,1));
btnPos=[x(2) y(10) w*0.75 dy];
REMORA.bp_verify.ThreshEdText = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bp_detector_control(''setThresh'')');

%***********************************
% Binsize
%***********************************
%   Binsize text
labelStr= 'Binsize';
btnPos =[x(1)+xbuff*2 y(11)-ybuff w*2 h];
REMORA.bp_verify.BinText = uicontrol(REMORA.fig.bp.detector,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized',...
    'Visible','on');

% Binsize Editable Text
labelStr=num2str(REMORA.bp.settings.binsize(1,1));
btnPos=[x(2) y(11) w*0.75 dy];
REMORA.bp_verify.BinEdText = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bp_detector_control(''setBin'')');

%***********************************
% Granularity Text
%***********************************
%   Granularity text
labelStr= 'Granularity';
btnPos =[x(1)+xbuff*2 y(12)-ybuff w*2 h];
REMORA.bp_verify.GranText = uicontrol(REMORA.fig.bp.detector,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized',...
    'Visible','on');

% Granularity Editable Text
labelStr=num2str(REMORA.bp.settings.granularity);
btnPos=[x(2) y(12) w*0.75 dy];
REMORA.bp_verify.GranEdText = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bp_detector_control(''setGranularity'')');

%***********************************
% Call Frequency Text
%***********************************
%   Call frequency text
labelStr= 'Call Frequency';
btnPos =[x(1)+xbuff*2 y(13)-ybuff w*2 h];
REMORA.bp_verify.CallFreqText = uicontrol(REMORA.fig.bp.detector,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized',...
    'Visible','on');

% Call Frequency Editable Text
labelStr=num2str(REMORA.bp.settings.callfreq);
btnPos=[x(2) y(13) w*0.75 dy];
REMORA.bp_verify.callFreqEdText = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bp_detector_control(''setCallFreq'')');

%***********************************
% Noise Text
%***********************************
%   Noise text
labelStr= 'Noise';
btnPos =[x(1)+xbuff*2 y(14)-ybuff w/2 h];
REMORA.bp_verify.NoiseText = uicontrol(REMORA.fig.bp.detector,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized',...
    'Visible','on');

% Low Noise Text
labelStr= 'Low';
btnPos =[x(2) y(14)-ybuff w/4 h];
REMORA.bp_verify.LowNoiseText = uicontrol(REMORA.fig.bp.detector,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized',...
    'Visible','on');

% Low Noise Editable Text
labelStr=num2str(REMORA.bp.settings.nfreq1);
btnPos=[x(2)+xbuff y(14) w/4 dy];
REMORA.bp_verify.LowNoiseEdText = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bp_detector_control(''setLowNoise'')');

% High Noise Text
labelStr= 'High';
btnPos =[x(2)+xbuff*4 y(14)-ybuff w/4 h];
REMORA.bp_verify.HighNoiseText = uicontrol(REMORA.fig.bp.detector,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized',...
    'Visible','on');

% High Noise Editable Text
labelStr=num2str(REMORA.bp.settings.nfreq2);
btnPos=[x(2)+xbuff*5 y(14) w/4 dy];
REMORA.bp_verify.HighNoiseEdText = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bp_detector_control(''setHighNoise'')');

%***********************************
% File type Text
%***********************************
%labelStr = 'HARP Data';
%btnPos=[x(1)+xbuff*2 y(9) w h];
%REMORA.bp_verify.HARPdataCheckbox = uicontrol(REMORA.fig.bp.batch,...
%    'Style','checkbox',...
%    'Units','normalized',...
%    'Position',btnPos,...
%    'String',labelStr,...
%    'Value',REMORA.bp.settings.HARPdata,...
%    'FontUnits','normalized', ...
%    'Visible','on',...
%    'Callback','bp_detector_control(''setHARPdata'')');

%labelStr = 'Sound Trap Data';
%btnPos=[x(2) y(9) w h];
%REMORA.bp_verify.SoundTrapdataCheckbox = uicontrol(REMORA.fig.bp.batch,...
%    'Style','checkbox',...
%    'Units','normalized',...
%    'Position',btnPos,...
%    'String',labelStr,...
%    'Value',REMORA.bp.settings.SoundTrap,...
%    'FontUnits','normalized', ...
%    'Visible','on',...
%    'Callback','bp_detector_control(''setSoundTrapdata'')');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%***********************************
% Save .tlab file Checkbox
%***********************************
%labelStr = 'Create .csv Output File';
%btnPos=[x(1)+xbuff*2 y(10) w h];
%REMORA.bp_verify.csvCheckbox = uicontrol(REMORA.fig.bp.batch,...
%    'Style','checkbox',...
%    'Units','normalized',...
%    'Position',btnPos,...
%    'String',labelStr,...
%    'Value',REMORA.bp.settings.saveCsv,...
%    'FontUnits','normalized', ...
%    'Visible','on',...
%    'Callback','bp_detector_control(''setCsvFile'')');

% Run button
labelStr = 'Run Detector';
btnPos=[x(1)+1/2*w y(16) w h];
REMORA.bp_verify.RunDetectorEdTxt = uicontrol(REMORA.fig.bp.detector,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',[.47,.67,.19],...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','bp_detector_control(''RunFinwhaleIndexDetector'')');



