function bp_init_detector_params_window

global REMORA

defaultPos = [0.25,0.35,0.38,0.4];
REMORA.fig.bp.detector = figure('NumberTitle','off', ...
    'Name','Fin Whale Index Detector - v1.0',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on',...
    'ToolBar', 'none');

% Button grid layouts
% 14 rows, 2 columns
r = 15; % Rows (Extra space for separations between sections)
c = 2;  % Columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
% Y Position (Rrelative Units)
y = 1:-h:0;

% X Position (Relative Units)
x = 0:w:1;

% Colors
bgColor = [1 1 1];  % White
bgColorRed = [1 .6 .6];  % Red
% bgColorGray = [.86 .86 .86];  % Gray
bgColor3 = [.75 .875 1]; % Light Green 
bgColor4 = [.76 .87 .78]; % Light Blue 

REMORA.bp.verify = [];

%REMORA.bp.params_help = bp_get_help_strings;

% Title:

labelStr = 'Fin Whale Index Detector Settings';
btnPos=[x(1) y(2) 2*w h];
REMORA.bp.detector.headtext = uicontrol(REMORA.fig.bp.detector, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',12,...
    'Visible','on');
% Set paths and strings
%***********************************
%% User text
labelSr = 'User ID';
btnPos=[x(1) y(3)-ybuff w/2 h];
REMORA.bp.verify.useridTxt = uicontrol(REMORA.fig.bp.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');

% User ID Editable Text
labelStr=num2str(REMORA.bp.detect_params.userid);
btnPos=[x(1)+w/2 y(3) w h];
REMORA.bp.verify.useridEdTxt = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','bp_detector_control(''setUserID'')');
%% Base Folder Text
labelStr = 'LTSA Directory';
btnPos=[x(1) y(4)-ybuff w/2 h];
REMORA.bp.verify.baseDirTxt = uicontrol(REMORA.fig.bp.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');
%  'BackgroundColor',bgColor3,...

% Base Folder Editable Text
labelStr=num2str(REMORA.bp.detect_params.baseDir);
btnPos=[x(1)+w/2 y(4) w h];
REMORA.bp.verify.baseDirEdTxt = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','bp_detector_control(''setbaseDir'')');

labelStr = 'Search Sub-Folders';
btnPos=[x(1)+w/2 y(5) w h];
REMORA.bp.verify.recursSearch = uicontrol(REMORA.fig.bp.detector,...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'Value',REMORA.bp.detect_params.recursSearch,...
   'FontUnits','normalized', ...
   'Visible','on',...
   'Callback','bp_detector_control(''recursSearch'')');

%% Output Folder Text
labelStr = 'Output Folder';
btnPos=[x(1) y(6)-ybuff w/2 h];
REMORA.bp.verify.outDirTxt = uicontrol(REMORA.fig.bp.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');%   'BackgroundColor',bgColor3,...

% Output Folder Editable Text
labelStr=num2str(REMORA.bp.detect_params.outDir);
btnPos=[x(1)+w/2 y(6) w h];
REMORA.bp.verify.outDirEdTxt = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bp_detector_control(''setOutDir'')');

%% Fin Whale Index Detector Settings Header
labelStr = 'Fin Whale Index Detector Parameters';
btnPos=[x(1) y(7) 2*w h-ybuff];
REMORA.bp.verify.detectParmTxt = uicontrol(REMORA.fig.bp.detector, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorRed,...
    'String',labelStr, ...
    'FontWeight','bold',...    
    'FontSize',11,...
    'FontUnits','points',...
    'Visible','on');

%% Bin size Text
labelStr = 'Bin size (minutes)';
btnPos=[x(1) y(9)-ybuff w/2 h];
REMORA.bp.verify.binsizeTxt = uicontrol(REMORA.fig.bp.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');

% Bin size Editable Text
labelStr=num2str(REMORA.bp.detect_params.binsize);
btnPos=[x(1)+w/2 y(9) w/4 h];
REMORA.bp.verify.binsizeEdTxt = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bp_detector_control(''setBin'')');

%% Granularity Text
labelStr = 'Granularity';
btnPos=[x(1) y(10)-ybuff w/2 h];
REMORA.bp.verify.granularityTxt = uicontrol(REMORA.fig.bp.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');

% Granularity drop-down box
labelStr={'call','encounter','binned'};
btnPos=[x(1)+w/2 y(10) w/4 h];
REMORA.bp.verify.granularity = uicontrol(REMORA.fig.bp.detector,...
    'Style','popup',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bp_detector_control(''setGranularity'')');
%% Threshold Text
labelStr = 'Threshold';
btnPos=[x(1) y(11)-ybuff w/2 h];
REMORA.bp.verify.thresholdTxt = uicontrol(REMORA.fig.bp.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');

% Threshold Editable Text
labelStr=num2str(REMORA.bp.detect_params.threshold);
btnPos=[x(1)+w/2 y(11) w/4 h];
REMORA.bp.verify.threshEdTxt = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bp_detector_control(''setThresh'')');

%% Call Frequency Text
labelStr = 'Call Frequency';
btnPos=[x(1) y(12)-ybuff w/2 h];
REMORA.bp.verify.callfreqTxt = uicontrol(REMORA.fig.bp.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');

% Threshold Editable Text
labelStr=num2str(REMORA.bp.detect_params.c2_offset);
btnPos=[x(1)+w/2 y(12) w/4 h];
REMORA.bp.verify.callfreqEdTxt = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bp_detector_control(''setCallFreq'')');

%% Lower noise band Text
labelStr = 'Lower Noise Band';
btnPos=[x(1) y(13)-ybuff w/2 h];
REMORA.bp.verify.minNoiseTxt = uicontrol(REMORA.fig.bp.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');

% Minimum Time Distance Editable Text
labelStr=num2str(REMORA.bp.detect_params.nfreq1);
btnPos=[x(1)+w/2 y(13) w/4 h];
REMORA.bp.verify.minNoiseEdTxt = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bp_detector_control(''setLowNoise'')');

%% # Higher noise band Text
labelStr = 'Higher Noise Band';
btnPos=[x(1) y(14)-ybuff w/2 h];
REMORA.bp.verify.highNoiseTxt = uicontrol(REMORA.fig.bp.detector,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');

% Higher noise band Editable Text
labelStr=num2str(REMORA.bp.detect_params.nfreq2);
btnPos=[x(1)+w/2 y(14) w/4 h];
REMORA.bp.verify.highNoiseEdText = uicontrol(REMORA.fig.bp.detector,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bp_detector_control(''setHighNoise'')');

%% Run Button
labelStr = 'Run Fin Whale Index Detector';
btnPos=[x(2)-w/2 y(15) w h];

REMORA.bp.verify.runTxt = uicontrol(REMORA.fig.bp.detector,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor3,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','bp_detector_control(''runFinWhaleIndexDetector'')');
