function bp_init_batch_figure

global REMORA

defaultPos = [0.25,0.25,0.3,0.6];
REMORA.fig.bp.batch = figure( ...
    'NumberTitle','off', ...
    'Name','Fin Whale Index Detector Batch - v1.0',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on');

% Detection Settings pulldown
REMORA.bp.menuBatch = uimenu(REMORA.fig.bp.batch,'Label','&Load Settings',...
    'Enable','on','Visible','on');

% Spectrogram load/save params
uimenu(REMORA.bp.menuBatch,'Label','&Select Detector Settings File',...
    'Callback','bp_gui_pulldown(''settingsLoadBatch'')');
