function bp_tethys_figure

global REMORA

defaultPos = [0.6,0.1,0.2,0.2];
REMORA.fig.bp.tethys = figure(...
    'NumberTitle','off',...
    'Name','Tethys metadata',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos,...
    'Visible','on');