function bp_tethys_gui
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
global REMORA

% button grid layouts
r = 7; % rows      (extra space for separations btw sections)
c = 2;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
xbuff = w*.1;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;

% colors
bgColor = [1 1 1];  % white
bgColorGrayLight = [.92 .92 .92];  % gray
bgColorGray = [.86 .86 .86];  % gray
%REMORA.bp_verify = [];

labelStr = 'Metadata for Tethys';
btnPos=[x(1) y(2) w*2 h];
REMORA.bp_verify.metatext = uicontrol(REMORA.fig.bp.tethys, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');


% Set paths and strings
%***********************************
%% User text
labelStr = 'User ID';
btnPos=[x(1)+xbuff*2 y(4) w dy];
REMORA.bp_verify.useridTxt = uicontrol(REMORA.fig.bp.tethys,...
   'Style','text',...
   'Units','normalized',...
   'HorizontalAlignment','left',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');

% User ID Editable Text
labelStr=num2str(REMORA.bp.settings.userid);
btnPos=[x(2)-w/4 y(4) w dy];
REMORA.bp_verify.useridEdTxt = uicontrol(REMORA.fig.bp.tethys,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','bp_detector_control(''setUserID'')');

%% Project text
labelStr = 'Project';
btnPos=[x(1)+xbuff*2 y(5) w dy];
REMORA.bp_verify.projectTxt = uicontrol(REMORA.fig.bp.tethys,...
   'Style','text',...
   'Units','normalized',...
   'HorizontalAlignment','left',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');

% Project Editable Text
labelStr=num2str(REMORA.bp.settings.project);
btnPos=[x(2)-w/4 y(5) w dy];
REMORA.bp_verify.projectEdTxt = uicontrol(REMORA.fig.bp.tethys,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','bp_detector_control(''setProject'')');

%% Site text
labelStr = 'Site';
btnPos=[x(1)+xbuff*2 y(6) w dy];
REMORA.bp_verify.siteTxt = uicontrol(REMORA.fig.bp.tethys,...
   'Style','text',...
   'Units','normalized',...
   'HorizontalAlignment','left',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');

% Site Editable Text
labelStr=num2str(REMORA.bp.settings.site);
btnPos=[x(2)-w/4 y(6) w dy];
REMORA.bp_verify.siteEdTxt = uicontrol(REMORA.fig.bp.tethys,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','bp_detector_control(''setSite'')');

%% Deployment text
labelStr = 'Deployment';
btnPos=[x(1)+xbuff*2 y(7) w dy];
REMORA.bp_verify.deploymentTxt = uicontrol(REMORA.fig.bp.tethys,...
   'Style','text',...
   'Units','normalized',...
   'HorizontalAlignment','left',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');

% Deployment Editable Text
labelStr=num2str(REMORA.bp.settings.deployment);
btnPos=[x(2)-w/4 y(7) w dy];
REMORA.bp_verify.deploymentEdTxt = uicontrol(REMORA.fig.bp.tethys,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','bp_detector_control(''setDepl'')');