function batchLTSA_init_gui
% BATCHLTSA_INIT_GUI    Creates set up GUI windo for batchLTSA remora
%
%   Syntax:
%       BATCHLTSA_INIT_GUI
%
%   Description:
%       Populates the set up GUI window with push buttons, editable text
%       boxes, radio buttons, and informational text where a user defines
%       the desired settings. Each interaction with the GUI calles an
%       action in BATCHLTSA_CONTROL.
%
%       The GUI window includes an option to set the directory that
%       contains sound files (either manually or using a Browse button),
%       the raw sound file type (XWAV, WAV, or FLAC), initial broad LTSA
%       settings (time average and frequency average; these can be modified
%       by individual directory later), whether the data is single or
%       multichannel, and if it is multichannel how many or which channel
%       to create LTSAs for (can do all channels by setting to 0 or select
%       a single channel)
%
%   Inputs:
%       calls global REMORA
%
%	Outputs:
%       updates global REMORA
%
%   Examples:
%
%   See also BATCHLTSA_CONTROL
%
%   Authors:
%       S. Fregosi <selene.fregosi@gmail.com> <https://github.com/sfregosi>
%
%   Updated:   04 May 2025
%
%   Created with MATLAB ver.: 24.2.0.2740171 (R2024b) Update 1
% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

global REMORA

% button grid layouts
% 8 rows, 5 columns
r = 9; % rows      (extra space for separations btw sections)
c = 5;  % columns
h = 1/r;
w = 1/c;
ph = h * 0.8; % padded height for buttons/boxes leaves a bit of padding
pw = w * 0.9; % padded width
ybuff = h*.2;
ycenter = h*.25;
xbuff = w*.1;
% y position (relative units)
y = 1:-h:0;
% x position (relative units)
x = 0:w:1;

% colors
bgColor = [1 1 1];  % white
bgColorGrayLight = [.92 .92 .92];  % gray
bgColorGray = [.86 .86 .86];  % gray

%% Set Directory Section

REMORA.batchLTSA_verify = [];
labelStr = 'Set Directory';
btnPos=[x(1) y(2) w*5 ph];
REMORA.batchLTSA_verify.headtext = uicontrol(REMORA.fig.batchLTSA, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',12,...
    'Visible','on');

%***********************************
% Set Path
%***********************************
% Input Folder Text
labelStr = 'Input Folder';
btnPos=[x(1)+xbuff y(3)-ycenter pw ph];
REMORA.batchLTSA_verify.inDirTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'BackgroundColor', bgColor,...
    'Visible','on');

% Input Folder Editable Text
labelStr=num2str(REMORA.batchLTSA.settings.inDir);
btnPos=[x(2)+xbuff y(3) w*3-xbuff*2 ph];
REMORA.batchLTSA_verify.inDirEdTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','batchLTSA_control(''setInDir'')');

% Input Folder Browse Button
labelStr = 'Browse';
btnPos = [x(5) y(3) pw ph];
REMORA.batchLTSA_verify.inDirBrowse = uicontrol(REMORA.fig.batchLTSA,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorGray,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','batchLTSA_control(''browseInDir'')');

% ***********************************
% Set File Type
% ***********************************
% File Type Text
labelStr = 'Data File Type';
btnPos=[x(1)+xbuff y(4)-ycenter pw ph];
REMORA.batchLTSA_verify.inDirTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'BackgroundColor', bgColor,...
    'Visible','on');

% Make radiobutton group
REMORA.fig.dataType_buttongroup = uibuttongroup('Visible','off',...
    'Position',[x(2)+xbuff y(4) w*4-xbuff*2 ph],...
    'SelectionChangedFcn','batchLTSA_control(''setDataType'')',...
    'Visible', 'on');

% set radio button options
labelStr = 'XWAV Data';
relBtnPos = [15 10 120 20];
REMORA.batchLTSA_verify.XWAVRadioButton = uicontrol(REMORA.fig.dataType_buttongroup,...
    'Style', 'radiobutton',...
    'Position',relBtnPos,...
    'String',labelStr,...
    'Value',true,...
    'Tag','XWAV',...
    'FontUnits','normalized', ...
    'Visible','on');

labelStr = 'WAV Data';
relBtnPos=[145 10 120 20];
REMORA.batchLTSA_verify.WAVRadioButton = uicontrol(REMORA.fig.dataType_buttongroup,...
    'Style','radiobutton',...
    'Position',relBtnPos,...
    'String',labelStr,...
    'Tag','WAV',...
    'FontUnits','normalized', ...
    'Visible','on');

labelStr = 'FLAC Data';
relBtnPos=[255 10 120 20];
REMORA.batchLTSA_verify.FLACRadioButton = uicontrol(REMORA.fig.dataType_buttongroup,...
    'Style','radiobutton',...
    'Position',relBtnPos,...
    'String',labelStr,...
    'Tag','FLAC',...
    'FontUnits','normalized', ...
    'Visible','on');

%***********************************
% Set LTSA Settings
%***********************************
labelStr = 'LTSA Settings';
btnPos=[x(1) y(5) w*5 ph];
REMORA.batchLTSA_verify.headtext = uicontrol(REMORA.fig.batchLTSA, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',12,...
    'Visible','on');

%***********************************
% Set Time Average
%***********************************
% tave text
labelStr = 'tave\n[time average]';
btnPos=[x(1)+xbuff y(6) pw ph];
REMORA.batchLTSA_verify.taveTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'BackgroundColor', bgColor,...
    'Visible','on');

% tave editable Text
labelStr=num2str(REMORA.batchLTSA.settings.tave);
btnPos=[x(2) y(6) pw ph];
REMORA.batchLTSA_verify.taveEdTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','batchLTSA_control(''settave'')');

%***********************************
% Set Frequency Settings
%***********************************
% dfreq Text
labelStr = 'dfreq\n[frequency average]';
btnPos=[x(4)-w/2 y(6) pw+w/2 ph];
REMORA.batchLTSA_verify.dfreqTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'BackgroundColor', bgColor,...
    'Visible','on');

% dfreq Editable Text
labelStr=num2str(REMORA.batchLTSA.settings.dfreq);
btnPos=[x(5)-w/4 y(6) pw ph];
REMORA.batchLTSA_verify.dfreqEdTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','batchLTSA_control(''setdfreq'')');

%***********************************
% Set Number of Channels to Process
%***********************************
% Number of channels 
labelStr = 'Number of\nchannels';
btnPos=[x(1)+xbuff y(7) pw ph];
REMORA.batchLTSA_verify.numChTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'BackgroundColor', bgColor,...
    'Visible','on');

% Make radiobutton group
REMORA.fig.numCh_buttongroup = uibuttongroup('Visible', 'off',...
    'Position',[x(2) y(7) pw*1.6 ph], ...
    'SelectionChangedFcn','batchLTSA_control(''setNumCh'')',...
    'Visible', 'on');

% set radio button options
labelStr = 'Single';
relBtnPos=[10 10 120 20];
REMORA.batchLTSA_verify.singleRadioButton = uicontrol(REMORA.fig.numCh_buttongroup,...
    'Style','radiobutton',...
    'Position',relBtnPos,...
    'String',labelStr,...
    'Value',true,...
    'Tag','single',...
    'FontUnits','normalized', ...
    'Visible','on');

labelStr = 'Multichannel';
relBtnPos=[65 10 120 20];
REMORA.batchLTSA_verify.multiRadioButton = uicontrol(REMORA.fig.numCh_buttongroup,...
    'Style','radiobutton',...
    'Position',relBtnPos,...
    'String',labelStr,...
    'Tag','multi',...
    'FontUnits','normalized', ...
    'Visible','on');

% if only one channel, which one?
% which channels text 
labelStr = 'Channel to process\nSet to 0 for all';
btnPos=[x(4)-w/2 y(7) pw+w/2 ph];
REMORA.batchLTSA_verify.whChTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'BackgroundColor', bgColor,...
    'Visible','on');

% whCh editable Text
labelStr=num2str(REMORA.batchLTSA.settings.whCh);
btnPos=[x(5)-w/4 y(7) pw ph];
REMORA.batchLTSA_verify.whChEdTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','batchLTSA_control(''setWhCh'')');

%***********************************
% Create LTSAs
%***********************************
labelStr = 'Batch Create LTSAs';
btnPos=[x(1)+1/2*w y(8)-h/2 w*4 h];
REMORA.batchLTSA_verify.BatchLTSAButton = uicontrol(REMORA.fig.batchLTSA,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',[.47,.67,.19],...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','batchLTSA_control(''RunBatchLTSA'')');


%***********************************
% Cancel Button
%***********************************
labelStr = 'Cancel';
btnPos = [x(5) y(9)-h/1.5 pw ph];
REMORA.batchLTSA_verify.CancelButton = uicontrol(REMORA.fig.batchLTSA,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorGray,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','batchLTSA_control(''cancelAll'')');







