function sh_init_motion_gui
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% sh_init_motion_gui.m
%
% Editable settings in motion GUI to run detector on window.
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
global REMORA HANDLES PARAMS

% button grid layouts
% 14 rows, 4 columns
r = 20; % rows      (extra space for separations btw sections)
c = 3;  % columns
h = 1/r;
w = 1/c;
dy = h * 1.2;
% dx = 0.008;
ybuff = h*.2;
xbuff = w*.1;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;

% colors
bgColor = [1 1 1];  % white
bgColorGrayLight = [.92 .92 .92];  % gray
bgColorGray = [.86 .86 .86];  % gray
bgColorBlue = [.75 .875 1]; % light blue for

% is an ltsa file open? (There are some callbacks that depend on this!)
if isfield(PARAMS, 'ltsa')
    f_enbl = get(HANDLES.ltsa.motion.fwd, 'Enable');
    b_enbl = get(HANDLES.ltsa.motion.back, 'Enable');
else
    f_enbl = 'off';
    b_enbl = 'off';
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

REMORA.sh_verify = [];
labelStr = 'Adjustable Detector Settings';
btnPos=[x(1) y(2) w*3 h];
REMORA.sh_verify.headtext = uicontrol(REMORA.fig.sh.motion, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');


% Set paths and strings
%***********************************

% Transfer Function Text
labelStr = 'Transfer Function Path';
btnPos=[x(1)+xbuff  y(3)-ybuff*2 w h];
REMORA.sh_verify.TFPathTxt = uicontrol(REMORA.fig.sh.motion,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Transfer Function Editable Text
labelStr=num2str(REMORA.sh.settings.tfFullFile);
btnPos=[x(2) y(3)-ybuff*2 w*2-xbuff h];
REMORA.sh_verify.TFPathEdTxt = uicontrol(REMORA.fig.sh.motion,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sh_control(''setTFPath'',''motion'')');

% col names
labelStr='Parameter';
btnPos=[x(1) y(5) w*2 h];
REMORA.sh_verify.headtext = uicontrol(REMORA.fig.sh.motion, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGrayLight,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');

labelStr='Min';
btnPos=[x(3)-xbuff y(5) w/2 h];
REMORA.sh_verify.headtext = uicontrol(REMORA.fig.sh.motion, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGrayLight,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');

labelStr='Max';
btnPos=[x(3)+w/2-xbuff y(5) w/2 h];
REMORA.sh_verify.headtext = uicontrol(REMORA.fig.sh.motion, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGrayLight,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');

%***********************************
% Low Band Limits Text
%***********************************

%  Low Band Limit Text
labelStr = 'Low Band Limit (Hz)';
btnPos=[x(1)+xbuff y(6)-ybuff w*2 h];
REMORA.sh_verify.LowBandText = uicontrol(REMORA.fig.sh.motion,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Minimum Low Band Limit Editable Text
labelStr=num2str(REMORA.sh.settings.lowBand(1,1));
btnPos=[x(3)-xbuff y(6) w/2 h];
REMORA.sh_verify.MinLowBandEdText = uicontrol(REMORA.fig.sh.motion,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sh_control(''setMinLowBand'',''motion'')');

% Maximum Low Band Limit Editable Text
labelStr=num2str(REMORA.sh.settings.lowBand(1,2));
btnPos=[x(3)+w/2-xbuff y(6) w/2 h];
REMORA.sh_verify.MaxLowBandEdText = uicontrol(REMORA.fig.sh.motion,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sh_control(''setMaxLowBand'',''motion'')');

%***********************************
% Medium Band Limits Text
%***********************************
labelStr = 'Medium Band Limit (Hz)';
btnPos=[x(1)+xbuff y(7)-ybuff w*2 h];
REMORA.sh_verify.MediumBandText = uicontrol(REMORA.fig.sh.motion,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr),...
    'FontUnits','normalized', ...
    'Visible','on');

% Minimum Medium Band Limit Editable Text
labelStr=num2str(REMORA.sh.settings.mediumBand(1,1));
btnPos=[x(3)-xbuff y(7) w/2 h];
REMORA.sh_verify.MinMediumBandEdText = uicontrol(REMORA.fig.sh.motion,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sh_control(''setMinMediumBand'',''motion'')');

% Maximum Medium Band Limit Editable Text
labelStr=num2str(REMORA.sh.settings.mediumBand(1,2));
btnPos=[x(3)+w/2-xbuff y(7) w/2 h];
REMORA.sh_verify.MaxMediumBandEdText = uicontrol(REMORA.fig.sh.motion,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sh_control(''setMaxMediumBand'',''motion'')');

%***********************************
% High Band Limits Text
%***********************************
labelStr = 'High Band Limit (Hz)';
btnPos=[x(1)+xbuff y(8)-ybuff w*2 h];
REMORA.sh_verify.MediumBandText = uicontrol(REMORA.fig.sh.motion,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr),...
    'FontUnits','normalized', ...
    'Visible','on');

% Minimum Duration Limit Editable Text
labelStr=num2str(REMORA.sh.settings.highBand(1,1));
btnPos=[x(3)-xbuff y(8) w/2 h];
REMORA.sh_verify.MinHighBandEdText = uicontrol(REMORA.fig.sh.motion,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sh_control(''setMinHighBand'',''motion'')');

% Maximum Duration Limit Editable Text
labelStr=num2str(REMORA.sh.settings.highBand(1,2));
btnPos=[x(3)+w/2-xbuff y(8) w/2 h];
REMORA.sh_verify.MaxHighBandEdText = uicontrol(REMORA.fig.sh.motion,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sh_control(''setMaxHighBand'',''motion'')');

%***********************************
% Duration Threshold Close Passage Text
%***********************************
labelStr = 'Close Passage Duration Threshold (s)';
btnPos=[x(1)+xbuff y(9)-ybuff w*2 h];
REMORA.sh_verify.ThrCloseTxt = uicontrol(REMORA.fig.sh.motion,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on');

% Minimum Duration Threshold Close Passage Editable Text
labelStr=num2str(REMORA.sh.settings.thrClose);
btnPos=[x(3)-xbuff y(9) w/2 h];
REMORA.sh_verify.ThrCloseEdTxt = uicontrol(REMORA.fig.sh.motion,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sh_control(''setThrClose'',''motion'')');

%***********************************
% Duration Threshold Distant Passage Text
%***********************************
labelStr = 'Distant Passage Duration Threshold (s)';
btnPos=[x(1)+xbuff y(10)-ybuff w*2 h];
REMORA.sh_verify.ThrDistantTxt = uicontrol(REMORA.fig.sh.motion,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on');

% Minimum Duration Threshold Distant Passage Editable Text
labelStr=num2str(REMORA.sh.settings.thrDistant);
btnPos=[x(3)-xbuff y(10) w/2 h];
REMORA.sh_verify.ThrDistantEdTxt = uicontrol(REMORA.fig.sh.motion,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sh_control(''setThrDistant'',''motion'')');

%***********************************
% Received Level Threshold Text
%***********************************
labelStr = 'Received Level Threshold (%)';
btnPos=[x(1)+xbuff y(11)-ybuff w*2 h];
REMORA.sh_verify.ThrRLTxt = uicontrol(REMORA.fig.sh.motion,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on');

% Minimum Duration Threshold Distant Passage Editable Text
labelStr=num2str(REMORA.sh.settings.thrRL);
btnPos=[x(3)-xbuff y(11) w/2 h];
REMORA.sh_verify.ThrRLEdTxt = uicontrol(REMORA.fig.sh.motion,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sh_control(''setThrRL'',''motion'')');

%***********************************
% Minimum Time Between Passages Threshold Text
%***********************************
labelStr = 'Time Between Passages (h)';
btnPos=[x(1)+xbuff y(12)-ybuff w*2 h];
REMORA.sh_verify.MinPassageTxt = uicontrol(REMORA.fig.sh.motion,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on');

% Minimum Duration Threshold Distant Passage Editable Text
labelStr=num2str(REMORA.sh.settings.minPassage);
btnPos=[x(3)-xbuff y(12) w/2 h];
REMORA.sh_verify.MinPassageEdTxt = uicontrol(REMORA.fig.sh.motion,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sh_control(''setMinPassage'',''motion'')');

%***********************************
% Buffer Time Detections Text
%***********************************
labelStr = 'Buffer Time (min)';
btnPos=[x(1)+xbuff y(13)-ybuff w*2 h];
REMORA.sh_verify.BufferTxt = uicontrol(REMORA.fig.sh.motion,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on');

% Minimum Duration Threshold Distant Passage Editable Text
labelStr=num2str(REMORA.sh.settings.buffer);
btnPos=[x(3)-xbuff y(13) w/2 h];
REMORA.sh_verify.BufferEdTxt = uicontrol(REMORA.fig.sh.motion,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sh_control(''setBuffer'',''motion'')');

%***********************************
% Duty Cycle Text
%***********************************
labelStr = 'Duty Cycle Data';
btnPos=[x(1)+xbuff y(14) w h];
REMORA.sh_verify.dutyCycleCheckbox = uicontrol(REMORA.fig.sh.motion,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'Value',REMORA.sh.settings.dutyCycle,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sh_control(''setDutyCycle'',''motion'')');

%***********************************
% Disk Write Noise Text
%***********************************
labelStr = 'Exclude Disk-Write Noise (HARP data only)';
btnPos=[x(1)+xbuff y(15) w*3 h];
REMORA.sh_verify.diskWriteCheckbox = uicontrol(REMORA.fig.sh.motion,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'Value',REMORA.sh.settings.diskWrite,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sh_control(''setDiskWrite'',''motion'')');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Window heading
labelStr = 'Window Settings:';
btnPos=[x(1)+xbuff y(17)-ybuff w*2 h];
REMORA.sh_verify.WindowHeading = uicontrol(REMORA.fig.sh.motion,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontWeight','bold',...
    'FontUnits','normalized', ...
    'Visible','on');

%***********************************
% Duration Window Text
%***********************************

labelStr = 'Window Size (h)';
btnPos=[x(1)+xbuff y(18) w*2 h];
REMORA.sh_verify.DurWindTxt = uicontrol(REMORA.fig.sh.motion,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on');
% Duration Window Editable Text
labelStr=num2str(REMORA.sh.settings.durWind);
btnPos=[x(2)-xbuff y(18) w/2 h];
REMORA.sh_verify.DurWindEdTxt = uicontrol(REMORA.fig.sh.motion,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sh_control(''setDurWind'',''motion'')');

%***********************************
% Slide Time Window Text
%***********************************

labelStr = 'Sliding Time (h)';
btnPos=[x(2)+w/2+xbuff y(18) w*2 h];
REMORA.sh_verify.SlideTxt = uicontrol(REMORA.fig.sh.motion,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on');
% Slide Editable Text
labelStr = num2str(REMORA.sh.settings.slide);
btnPos=[x(3)+w/3 y(18) w/2 h];
REMORA.sh_verify.SlideEdTxt = uicontrol(REMORA.fig.sh.motion,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sh_control(''setSlide'',''motion'')');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

w_third = (2*w)/3;
%*********************************
% The BACK button setup
%*********************************
labelStr = '<';
btnPos=[x(1) y(20) w 1.5*h];
REMORA.sh_verify.back = uicontrol(REMORA.fig.sh.motion,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorBlue,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Enable', b_enbl, ...
    'FontWeight','bold',...
    'Callback','sh_motion_control(''Back'')');

%*********************************
% The REFRESH button setup
%*********************************
labelStr = 'Refresh';
btnPos=[x(2) y(20) w 1.5*h];
REMORA.sh_verify.refresh = uicontrol(REMORA.fig.sh.motion,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorBlue,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Callback','sh_motion_control(''Refresh'')');

%*********************************
% The FORWARD button setup
%*********************************
labelStr = '>';
btnPos=[x(3) y(20) w 1.5*h];
REMORA.sh_verify.fwd = uicontrol(REMORA.fig.sh.motion,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorBlue,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Enable', f_enbl, ...
    'FontWeight','bold',...
    'Callback','sh_motion_control(''Forward'')');

