function sh_init_visLabel_gui
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% sh_init_visLabel_gui.m
%
% Detection Labels File GUI to visualize detections on window.
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
global REMORA HANDLES PARAMS

% button grid layouts
% 14 rows, 4 columns
r = 6; % rows      (extra space for separations btw sections)
c = 3;  % columns
h = 1/r;
w = 1/c;
dy = h * 1.2;
% dx = 0.008;
ybuff = h*.3;
xbuff = w*.1;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;

% colors
bgColor = [1 1 1];  % white
bgColorGrayLight = [.92 .92 .92];  % gray
bgColorGray = [.86 .86 .86];  % gray
bgColorBlue = [.75 .875 1]; % light blue for

% is an ltsa file open? (There are some callbacks that depend on this!)
if isfield(PARAMS, 'ltsa')
    f_enbl = get(HANDLES.ltsa.motion.fwd, 'Enable');
    b_enbl = get(HANDLES.ltsa.motion.back, 'Enable');
else
    f_enbl = 'off';
    b_enbl = 'off';
end


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Set paths and strings
%***********************************

%*********************************
% Detection label file 1
%*********************************

REMORA.sh_motionLabel = [];
labelStr = 'Detection label file:';
btnPos=[x(1)+xbuff y(2)-ybuff*2 w*3 h];
REMORA.sh_motionLabel.headtext = uicontrol(REMORA.fig.sh.visLabel, ...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontWeight','bold',...
    'FontUnits','normalized', ...
    'BackgroundColor',bgColorBlue,...
    'Visible','on');

labelStr = 'Load labels';
btnPos=[x(2)+xbuff*5 y(2)-ybuff w*1.1 h];
REMORA.sh_motionLabel.tlab1 = uicontrol(REMORA.fig.sh.visLabel,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'Callback','sh_control_visLabel(''Load'',''File1'')');

labelStr = 'Display';
btnPos = [x(1)+xbuff y(3)-ybuff/2.3 w*2.8 h*.7];
REMORA.sh_motionLabel.tlab1CheckBox = uicontrol(REMORA.fig.sh.visLabel,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'off', ...
    'BackgroundColor',bgColorBlue,...
    'FontUnits','normalized', ...
    'Callback','sh_control_visLabel(''Display'',''File1'')');

%*********************************
% Detection label file 2
%*********************************

labelStr = 'Compare (optional):';
btnPos = [x(1)+xbuff y(4)-ybuff*3 w*3 h];
REMORA.sh_motionLabel.comparetext = uicontrol(REMORA.fig.sh.visLabel, ...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontWeight','bold',...
    'FontUnits','normalized', ...
    'BackgroundColor',bgColorBlue,...
    'Visible','on');

labelStr = 'Load other labels';
btnPos = [x(2)+xbuff*5 y(4)-ybuff*2 w*1.1 h];
REMORA.sh_motionLabel.tlab2 = uicontrol(REMORA.fig.sh.visLabel,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'Callback','sh_control_visLabel(''Load'',''File2'')');

labelStr = 'Display';
btnPos = [x(1)+xbuff y(5)-ybuff*1.3 w*2.8 h*.7];
REMORA.sh_motionLabel.tlab2CheckBox = uicontrol(REMORA.fig.sh.visLabel,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'off', ...
    'BackgroundColor',bgColorBlue,...
    'FontUnits','normalized', ...
    'Callback','sh_control_visLabel(''Display'',''File2'')');

%*********************************
% The BACK button setup
%*********************************

labelStr = '<';
btnPos = [x(1) y(7) w*1.5 dy];
REMORA.sh_motionLabel.back = uicontrol(REMORA.fig.sh.visLabel,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorBlue,...
    'String',labelStr ,...
    'FontUnits','normalized', ...
    'Enable', b_enbl, ...
    'FontWeight','bold',...
    'Callback','sh_control_visLabel(''Back'')');

%*********************************
% The FORWARD button setup
%*********************************
labelStr = '>';
btnPos = [x(2)+w/2 y(7) w*1.5 dy];
REMORA.sh_motionLabel.fwd = uicontrol(REMORA.fig.sh.visLabel,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorBlue,...
    'String',labelStr ,...
    'FontUnits','normalized', ...
    'Enable', f_enbl, ...
    'FontWeight','bold',...
    'Callback','sh_control_visLabel(''Forward'')');

