function pi_init_batch_gui
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% sh_init_batch_gui.m
%
% Verify settings in GUI before running on entire drive.
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
global REMORA

% button grid layouts
% 14 rows, 4 columns
r = 12; % rows      (extra space for separations btw sections)
c = 5;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
xbuff = w*.1;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;

% colors
bgColor = [1 1 1];  % white
bgColorGrayLight = [.92 .92 .92];  % gray
bgColorGray = [.86 .86 .86];  % gray

REMORA.bm_verify = [];
labelStr = 'Verify Detector Options';
btnPos=[x(1) y(2) w*5 h];
REMORA.pi_verify.headtext = uicontrol(REMORA.fig.pi.batch, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');


% Set paths and strings
%***********************************

% Input Folder Text
labelStr = 'Input Folder';
btnPos=[x(1)+xbuff  y(3) w dy];
REMORA.pi_verify.inDirTxt = uicontrol(REMORA.fig.pi.batch,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Input Folder Editable Text
labelStr=num2str(REMORA.pi.settings.baseDir);
btnPos=[x(3)-w/4 y(3) w*3 dy];
REMORA.pi_verify.inDirEdTxt = uicontrol(REMORA.fig.pi.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','pi_control(''setInDir'')');

% Output Folder Text
labelStr = 'Output Folder';
btnPos=[x(1)+xbuff  y(4) w dy];
REMORA.pi_verify.outDirTxt = uicontrol(REMORA.fig.pi.batch,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Output Folder Editable Text
labelStr=num2str(REMORA.pi.settings.outDir);
btnPos=[x(3)-w/4 y(4) w*3 dy];
REMORA.pi_verify.outDirEdTxt = uicontrol(REMORA.fig.pi.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','pi_control(''setOutDir'')');

% Template file Text
labelStr = 'Template file name';
btnPos=[x(1)+xbuff  y(5) w dy];
REMORA.pi_verify.tempTxt = uicontrol(REMORA.fig.pi.batch,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Template file Editable Text
labelStr=num2str(REMORA.pi.settings.templateFile);
btnPos=[x(3)-w/4 y(5) w*3 dy];
REMORA.pi_verify.tempEdTxt = uicontrol(REMORA.fig.pi.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','pi_control(''setTemplate'')');
%%
% Detector settings
labelStr = 'Adjustable Detector Settings';
btnPos=[x(1) y(6)-ybuff w*5 h];
REMORA.pi_verify.headtext = uicontrol(REMORA.fig.pi.batch, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');


% col names
labelStr='Parameter';
btnPos=[x(1) y(7) w*2 dy];
REMORA.pi_verify.headtext = uicontrol(REMORA.fig.pi.batch, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGrayLight,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');

labelStr='Value';
btnPos=[x(3)-w/2 y(7) w*3.5 dy];
REMORA.pi_verify.headtext = uicontrol(REMORA.fig.pi.batch, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGrayLight,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');


%***********************************
% Parameter Text
%***********************************

%  Bandpass Text
labelStr = 'Bandpass limits';
btnPos=[x(1)+xbuff*2 y(8)-ybuff w*2 dy];
REMORA.pi_verify.FreqbpText = uicontrol(REMORA.fig.pi.batch,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Lower bandpass Editable Text
labelStr=num2str(REMORA.pi.settings.Fc1);
btnPos=[x(4)-w/2 y(8) w/2 dy];
REMORA.pi_verify.Fc1EdText = uicontrol(REMORA.fig.pi.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','pi_control(''setFc1'')');

% Upper bandpass Editable Text
labelStr=num2str(REMORA.pi.settings.Fc2);
btnPos=[x(4) y(8) w/2 dy];
REMORA.pi_verify.Fc2EdText = uicontrol(REMORA.fig.pi.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','pi_control(''setFc2'')');

%  Threshold Text
labelStr = 'Threshold offset';
btnPos=[x(1)+xbuff*2 y(9)-ybuff w*2 dy];
REMORA.pi_verify.ThreshText = uicontrol(REMORA.fig.pi.batch,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Threshold Editable Text
labelStr=num2str(REMORA.pi.settings.c2_offset);
btnPos=[x(4)-w/2 y(9) w dy];
REMORA.pi_verify.ThreshEdText = uicontrol(REMORA.fig.pi.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','pi_control(''setThresh'')');

% Diff_s text
 labelStr= 'Time between calls';
 btnPos =[x(1)+xbuff*2 y(10)-ybuff*2 w*2 h];
 REMORA.pi_verify.diffsText = uicontrol(REMORA.fig.pi.batch,...
      'Style','text',...
      'Units','normalized',...
     'HorizontalAlignment','left',...
     'Position',btnPos,...
     'String',sprintf(labelStr,'Interpreter','tex'),...
     'FontUnits','normalized',...
     'Visible','on');


%Diff_s editable text
labelStr=num2str(REMORA.pi.settings.diff_s);
btnPos=[x(4)-w/2 y(10) w dy];
REMORA.pi_verify.diffsEdText = uicontrol(REMORA.fig.pi.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','pi_control(''setDiffS'')');

% RmsASmin text
 labelStr= 'Minimum SNR';
 btnPos =[x(1)+xbuff*2 y(11)-ybuff*2 w*2 h];
 REMORA.pi_verify.rmsASminText = uicontrol(REMORA.fig.pi.batch,...
      'Style','text',...
      'Units','normalized',...
     'HorizontalAlignment','left',...
     'Position',btnPos,...
     'String',sprintf(labelStr,'Interpreter','tex'),...
     'FontUnits','normalized',...
     'Visible','on');


%Diff_s editable text
labelStr=num2str(REMORA.pi.settings.rmsASmin);
btnPos=[x(4)-w/2 y(11) w dy];
REMORA.pi_verify.rmsASminEdText = uicontrol(REMORA.fig.pi.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','pi_control(''setRmsASmin'')');

% Run button
labelStr = 'Run Detector';
btnPos=[x(2)+1/2*w y(12) w*2 h];
REMORA.pi_verify.RunDetectorEdTxt = uicontrol(REMORA.fig.pi.batch,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',[.47,.67,.19],...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','pi_control(''RunBatchDetection'')');



