function pi_init_batch_figure

global REMORA

defaultPos = [0.25,0.25,0.3,0.3];
REMORA.fig.pi.batch = figure( ...
    'NumberTitle','off', ...
    'Name','Fish Detector - v1.0',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on');

% Detection Settings pulldown
REMORA.pi.menuBatch = uimenu(REMORA.fig.pi.batch,'Label','&Load Settings',...
    'Enable','on','Visible','on');

% Spectrogram load/save params
uimenu(REMORA.pi.menuBatch,'Label','&Select Detector Settings File',...
    'Callback','pi_gui_pulldown(''settingsLoadBatch'')');
