function sm_ltsa_params_window

global REMORA

defaultPos = [0.25,0.35,0.38,0.4];
if isfield(REMORA.fig, 'sm')
    % Check if the figure already exists. If so, don't move it.
    if isfield(REMORA.fig.sm, 'ltsa') && isvalid(REMORA.fig.sm.ltsa)
        defaultPos = get(REMORA.fig.sm.ltsa,'Position');
    else
        REMORA.fig.sm.ltsa = figure;
    end
else 
    REMORA.fig.sm.ltsa = figure;
end

clf

set(REMORA.fig.sm.ltsa,'NumberTitle','off', ...
    'Name','Make Soundscape LTSA - v1.0',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on',...
    'ToolBar', 'none');

figure(REMORA.fig.sm.ltsa)

% Load/save settings pulldown:

if ~isfield(REMORA.fig.sm,'SMfileMenu') || ~isvalid(REMORA.fig.sm.SMfileMenu)
    REMORA.fig.sm.SMfileMenu = uimenu(REMORA.fig.sm.ltsa,'Label',...
        'Save/Load Settings','Enable','on','Visible','on');
    
    % LTSA load/save params:
    uimenu(REMORA.fig.sm.SMfileMenu,'Label','&Load Settings',...
        'Callback','sm_ltsa_control(''sm_ltsa_settingsLoad'')');
    uimenu(REMORA.fig.sm.SMfileMenu,'Label','&Save Settings',...
        'Callback','sm_ltsa_control(''sm_ltsa_settingsSave'')');
end

% Button grid layouts
% 12 rows, 2 columns
r = 13; % Rows (Extra space for separations between sections)
c = 2;  % Columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
% Y Position (Rrelative Units)
y = 1:-h:0;

% X Position (Relative Units)
x = 0:w:1;

% Colors
bgColor = [1 1 1];  % White
bgColorRed = [1 .6 .6];  % Red
% bgColorGray = [.86 .86 .86];  % Gray
bgColor3 = [.75 .875 1]; % Light Green 
bgColor4 = [.76 .87 .78]; % Light Blue 

REMORA.sm.verify = [];

REMORA.sm.params_help = sm_ltsa_get_help_strings;

%% Title:

labelStr = 'Soundscape LTSA Settings';
btnPos=[x(1) y(2) 2*w h];
REMORA.sm.ltsa.headtext = uicontrol(REMORA.fig.sm.ltsa, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',12,...
    'Visible','on');
%% Set paths and strings
%***********************************
% Input Directory Text
labelStr = 'Input Directory';
btnPos=[x(1) y(3)-ybuff w/2 h];
REMORA.sm.verify.indirTxt = uicontrol(REMORA.fig.sm.ltsa,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.sm.params_help.indirHelp));
%  'BackgroundColor',bgColor3,...

% Input Directory Editable Text
labelStr=num2str(REMORA.sm.ltsa.indir);
btnPos=[x(1)+w/2 y(3) w h];
REMORA.sm.verify.indir = uicontrol(REMORA.fig.sm.ltsa,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','sm_ltsa_control(''setindir'')');

% Change Input Directory Button
labelStr = 'Select';
btnPos=[x(1)+w*1.6 y(3) w/4 h];

REMORA.sm.verify.indirSel = uicontrol(REMORA.fig.sm.ltsa,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor3,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.4,...
    'Visible','on',...
    'FontWeight','normal',...
    'Callback','sm_ltsa_control(''indirSel'')');

%% Output Directory Text
labelStr = 'Output Directory';
btnPos=[x(1) y(4)-ybuff w/2 h];
REMORA.sm.verify.outdirTxt = uicontrol(REMORA.fig.sm.ltsa,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.sm.params_help.outdirHelp));%   'BackgroundColor',bgColor3,...

% Output Folder Editable Text
labelStr=num2str(REMORA.sm.ltsa.outdir);
btnPos=[x(1)+w/2 y(4) w h];
REMORA.sm.verify.outdir = uicontrol(REMORA.fig.sm.ltsa,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sm_ltsa_control(''setoutdir'')');

% Change Output Directory Button
labelStr = 'Select';
btnPos=[x(1)+w*1.6 y(4) w/4 h];

REMORA.sm.verify.outdirSel = uicontrol(REMORA.fig.sm.ltsa,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor3,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.4,...
    'Visible','on',...
    'FontWeight','normal',...
    'Callback','sm_ltsa_control(''outdirSel'')');

%% Output Filename Text
labelStr = 'Output Filename';
btnPos=[x(1) y(5)-ybuff w/2 h];
REMORA.sm.verify.outfnameTxt = uicontrol(REMORA.fig.sm.ltsa,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.sm.params_help.outfnameHelp));%   'BackgroundColor',bgColor3,...

% Output Filename Editable Text
labelStr=num2str(REMORA.sm.ltsa.outfname);
btnPos=[x(1)+w/2 y(5) w h];
REMORA.sm.verify.outfname = uicontrol(REMORA.fig.sm.ltsa,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sm_ltsa_control(''setoutfname'')');

%% LTSA Parameters Header
labelStr = 'LTSA Parameters';
btnPos=[x(1) y(6) 2*w h-ybuff];
REMORA.sm.verify.ltsaParamTxt = uicontrol(REMORA.fig.sm.ltsa, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorRed,...
    'String',labelStr, ...
    'FontWeight','bold',...    
    'FontSize',11,...
    'FontUnits','points',...
    'Visible','on');

%% Left column in LTSA Parameters

% Averaging Time Text
labelStr = 'Averaging Time [s]';
btnPos=[x(1) y(8)-ybuff w/2 h];
REMORA.sm.verify.taveTxt = uicontrol(REMORA.fig.sm.ltsa,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.sm.params_help.taveHelp));

% Averaging Time Editable Text
labelStr=num2str(REMORA.sm.ltsa.tave);
btnPos=[x(1)+w/2 y(8) w/4 h];
REMORA.sm.verify.tave = uicontrol(REMORA.fig.sm.ltsa,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sm_ltsa_control(''settave'')');

%% Frequency Bin Size Text
labelStr = 'Frequency bin size [Hz]';
btnPos=[x(1) y(9)-ybuff w/2 h];
REMORA.sm.verify.dfreqTxt = uicontrol(REMORA.fig.sm.ltsa,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.sm.params_help.dfreqHelp));

% Frequency Bin Size Editable Text
labelStr=num2str(REMORA.sm.ltsa.dfreq);
btnPos=[x(1)+w/2 y(9) w/4 h];
REMORA.sm.verify.dfreq = uicontrol(REMORA.fig.sm.ltsa,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sm_ltsa_control(''setdfreq'')');

%% Length of LTSA Text
labelStr = 'Length of LTSA [days]';
btnPos=[x(1) y(10)-ybuff w/2 h];
REMORA.sm.verify.ndaysTxt = uicontrol(REMORA.fig.sm.ltsa,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.sm.params_help.ndaysHelp));

% Length of LTSA Editable Text
labelStr=num2str(REMORA.sm.ltsa.ndays);
btnPos=[x(1)+w/2 y(10) w/4 h];
REMORA.sm.verify.ndays = uicontrol(REMORA.fig.sm.ltsa,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sm_ltsa_control(''setndays'')');

%% Number of LTSA to start
labelStr = 'Start with LTSA #';
btnPos=[x(1) y(11)-ybuff w/2 h];
REMORA.sm.verify.nstartTxt = uicontrol(REMORA.fig.sm.ltsa,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.sm.params_help.nstartHelp));

% Number of LTSA to start Editable Text
labelStr=num2str(REMORA.sm.ltsa.nstart);
btnPos=[x(1)+w/2 y(11) w/4 h];
REMORA.sm.verify.nstart = uicontrol(REMORA.fig.sm.ltsa,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sm_ltsa_control(''setnstart'')');

%% Right Column LTSA Parameters
% File Type Text
labelStr = 'File type: 1=WAV, 2=XWAV';
btnPos=[x(2) y(8)-ybuff w/2 h];
REMORA.sm.verify.ftypeTxt = uicontrol(REMORA.fig.sm.ltsa,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.sm.params_help.ftypeHelp));

% File Type Editable Text
labelStr=num2str(REMORA.sm.ltsa.ftype);
btnPos=[x(2)+w/2 y(8) w/4 h];
REMORA.sm.verify.ftype = uicontrol(REMORA.fig.sm.ltsa,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sm_ltsa_control(''setftype'')');

%% Data Type Text
labelStr = 'Data Type: 1=HARP, 5=SoundTrap';
btnPos=[x(2) y(9)-ybuff w/2 h];
REMORA.sm.verify.dtypeTxt = uicontrol(REMORA.fig.sm.ltsa,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.sm.params_help.dtypeHelp));

% Data Type Editable Text
labelStr=num2str(REMORA.sm.ltsa.dtype);
btnPos=[x(2)+w/2 y(9) w/4 h];
REMORA.sm.verify.dtype = uicontrol(REMORA.fig.sm.ltsa,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sm_ltsa_control(''setdtype'')');

%% Data Channel Text
labelStr = 'Data Channel Number';
btnPos=[x(2) y(10)-ybuff w/2 h];
REMORA.sm.verify.ch = uicontrol(REMORA.fig.sm.ltsa,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on',...
   'TooltipString',sprintf(REMORA.sm.params_help.chHelp));

% Data Channel Editable Text
labelStr=num2str(REMORA.sm.ltsa.ch);
btnPos=[x(2)+w/2 y(10) w/4 h];
REMORA.sm.verify.ch = uicontrol(REMORA.fig.sm.ltsa,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sm_ltsa_control(''setch'')');



%% Run Button
labelStr = 'Run Soundscape LTSA';
btnPos=[x(2)-w/2 y(13) w h];

REMORA.sm.verify.runTxt = uicontrol(REMORA.fig.sm.ltsa,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor3,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','sm_ltsa_control(''runltsa'')');
1;
