function [myNetwork, trainPrefs] = nn_build_network

global REMORA
% should check that train and test data have same dimensions.

dataSize = ;%figure out dims of training data.
numClasses = ;%figure out unique labels.
layerSet = imageInputLayer(dataSize);

for iD = 1:REMORA.nn.train_net.nHiddenLayers
    layerSet = [layerSet;...
    fullyConnectedLayer(numClasses);...
    reluLayer;...
    dropoutLayer(REMORA.nn.train_net.droupout)];

end

options = trainingOptions(...
    'MaxEpochs',100, ...
    'MiniBatchSize',miniBatchSize, ...
    'Shuffle','every-epoch', ...
    'Plots','training-progress');

layerSet = [layerSet;...
	fullyConnectedLayer(numClasses);...
	softmaxLayer;...
	classificationLayer];
