function lt_init_lVis_window

global REMORA


defaultPos = [0.1,0.1,0.3,0.25];



if isfield(REMORA.fig, 'lt')
    % check if the figure already exists. If so, don't move it.
    if isfield(REMORA.fig.lt, 'lVis_settings') && isvalid(REMORA.fig.lt.lVis_settings)
        defaultPos = get(REMORA.fig.lt.lVis_settings,'Position');
    else
        REMORA.fig.lt.lVis_settings = figure;
    end
else
    REMORA.fig.lt.lVis_settings = figure;
end

set(REMORA.fig.lt.lVis_settings,'NumberTitle','off', ...
    'Name','Visualize Labels',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on',...
    'ToolBar', 'none');

figure(REMORA.fig.lt.lVis_settings)




%%%%button grid
row = 7;
col = 3;
h = 1/row;
w = 1/col;
x = 0:w:1;
y = 1:-h:0;
xbuff = w*0.25;

%%%colors
bgColor = [1 1 1];
bgColorPurple = [0.8 0.6 0.6];

REMORA.lt.lVis_verify = [];

%% title content 
btnPos = [x(1) y(2) w h];
labelStr = 'Load labels to visualize';
REMORA.lt.lVis_verify.headtext = uicontrol(REMORA.fig.lt.lVis_settings, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');  %'BackgroundColor',bgColor3,...


% %%%work with LTSA
% if isfield(PARAMS, 'ltsa')
%     f_enbl = get(HANDLES.ltsa.motion.fwd, 'Enable');
%     b_enbl = get(HANDLES.ltsa.motion.back, 'Enable');
% else
%     f_enbl = 'off';
%     b_enbl = 'off';
% end

%% label loading functionality
labelStr = 'Load Labels 1';
btnPos=[x(1) y(3) w h];
REMORA.lt.lVis_verify.load1 = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'BackgroundColor',bgColorPurple,...
    'Callback','lt_lVis_control(''LoadLabels'',''labels1'')');

labelStr = 'Load Labels 2';
btnPos=[x(1) y(4) w h];
REMORA.lt.lVis_verify.load2 = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'BackgroundColor',bgColorPurple,...
    'Callback','lt_lVis_control(''LoadLabels'',''labels2'')');

labelStr = 'Load Labels 3';
btnPos=[x(1) y(5) w h];
REMORA.lt.lVis_verify.load3 = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'BackgroundColor',bgColorPurple,...
    'Callback','lt_lVis_control(''LoadLabels'',''labels3'')');

labelStr = 'Load Labels 4';
btnPos=[x(1) y(6) w h];
REMORA.lt.lVis_verify.load4 = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'BackgroundColor',bgColorPurple,...
    'Callback','lt_lVis_control(''LoadLabels'',''labels4'')');


%% display label buttons
labelStr = 'Display 1';
btnPos = [x(2)+xbuff y(3) w*1.3 h];
REMORA.lt.lVis_labels.label1Check = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'off', ...
    'FontUnits','normalized', ...
    'Callback','lt_lVis_control(''Display'',''labels1'')');

labelStr = 'Display 2';
btnPos = [x(2)+xbuff y(4) w*1.3 h];
REMORA.lt.lVis_labels.label2Check = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'off', ...
    'FontUnits','normalized', ...
    'Callback','lt_lVis_control(''Display'',''labels2'')');

labelStr = 'Display 3';
btnPos = [x(2)+xbuff y(5) w*1.3 h];
REMORA.lt.lVis_labels.label3Check = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'off', ...
    'FontUnits','normalized', ...
    'Callback','lt_lVis_control(''Display'',''labels3'')');

labelStr = 'Display 4';
btnPos = [x(2)+xbuff y(6) w*1.3 h];
REMORA.lt.lVis_labels.label4Check = uicontrol(REMORA.fig.lt.lVis_settings,...
    'Style','checkbox',...
    'Units','normalized',...
    'String',labelStr,...
    'Position',btnPos,...
    'Value',0,...
    'Enable', 'off', ...
    'FontUnits','normalized', ...
    'Callback','lt_lVis_control(''Display'',''labels4'')');

