function ct_cc_saveID_gui

global REMORA
% Make another gui
initAxes = 0;
default_pos = [0.75,.05,.2,.15];
if isfield(REMORA.fig, 'ct')
    % check if the figure already exists. If so, don't move it.
    if isfield(REMORA.fig.ct, 'cc_saveID') && isvalid(REMORA.fig.ct.cc_saveID)
        defaultPos = get(REMORA.fig.ct.cc_saveID,'Position');
    else
        initAxes = 1;
    end
else
    initAxes = 1;
end

if initAxes
    REMORA.fig.ct.cc_saveID = figure;
    
    set(REMORA.fig.ct.cc_saveID,...
        'Units','normalized',...
        'ToolBar', 'none',...
        'MenuBar','none',...
        'NumberTitle','off','Name',...
        'Composite Clustering Tool - v1.0',...
        'Position',default_pos,...
        'Visible','on');    %
end

clf


REMORA.ct.CC.saveID = [];
labelStr = 'ID File Saving Options';
btnPos=[0.1 .7 1 .2];
REMORA.ct.CC.saveID.headtext = uicontrol(REMORA.fig.ct.cc_saveID, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',12,...
    'Visible','on');  %'BackgroundColor',bgColor3,...


%% Output Folder Text
labelStr = 'Output Folder';
btnPos=[.02 .6 .3 .15];
REMORA.ct.CC.saveID.outDirTxt = uicontrol(REMORA.fig.ct.cc_saveID,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','left',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Select output directory
if ~isfield(REMORA.ct.CC.output,'idDir') && isfield(REMORA.ct.CC.output, 'inDir')
    % To start, assume output folder = cluster_bins folder 
    REMORA.ct.CC.output.idDir =  REMORA.ct.CC_params.inDir;
elseif ~isfield(REMORA.ct.CC.output,'idDir') && ~isfield(REMORA.ct.CC.output,'idDir')
    REMORA.ct.CC.output.idDir = 'C:\';
end

% Output Folder Editable Text
btnPos=[.3 .65 .55 .15];
REMORA.ct.CC.saveID.outDirEdTxt = uicontrol(REMORA.fig.ct.cc_saveID,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'String',REMORA.ct.CC.output.idDir,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@ct_cc_saveID_control,'setOutDir'});


%% File ending
labelStr = 'Output File Ending';
btnPos=[.02 .3 .3 .15];
RREMORA.ct.CC.saveID.fEndTxt = uicontrol(REMORA.fig.ct.cc_saveID,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

if isfield(REMORA.ct.CC.output, 'fileEnding')
    fileEnding = REMORA.ct.CC.output.fileEnding;% should use input TPWS if exists
else
    fileEnding = 'ID1.mat';
    REMORA.ct.CC.output.fileEnding = fileEnding;
end

btnPos=[.3 .35 .55 .15];
REMORA.ct.CC.saveID.fEndEdTxt = uicontrol(REMORA.fig.ct.cc_saveID,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'String',fileEnding,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@ct_cc_saveID_control,'setFileEnding'});

% put a "save" button
labelStr = 'Save';
btnPos=[.4, 0.1, .2, .15];

REMORA.ct.CC.saveID.saveBtn = uicontrol(REMORA.fig.ct.cc_saveID,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','green',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback',@ct_cc_clusters_to_zID);

% bring to top
figure(REMORA.fig.ct.cc_saveID)

end


function ct_cc_close_ID_gui(hObject,eventdata)
global REMORA

close(REMORA.fig.ct.cc_saveID)
end


function ct_cc_saveID_control(hObject,eventdata,myEvent)

global REMORA

if strcmp(myEvent, 'setOutDir')
    REMORA.ct.CC.output.idDir = get(REMORA.ct.CC.saveID.outDirEdTxt,'String');
elseif strcmp(myEvent, 'setFileEnding')
    REMORA.ct.CC.output.fileEnding = get(REMORA.ct.CC.saveID.fEndEdTxt,'String');
end

end
