function d = ct_cb_status_dialog(dispMessage)

d = figure(98);clf

set(d,'Name','ClusterTool Status',...
       'MenuBar','none','Toolbar','none',...
       'NumberTitle','off',...
      'Units','normalized','Visible','on');
set(d,'Position',[.45,.45,.2,.1])
txt = uicontrol('Parent',d,...
       'Style','text',...
       'Units','normalized',...  
       'Position',[0.1 0.410 0.8 0.5],...
       'FontSize',11,...  
       'String',sprintf(dispMessage)); 
       
drawnow
figure(d)
1;
   
