function ct_cc_save_indiv_clust_gui(hObject,eventdata)


global REMORA
% Make another gui
initAxes = 0;
default_pos = [0.75,.05,.2,.15];
if isfield(REMORA.fig, 'ct')
    % check if the figure already exists. If so, don't move it.
    if isfield(REMORA.fig.ct, 'cc_saveClust') && isvalid(REMORA.fig.ct.cc_saveClust)
        defaultPos = get(REMORA.fig.ct.cc_saveClust,'Position');
    else
        initAxes = 1;
    end
else
    initAxes = 1;
end

if initAxes
    REMORA.fig.ct.cc_saveClust = figure;
    
    set(REMORA.fig.ct.cc_saveClust,...
        'Units','normalized',...
        'ToolBar', 'none',...
        'MenuBar','none',...
        'NumberTitle','off','Name',...
        'Save Cluster Training Files',...
        'Position',default_pos,...
        'Visible','on');    %
end

clf(REMORA.fig.ct.cc_saveClust)


REMORA.ct.CC.saveClust = [];
labelStr = 'Cluster File Saving Options';
btnPos=[0 .8 1 .2];
REMORA.ct.CC.saveClust.headtext = uicontrol(REMORA.fig.ct.cc_saveClust, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');  %'BackgroundColor',bgColor3,...


%% Output Folder Text
labelStr = 'Output Folder';
btnPos=[.02 .6 .3 .15];
REMORA.ct.CC.saveClust.outDirTxt = uicontrol(REMORA.fig.ct.cc_saveClust,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','left',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Select output directory
if ~isfield(REMORA.ct.CC.output,'clustDir') && isfield(REMORA.ct.CC.output, 'inDir')
    % To start, assume output folder = cluster_bins folder 
    REMORA.ct.CC.output.clustDir =  REMORA.ct.CC_params.inDir;
elseif ~isfield(REMORA.ct.CC.output,'clustDir') && ~isfield(REMORA.ct.CC.output,'inDir')
    REMORA.ct.CC.output.clustDir = 'C:\';
end

% Output Folder Editable Text
btnPos=[.25 .65 .70 .12];
REMORA.ct.CC.saveClust.outDirEdTxt = uicontrol(REMORA.fig.ct.cc_saveClust,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'String',REMORA.ct.CC.output.clustDir,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@ct_cc_saveClust_control,'setOutDir'});


% bin level output checkbox
REMORA.ct.CC.output.saveBinLevelDataTF = 1;
labelStr = 'Save bin-level output';
btnPos=[.02 .50 .6 .15];
REMORA.ct.CC.saveClust.saveBinLevelDataCheck = uicontrol(REMORA.fig.ct.cc_saveClust,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','left',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Value',REMORA.ct.CC.output.saveBinLevelDataTF,...
    'Callback',{@ct_cc_saveClust_control,'bin'},...
    'Visible','on');


% click level output checkbox
labelStr = 'Save detection-level output';
REMORA.ct.CC.output.saveDetLevelDataTF = 1;
btnPos = [.02 .35 .6 .15];
REMORA.ct.CC.saveClust.saveDetLevelDataCheck = uicontrol(REMORA.fig.ct.cc_saveClust,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','left',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Value',REMORA.ct.CC.output.saveDetLevelDataTF ,...
    'Callback',{@ct_cc_saveClust_control,'det'},...
    'Visible','on');

if ~isfield(REMORA.ct.CC.output,'TPWSDir')
    REMORA.ct.CC.output.TPWSDir = [];
end

labelStr = 'TPWS Folder';
btnPos=[.02 .18 .3 .15];
REMORA.ct.CC.saveClust.TPWSDirTxt = uicontrol(REMORA.fig.ct.cc_saveClust,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','left',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Output Folder Editable Text
btnPos=[.25 .23 .70 .12];
REMORA.ct.CC.saveClust.TPWSDirEdTxt = uicontrol(REMORA.fig.ct.cc_saveClust,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'String',REMORA.ct.CC.output.TPWSDir,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@ct_cc_saveClust_control,'setTPWSDir'});


% put a "save" button
labelStr = 'Save';
btnPos=[.4, 0.05, .2, .15];

REMORA.ct.CC.saveClust.saveBtn = uicontrol(REMORA.fig.ct.cc_saveClust,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','green',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback',@ct_cc_save_cluster_files);


btnPos=[.85, 0.05, .1, .15];
REMORA.ct.CC.saveClust.infoBtn = uicontrol(REMORA.fig.ct.cc_saveClust,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','cyan',...
    'FontUnits','normalized', ...
    'FontName','Times',...
    'FontSize',.5,...
    'String','i',...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback',{@ct_cc_saveClust_control,'help'});

% bring to top
figure(REMORA.fig.ct.cc_saveClust)

end


function ct_cc_saveClust_control(hObject,eventdata,myEvent)

global REMORA

if strcmp(myEvent, 'setOutDir')
    REMORA.ct.CC.output.clustDir = get(REMORA.ct.CC.saveClust.outDirEdTxt,'String');

elseif strcmp(myEvent, 'bin')
    REMORA.ct.CC.output.saveBinLevelDataTF = get(REMORA.ct.CC.saveClust.saveBinLevelDataCheck,'Value');

elseif strcmp(myEvent, 'det')
    REMORA.ct.CC.output.saveDetLevelDataTF = get(REMORA.ct.CC.saveClust.saveDetLevelDataCheck,'Value');
    if ~REMORA.ct.CC.output.saveDetLevelDataTF 
        set(REMORA.ct.CC.saveClust.TPWSDirEdTxt,'visible','off')
        set(REMORA.ct.CC.saveClust.TPWSDirTxt,'visible','off')
    else
        set(REMORA.ct.CC.saveClust.TPWSDirEdTxt,'visible','on')
        set(REMORA.ct.CC.saveClust.TPWSDirTxt,'visible','on')
    end
    
elseif strcmp(myEvent, 'setTPWSDir')
    REMORA.ct.CC.output.TPWSDir = get(REMORA.ct.CC.saveClust.TPWSDirEdTxt,'String');
   
elseif strcmp(myEvent, 'help')
    helpdlg(strcat('This tool will create one subfolder per cluster within your output folder,  ',...
                   ' and fill each with representative examples of the associated cluster. ',...
                   ' You can rearrange files, merge folders, rename folders, or add examples ',...
                   ' from other clustering iterations to the folders prior to running the next step:  ''Make train & test sets'''))
end

end
