function ct_cc_savebouts_gui(~,~)
% TODO: would be nice to have the option to merge bins into bouts.

global REMORA

if ~isfield(REMORA.ct.CC,'output')
    warning('No composite clusters loaded')
    ct_load_composite_clusters
end
initAxes = 0;
if isfield(REMORA.fig, 'ct')
    % check if the figure already exists. If so, don't move it.
    if isfield(REMORA.fig.ct, 'cc_saveBouts') && isvalid(REMORA.fig.ct.cc_saveBouts)
        defaultPos = get(REMORA.fig.ct.cc_saveBouts,'Position');
    else
        initAxes = 1;
    end
else 
    initAxes = 1;
end

default_pos = [0.35,.45,.3,.15];

if initAxes
    REMORA.fig.ct.cc_saveBouts = figure;
    
    set(REMORA.fig.ct.cc_saveBouts,...
        'Units','normalized',...
        'ToolBar', 'none',...
        'MenuBar','none',...
        'NumberTitle','off','Name',...
        'Composite Clustering Tool - v1.0: Bout Saving Options',...
        'Position',default_pos,...
        'Visible','on');
end

clf

% Title
REMORA.ct.CC.saveBouts = [];
labelStr = 'Bout Saving Options';
btnPos=[0 .8 1 .2];
REMORA.ct.CC.saveBouts.headText = uicontrol(REMORA.fig.ct.cc_saveBouts, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',12,...
    'Visible','on');  %'BackgroundColor',bgColor3,...

%% Output Folder Text
labelStr = 'Output Folder';
btnPos=[.02 .6 .15 .15];
REMORA.ct.CC.saveBouts.outDirTxt = uicontrol(REMORA.fig.ct.cc_saveBouts,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','Right',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Select output directory
if ~isfield(REMORA.ct.CC.output,'boutDir') && isfield(REMORA.ct.CC_params, 'inDir')
    % To start, assume output folder = cluster_bins folder 
    REMORA.ct.CC.output.boutDir =  REMORA.ct.CC_params.inDir;
elseif ~isfield(REMORA.ct.CC.output,'boutDir')&& ~isfield(REMORA.ct.CC.output,'inDir')
    REMORA.ct.CC.output.boutDir = 'C:\';
end

% Output Folder Editable Text
btnPos=[.2 .65 .70 .15];
REMORA.ct.CC.saveBouts.outDirEdTxt = uicontrol(REMORA.fig.ct.cc_saveBouts,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'String',REMORA.ct.CC.output.boutDir,...
    'FontUnits','normalized',...
    'Visible','on',...
    'Callback',{@ct_cc_savebouts_control,'setOutDir'});


% Bout file name
labelStr = 'Output File Name';
btnPos=[.02 .3 .15 .15];
REMORA.ct.CC.saveBouts.outFNameTxt = uicontrol(REMORA.fig.ct.cc_saveBouts,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','Right',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Bout file name Editable Text
REMORA.ct.CC.output.boutFName = 'Bouts.csv';
btnPos=[.2 .35 .70 .15];
REMORA.ct.CC.saveBouts.outFNameEdTxt = uicontrol(REMORA.fig.ct.cc_saveBouts,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'String',REMORA.ct.CC.output.boutFName,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@ct_cc_savebouts_control,'setBoutFName'});

% Modify labels button
labelStr = 'Edit labels';
btnPos=[.2, 0.05, .2, .15];

REMORA.ct.CC.saveBouts.labelBtn = uicontrol(REMORA.fig.ct.cc_saveBouts,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',[.8,.8,.8],...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback',@ct_cc_apply_labels_gui);

% put a "Save" button
labelStr = 'Save';
btnPos=[.6, 0.05, .2, .15];

REMORA.ct.CC.saveBouts.saveBtn = uicontrol(REMORA.fig.ct.cc_saveBouts,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','green',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback',@ct_cc_savebouts);



end


function ct_cc_savebouts_control(hObject,eventdata,myEvent)

global REMORA

if strcmp(myEvent, 'setOutDir')
    REMORA.ct.CC.output.boutDir = get(REMORA.ct.CC.saveBouts.outDirEdTxt,'String');    
elseif strcmp(myEvent, 'setBoutFName')
    REMORA.ct.CC.output.boutFName = get(REMORA.ct.CC.saveBouts.outFNameEdTxt,'String');    
end

end

