function ctHelpStrings = ct_cc_get_help_strings

%%% Clustering parameter choices %%%
ctHelpStrings.inDir = 'Folder containing cluster bins output file(s).';
ctHelpStrings.outDir = 'Folder where composite clusters output should be saved.';
ctHelpStrings.inFileString = 'Recommended. Wildcard for restricting input files by name.';
ctHelpStrings.outputName = 'A string for use in output file names. \nChange this to avoid overwriting prior runs.';
ctHelpStrings.saveOutput = 'Check box if you want to save output files';

ctHelpStrings.minClust = ['Minimum number of detections per bin required for a cluster to be used in composite step.\n', ... 
  'Higher number makes cleaner clusters, but may miss things that click slowly or rarely.'];
 
ctHelpStrings.pruneThr = ['Percentage of edges between nodes that you want to prune.\n ',...
'Pruning speeds up clustering and affects separation of types,\n',...
'but can result in isolation (therefore exclusion) of rare click types.'];

ctHelpStrings.correctForSaturation = ['Looks for secondary ICI peaks in',...
	 'cases where clicking is so dense that individual ICIs are obscured.\nThis ',...
	 'helps with marine mammals in large groups, but may hurt if you are\n',...
     'trying to pull out ships and rain too.\nOnly applies if modal ICI is used.'];

ctHelpStrings.useTimesTF = 'Compare bins based on temporal features?';

ctHelpStrings.minClust = ['Minimum cluster size to be retained in composite output.\n',...
    'Clusters consisting of fewer than this number of bins will be discarded.'];

ctHelpStrings.minClicks = ['Minimum number of clicks per bin to consider.\n',... 
    'Bins with fewer than this number of detections will be excluded from clusters.\n',...
    'Higher number makes cleaner clusters, but may miss things that click slowly.'];

ctHelpStrings.maxNetworkSz = ['Maximum number of bins to cluster simultaneously.\n',...
    'If number of bins in set exceeds this, a random subset of this size will be selected.'];

ctHelpStrings.singleClusterOnly = 'Restrict network input to bins where only one cluster was formed.';

ctHelpStrings.maxCWiterations = 'Maximum number of clustering iterations allowed.';

ctHelpStrings.mergeTF = ['If TRUE when a graph is large, we will attempt to reduce ',...
    'computation time\n by merging extremely similar nodes before clustering.'];

ctHelpStrings.linearTF = ['If TRUE, compare spectra in linear space,\n',...
    'otherwise compares in log (dB) scale.'];

ctHelpStrings.NTrials = ['Number of trials to run.\n',...
    'If >1, the best partition accross trials will be chosen based on\n',...
    'evidence accumulation. A larger number will theoretically produce\n',...
    'more robust clusters, but takes longer.'];

ctHelpStrings.plotFlag = ['If TRUE, plots will be shown for each clustered bin.\n'...
    'Turn this off for large jobs, but useful for seeing how your\n',...
    'clusters are coming out when choosing parameters.\n',...
    'Plotting is not available when parpool size > 1.'];

ctHelpStrings.falseRM = ['If TRUE, tool will check for FD file from detEdit and ',...
    'remove labeled false positives. \nOtherwise all detections in TPWS files ',...
    'will be used as clustering input.'];

ctHelpStrings.barIntMax = ''; %ICI bins in seconds (minICI:resolution:maxICI)

ctHelpStrings.diff = 'If TRUE, compare first derivative of spectra instead of original values.';

ctHelpStrings.ppThresh = ['If specified, enforces a minimum recieved level in ',...
    'dB peak to peak,\n and only clusters higher amplitude events, ', ...
    'which tend to have cleaner spectra.'];
 
ctHelpStrings.timeStep = ['Bin duration in minutes. \nDetections are ',...
    'clustered by time bin. How long of a time bin do you want to consider?\n',...
    'Larger bins -> more detections, better representation for slow cue rate sources.\n',...
    'However large time bins mean more detection counts -> longer computation ',... 
    'times,\n or subsampling when detections accumulate rapidly in time.'];

ctHelpStrings.maxClust = ['Maximum number of bins to cluster. If you have more than\n',...
    'this number in your input, a random subset of this size\n will be selected.\n',...
    'Choose based on your amount of RAM and patience.'];


ctHelpStrings.N = ['Number of clusterings to use for evidence accumulation.\n',...
	'Bigger is theoretically more robust, but takes longer.'];

ctHelpStrings.freqs = ['Range of frequencies you want to compare spectra across:\n',...
    'Comparing across the full bandwidth tends to reduce differences between similar\n',...
    'spectra. Results are typically better if you focus on comparing the region\n',...
    'where spectra differ most.\n',...
    'If your spectra roll off at the edges, use start and end freq to \n',...
    'exclude those regions. Including roll-off will reduce overall \nspectral differences.'];

ctHelpStrings.clusterPrune = ['Fraction of least-connected nodes to prune from each cluster. \n',...
    'Results in purer, but smaller clusters and more isolated nodes.'];

ctHelpStrings.rmvBins = ['Removes all bins with a certain degree of spectral similarity to bins \n'...
    'of unwanted clusters from this clustering iteration.'];

ctHelpStrings.SBdiff = ['Allowable amplitude difference for each point of mean spectra. \n',...
    'When compared to spectra of bins in removed clusters, any mean spectra within this amplitude \n'...
    'difference for most points will be removed.'];

ctHelpStrings.SBperc = ['Percent similarity required between a given bins mean spectra and spectra \n'...
    'of removed clusters for bin to be removed from potential clustering.'];
