function nn_ui_export_zID(hObject,eventdata)


% if bin: need to iterate through bin files

global REMORA

if ~isfield(REMORA.nn, 'exportzID')
    REMORA.nn.exportzID = [];
end
defaultPos = [0.35,.45,.3,.25];
initAxes = 0;
if isfield(REMORA.fig, 'nn')
    % check if the figure already exists. If so, don't move it.
    if isfield(REMORA.fig.nn, 'exportzID') && isvalid(REMORA.fig.nn.exportzID.figH)
        defaultPos = get(REMORA.fig.nn.exportzID.figH,'Position');
    else
        initAxes = 1;
    end
else
    initAxes = 1;
end



if initAxes
    REMORA.fig.nn.exportzID.figH = figure;
    
    set(REMORA.fig.nn.exportzID.figH,...
        'Units','normalized',...
        'ToolBar', 'none',...
        'MenuBar','none',...
        'NumberTitle','off','Name',...
        'Neural Net Tool - v1.0: Export DetEdit ID File(s)',...
        'Position',defaultPos,...
        'Visible','on');
else
    clf(REMORA.fig.nn.exportzID.figH)
end

%% button grid layouts
% 14 rows, 4 columns
r = 13; % rows      (extra space for separations btw sections)
c = 4;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;

% colors
bgColor = [1 1 1];  % white
bgColorRed = [1 .6 .6];  % red
bgColorGray = [.86 .86 .86];  % gray
bgColor3 = [.68,.92,0]; % a green
bgColor4 = [.75 .875 1]; % light blue 

%% Title
labelStr = 'Export Network Labels to DetEdit ID Format';
btnPos=[0 .9 1 .1];

REMORA.fig.nn.exportzID.headText = uicontrol(REMORA.fig.nn.exportzID.figH, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontSize',12,...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');

btnPos=[x(1) y(4) w*4 dy*2];
REMORA.fig.nn.exportzID.bg = uibuttongroup('Visible','on',...
    'Position',btnPos,...
    'BorderType','etchedin');%'SelectionChangedFcn',{@ct_cc_control},...


if ~isfield(REMORA.nn.exportzID,'binsTF')
    REMORA.nn.exportzID.binsTF = 1;
end
% Create 2 radio buttons in the button group.
btnPos=[0.25,0 .4 1];
REMORA.fig.nn.exportzID.bg_r1 = uicontrol(REMORA.fig.nn.exportzID.bg ,'Style','radiobutton',...
    'Units','normalized',...
    'String','Bins',...
    'Position',btnPos,...
    'HandleVisibility','on',...
    'Value',REMORA.nn.exportzID.binsTF,...
    'Callback','nn_ui_exportzID_control(''setBinTF'')');

REMORA.nn.exportzID.detsTF = ~REMORA.nn.exportzID.binsTF;
if REMORA.nn.exportzID.binsTF
    REMORA.fig.nn.exportzID.binsVisible = 'on';
    REMORA.fig.nn.exportzID.detsVisible = 'off';
else
    REMORA.fig.nn.exportzID.binsVisible = 'off';
    REMORA.fig.nn.exportzID.detsVisible = 'on';
end

btnPos=[0.6,0 .4 1];
REMORA.fig.nn.exportzID.bg_r2 = uicontrol(REMORA.fig.nn.exportzID.bg ,'Style','radiobutton',...
    'Units','normalized',...
    'String','Detections',...
    'Position',btnPos,...
    'HandleVisibility','on',...
    'Value',REMORA.nn.exportzID.detsTF,...
    'Callback','nn_ui_exportzID_control(''setDetTF'')');

%If bin: "Location of 'Cluster Bins' output"
if strcmp(REMORA.fig.nn.exportzID.binsVisible,'on')
    REMORA.nn.exportzID.inDirTxt = 'Folder of Network Classification Output (bin):';
else
    REMORA.nn.exportzID.inDirTxt = 'Folder of Network Classifications Output(det):';
end


btnPos=[x(1)+w/8 y(5)-ybuff 3*w h];
REMORA.fig.nn.exportzID.inDirTxt = uicontrol(REMORA.fig.nn.exportzID.figH,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(REMORA.nn.exportzID.inDirTxt,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

if ~isfield(REMORA.nn.exportzID,'inDir')
    REMORA.nn.exportzID.inDir = 'C:\';
end

btnPos=[x(1)+w/4 y(6) .85 h];
REMORA.fig.nn.exportzID.inDirEdTxt = uicontrol(REMORA.fig.nn.exportzID.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',REMORA.nn.exportzID.inDir,...
    'HorizontalAlignment','left',...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_exportzID_control(''setInDir'')');


if ~isfield(REMORA.fig.nn,'searchIcon')
    REMORA.fig.nn.searchIcon = nn_ui_search_icon;
end

btnPos=[.92 y(6) w/5 h];
REMORA.fig.nn.exportzID.inDirPathBtn = uicontrol(REMORA.fig.nn.exportzID.figH,...
    'Style','pushbutton',...
    'Units','normalized',...
    'CData',REMORA.fig.nn.searchIcon,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_exportzID_control(''selectInDir'')');%   'BackgroundColor',bgColor3,...

%% Optional wildcard
btnPos=[.35 y(7)-ybuff 3*w h];
REMORA.fig.nn.exportzID.wildcardTxt = uicontrol(REMORA.fig.nn.exportzID.figH,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String','Filename Wildcard (optional)',...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

if ~isfield(REMORA.nn.exportzID,'wildcard')
    REMORA.nn.exportzID.wildcard = '';
end
btnPos=[.65 y(7) .262 h];
REMORA.fig.nn.exportzID.wildcardEdTxt = uicontrol(REMORA.fig.nn.exportzID.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',REMORA.nn.exportzID.wildcard,...
    'HorizontalAlignment','left',...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_exportzID_control(''setWildcard'')');

%% Location to save spreadsheet
btnPos=[x(1)+w/8 y(8)-ybuff 3*w h];
REMORA.fig.nn.exportzID.saveDirTxt = uicontrol(REMORA.fig.nn.exportzID.figH,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String','Output Folder:',...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

if ~isfield(REMORA.nn.exportzID,'saveDir')
    if isfield(REMORA.nn,'classify') && isfield(REMORA.nn.classify,'saveDir')
        REMORA.nn.exportzID.saveDir = REMORA.nn.classify.saveDir;
    else
        REMORA.nn.exportzID.saveDir = 'C:\';
    end
end

btnPos=[x(1)+w/4 y(9) .85 h];
REMORA.fig.nn.exportzID.saveDirEdTxt = uicontrol(REMORA.fig.nn.exportzID.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',REMORA.nn.exportzID.saveDir,...
    'HorizontalAlignment','left',...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_exportzID_control(''setSaveDir'')');

btnPos=[.92 y(9) w/5 h];
REMORA.fig.nn.exportzID.saveDirBtn = uicontrol(REMORA.fig.nn.exportzID.figH,...
    'Style','pushbutton',...
    'Units','normalized',...
    'CData',REMORA.fig.nn.searchIcon,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_exportzID_control(''selectSaveDir'')');%   'BackgroundColor',bgColor3,...

btnPos = [x(2)+(x(2)/2) y(12) w h*2];
REMORA.fig.nn.exportzID.runBtn = uicontrol(REMORA.fig.nn.exportzID.figH,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',[.68,.92,0],...
    'HorizontalAlignment','center',...
    'string','Run',...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_exportzID_control(''Run'')');
