function sp_dt_mkTPWS_gui

global REMORA
% button grid layouts
% 14 rows, 4 columns
% button grid layouts
% 14 rows, 4 columns
r = 10; % rows      (extra space for separations btw sections)
c = 2;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
% ybuff = h*.2;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = [.05,.5];


% colors
bgColor = [1 1 1];  % white
bgColor3 = [.75 .875 1]; % light green 


% Setup variables:
defaultPos = [0.4,0.4,0.2,0.2];
% open and setup figure window

% If window already exists, close
if isfield(REMORA.fig, 'sp_dt_mkTPWS')
    if isgraphics(REMORA.fig.sp_dt_mkTPWS)
        close(REMORA.fig.sp_dt_mkTPWS)
    end
end

REMORA.fig.sp_dt_mkTPWS = figure( ...
    'NumberTitle','off', ...
    'Name','Make TPWS from detections',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on');

REMORA.spice_dt_mkTPWS = [];
labelStr = 'Specify Detection Information';
btnPos=[0 y(2) w*c h];
REMORA.spice_dt_mkTPWS.headtext = uicontrol(REMORA.fig.sp_dt_mkTPWS, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',11,...
    'Visible','on'); 


labelStr = 'Base Folder';
btnPos=[x(1) y(3) .5*w dy];
REMORA.spice_dt_mkTPWS.baseDirTxt = uicontrol(REMORA.fig.sp_dt_mkTPWS,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'HorizontalAlignment','left',...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');%   'BackgroundColor',bgColor3,...

% Base Folder Editable Text
labelStr = '';
btnPos=[0+w/2 y(3) (w*c)*.7 dy];
REMORA.spice_dt_mkTPWS.baseDirEdTxt = uicontrol(REMORA.fig.sp_dt_mkTPWS,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','sp_dt_TPWS_control(''setTPWSBaseDir'')');

% Base Folder Checkbox
labelStr = 'Run on Subfolders';
btnPos=[0+w/2 y(4) (w*c)*.7 dy];
REMORA.spice_dt_mkTPWS.subDirCheckBox = uicontrol(REMORA.fig.sp_dt_mkTPWS,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','sp_dt_TPWS_control(''setSubDirTF'')');

% Output Folder Text
labelStr = 'Output Folder';
btnPos=[x(1) y(5) w/2 dy];
REMORA.spice_dt_mkTPWS.outDirTxt = uicontrol(REMORA.fig.sp_dt_mkTPWS,...
   'Style','text',...
   'Units','normalized',...
   'HorizontalAlignment','left',...
   'Position',btnPos,...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');%   'BackgroundColor',bgColor3,...

% Output Folder Editable Text
labelStr = '';
btnPos=[0+w/2 y(5) (w*c)*.7 dy];
REMORA.spice_dt_mkTPWS.outDirEdTxt = uicontrol(REMORA.fig.sp_dt_mkTPWS,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_TPWS_control(''setTPWSOutDir'')');

% Filter String Text
labelStr = 'Partial String to Match (optional)';
btnPos=[x(1) y(6) w dy];
REMORA.spice_dt_mkTPWS.filterStringTxt = uicontrol(REMORA.fig.sp_dt_mkTPWS,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'HorizontalAlignment','left',...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');%   'BackgroundColor',bgColor3,...

%  Filter String Editable Text
labelStr = '';
btnPos=[x(2) y(6) w*.9 dy];
REMORA.spice_dt_mkTPWS.filterStringEdTxt = uicontrol(REMORA.fig.sp_dt_mkTPWS,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_TPWS_control(''setTPWSFilterString'')');


% Min RL Text
labelStr = 'Min. Recieved Level Threshold (dBpp, optional)';
btnPos=[x(1) y(7) w*1.5 dy];
REMORA.spice_dt_mkTPWS.minRLTxt = uicontrol(REMORA.fig.sp_dt_mkTPWS,...
   'Style','text',...
   'Units','normalized',...
   'Position',btnPos,...
   'HorizontalAlignment','left',...
   'String',sprintf(labelStr,'Interpreter','tex'),...
   'FontUnits','normalized', ...
   'Visible','on');%   'BackgroundColor',bgColor3,...

%  Min RL Editable Text
labelStr = '';
btnPos=[x(2)+w/2 y(7) w/2*.8 dy];
REMORA.spice_dt_mkTPWS.minRLEdTxt = uicontrol(REMORA.fig.sp_dt_mkTPWS,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','sp_dt_TPWS_control(''setTPWSminRL'')');


labelStr = 'Make TPWS Files';
btnPos=[.25 y(10) .5 2*h];
REMORA.spice_dt_mkTPWS.refresh = uicontrol(REMORA.fig.sp_dt_mkTPWS, ...
   'Style','pushbutton', ...
   'Units','normalized', ...
   'Position',btnPos, ...
   'BackgroundColor',bgColor3,...
   'String',labelStr, ...
   'FontUnits','points', ...
   'FontWeight','bold',...
   'FontSize',11,...
   'Callback','sp_dt_TPWS_control(''run_mkTPWS'')');

