function cc_count_params_window
% made by SGB 20240717
% Shelby G. Bloom (sbloom@ucsd.edu)
% modified/based on Soundscape-Metrics Remora gui folder code by Simone Baumann-Pickering

    global REMORA

    defaultPos = [0.25,0.2,0.38,0.67];
    if isfield(REMORA.fig, 'cc')
        % Check if the figure already exists. If so, don't move it.
        if isfield(REMORA.fig.cc, 'count') && isvalid(REMORA.fig.cc.count)
            defaultPos = get(REMORA.fig.cc.count,'Position');
        else
            REMORA.fig.cc.count = figure;
        end
    else 
        REMORA.fig.cc.count = figure;
    end

    clf

    set(REMORA.fig.cc.count,'NumberTitle','off', ...
        'Name','Make countCOFI Table  - v1.0',...
        'Units','normalized',...
        'MenuBar','none',...
        'Position',defaultPos, ...
        'Visible', 'on',...
        'ToolBar', 'none');

    figure(REMORA.fig.cc.count)

    % Load/save settings pulldown:

    if ~isfield(REMORA.fig.cc,'CCfileMenu') || ~isvalid(REMORA.fig.cc.CCfileMenu)
        REMORA.fig.cc.CCfileMenu = uimenu(REMORA.fig.cc.count,'Label',...
            'Save/Load Settings','Enable','on','Visible','on');

        % count load/save params:
        uimenu(REMORA.fig.cc.CCfileMenu,'Label','&Load Settings',...
            'Callback','cc_count_control(''cc_count_settingsLoad'')');
        uimenu(REMORA.fig.cc.CCfileMenu,'Label','&Save Settings',...
            'Callback','cc_count_control(''cc_count_settingsSave'')');
    end

    % Button grid layouts
    % 21 rows, 2 columns
    r = 22; % Rows (Extra space for separations between sections)
    c = 2;  % Columns
    h = 1/r;
    w = 1/c;
    dy = h * 0.8;
    % dx = 0.008;
    ybuff = h*.2;
    % Y Position (Rrelative Units)
    y = 1:-h:0;

    % X Position (Relative Units)
    x = 0:w:1;

    % Colors
    bgColor = [1 1 1];  % White
    bgColorRed = [1 .6 .6];  % Red
    % bgColorGray = [.86 .86 .86];  % Gray
    bgColor3 = [.75 .875 1]; % Light Blue 
    bgColor4 = [.76 .87 .78]; % Light Green 

    REMORA.cc.verify = [];

    REMORA.cc.params_help = cc_count_get_help_strings;

    %% Title:

    labelStr = 'countCOFI Table File Settings';
    btnPos=[x(1) y(2) 2*w h];
    REMORA.cc.count.headtext = uicontrol(REMORA.fig.cc.count, ...
        'Style','text', ...
        'Units','normalized', ...
        'Position',btnPos, ...
        'String',labelStr, ...
        'FontUnits','points', ...
        'FontWeight','bold',...
        'FontSize',12,...
        'Visible','on');
    %% Set paths and strings
    %***********************************
    % Input Directory Text
    labelStr = 'Directory with Daily Expanded Files';
    btnPos=[x(1) y(3)-ybuff w/2 h];
    REMORA.cc.verify.indirTxt = uicontrol(REMORA.fig.cc.count,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'TooltipString',sprintf(REMORA.cc.params_help.indirHelp));
    %  'BackgroundColor',bgColor3,...

    % Input Directory Editable Text
    labelStr=num2str(REMORA.cc.count.indir);
    btnPos=[x(1)+w/2 y(3) w h];
    REMORA.cc.verify.indir = uicontrol(REMORA.fig.cc.count,...
        'Style','edit',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'HorizontalAlignment','left',...
        'Visible','on',...
        'Callback','cc_count_control(''setindir'')');

    % Change Input Directory Button
    labelStr = 'Select';
    btnPos=[x(1)+w*1.6 y(3) w/4 h];

    REMORA.cc.verify.indirSel = uicontrol(REMORA.fig.cc.count,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor3,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'FontSize',.4,...
        'Visible','on',...
        'FontWeight','normal',...
        'Callback','cc_count_control(''indirSel'')');

    %% Output Directory Text
    labelStr = 'Output Directory for countCOFI Table';
    btnPos=[x(1) y(4)-ybuff w/2 h];
    REMORA.cc.verify.outdirTxt = uicontrol(REMORA.fig.cc.count,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'TooltipString',sprintf(REMORA.cc.params_help.outdirHelp));%   'BackgroundColor',bgColor3,...

    % Output Folder Editable Text
    labelStr=num2str(REMORA.cc.count.outdir);
    btnPos=[x(1)+w/2 y(4) w h];
    REMORA.cc.verify.outdir = uicontrol(REMORA.fig.cc.count,...
        'Style','edit',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor,...
        'HorizontalAlignment','left',...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'Visible','on',...
        'Callback','cc_count_control(''setoutdir'')');

    % Change Output Directory Button
    labelStr = 'Select';
    btnPos=[x(1)+w*1.6 y(4) w/4 h];

    REMORA.cc.verify.outdirSel = uicontrol(REMORA.fig.cc.count,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor3,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'FontSize',.4,...
        'Visible','on',...
        'FontWeight','normal',...
        'Callback','cc_count_control(''outdirSel'')');
    
 %% Input and Output Parameters   
    % Left Column:
    labelStr = 'Input GMT Time Difference';
    btnPos=[x(1)+w*0.1 y(5)+ybuff/2 w/2 h/2];
    REMORA.cc.verify.GMTdiffTxt = uicontrol(REMORA.fig.cc.count,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'FontWeight','bold',...   
       'Visible','on');
   
    % GMT Time Difference Text
    labelStr = 'GMT Time Difference [no. hours]';
    btnPos=[x(1) y(6)-ybuff w/2 h];
    REMORA.cc.verify.GMTdiffTxt = uicontrol(REMORA.fig.cc.count,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'TooltipString',sprintf(REMORA.cc.params_help.GMTdiffHelp));

    % GMT Time Difference Editable Text
    labelStr=num2str(REMORA.cc.count.GMTdiff);
    btnPos=[x(1)+w/2 y(6) w/4 h];
    REMORA.cc.verify.GMTdiff = uicontrol(REMORA.fig.cc.count,...
        'Style','edit',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'Visible','on',...
        'Callback','cc_count_control(''setGMTdiff'')');
 
    %% Make countCOFI Table File Button
    labelStr = 'Make countCOFI Table File';
    btnPos=[x(2)-w/2 y(21) w h];

    REMORA.cc.verify.countTxt = uicontrol(REMORA.fig.cc.count,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor3,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'FontSize',.5,...
        'Visible','on',...
        'FontWeight','bold',...
        'Callback','cc_count_control(''runcount'')');

