function cc_vis_params_window
% made by SGB 20240717
% Shelby G. Bloom (sbloom@ucsd.edu)
% modified/based on Soundscape-Metrics Remora gui folder code by Simone Baumann-Pickering

    global REMORA

    defaultPos = [0.25,0.35,0.38,0.4];
    if isfield(REMORA.fig, 'cc')
        % Check if the figure already exists. If so, don't move it.
        if isfield(REMORA.fig.cc, 'vis') && isvalid(REMORA.fig.cc.vis)
            defaultPos = get(REMORA.fig.cc.vis,'Position');
        else
            REMORA.fig.cc.vis = figure;
        end
    else 
        REMORA.fig.cc.vis = figure;
    end

    clf

    set(REMORA.fig.cc.vis,'NumberTitle','off', ...
        'Name','Make visEffort Outputs  - v1.0',...
        'Units','normalized',...
        'MenuBar','none',...
        'Position',defaultPos, ...
        'Visible', 'on',...
        'ToolBar', 'none');

    figure(REMORA.fig.cc.vis)

    % Load/save settings pulldown:

    if ~isfield(REMORA.fig.cc,'CCfileMenu') || ~isvalid(REMORA.fig.cc.CCfileMenu)
        REMORA.fig.cc.CCfileMenu = uimenu(REMORA.fig.cc.vis,'Label',...
            'Save/Load Settings','Enable','on','Visible','on');

        % vis load/save params:
        uimenu(REMORA.fig.cc.CCfileMenu,'Label','&Load Settings',...
            'Callback','cc_vis_control(''cc_vis_settingsLoad'')');
        uimenu(REMORA.fig.cc.CCfileMenu,'Label','&Save Settings',...
            'Callback','cc_vis_control(''cc_vis_settingsSave'')');
    end

    % Button grid layouts
    % 12 rows, 2 columns
    r = 13; % Rows (Extra space for separations between sections)
    c = 2;  % Columns
    h = 1/r;
    w = 1/c;
    dy = h * 0.8;
    % dx = 0.008;
    ybuff = h*.2;
    % Y Position (Rrelative Units)
    y = 1:-h:0;

    % X Position (Relative Units)
    x = 0:w:1;

    % Colors
    bgColor = [1 1 1];  % White
    bgColorRed = [1 .6 .6];  % Red
    % bgColorGray = [.86 .86 .86];  % Gray
    bgColor3 = [.75 .875 1]; % Light Green 
    bgColor4 = [.76 .87 .78]; % Light Blue  

    REMORA.cc.verify = struct();

    REMORA.cc.params_help = cc_vis_get_help_strings;

    %% Title:

    labelStr = 'visEffort Outputs Settings';
    btnPos=[x(1) y(2) 2*w h];
    REMORA.cc.vis.headtext = uicontrol(REMORA.fig.cc.vis, ...
        'Style','text', ...
        'Units','normalized', ...
        'Position',btnPos, ...
        'String',labelStr, ...
        'FontUnits','points', ...
        'FontWeight','bold',...
        'FontSize',12,...
        'Visible','on');
    %% Set paths and strings
    %***********************************
    % Input File Text
    labelStr = 'File Path of GPS Track';
    btnPos=[x(1) y(3)-ybuff w/2 h];
    REMORA.cc.verify.GPSFilePathTxt = uicontrol(REMORA.fig.cc.vis,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'TooltipString',sprintf(REMORA.cc.params_help.GPSFilePathHelp));
    %  'BackgroundColor',bgColor3,...

    % Input File Editable Text
    labelStr=num2str(REMORA.cc.vis.GPSFilePath);
    btnPos=[x(1)+w/2 y(3) w h];
    REMORA.cc.verify.GPSFilePath = uicontrol(REMORA.fig.cc.vis,...
        'Style','edit',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'HorizontalAlignment','left',...
        'Visible','on',...
        'Callback','cc_vis_control(''setGPSFilePath'')');

    % Change Input File Button
    labelStr = 'Select';
    btnPos=[x(1)+w*1.6 y(3) w/4 h];

    REMORA.cc.verify.GPSFilePathSel = uicontrol(REMORA.fig.cc.vis,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor3,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'FontSize',.4,...
        'Visible','on',...
        'FontWeight','normal',...
        'Callback',@selectGPSFilePath);
    
    %% Set paths and strings
    %***********************************
    % Input File Text
    labelStr = 'File Path of Concatenated File';
    btnPos=[x(1) y(4)-ybuff w/2 h];
    REMORA.cc.verify.effFilePathTxt = uicontrol(REMORA.fig.cc.vis,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'TooltipString',sprintf(REMORA.cc.params_help.effFilePathHelp));
    %  'BackgroundColor',bgColor3,...

    % Input File Editable Text
    labelStr=num2str(REMORA.cc.vis.effFilePath);
    btnPos=[x(1)+w/2 y(4) w h];
    REMORA.cc.verify.effFilePath = uicontrol(REMORA.fig.cc.vis,...
        'Style','edit',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'HorizontalAlignment','left',...
        'Visible','on',...
        'Callback','cc_vis_control(''seteffFilePath'')');

    % Change Input File Button
    labelStr = 'Select';
    btnPos=[x(1)+w*1.6 y(4) w/4 h];

    REMORA.cc.verify.effFilePathSel = uicontrol(REMORA.fig.cc.vis,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor3,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'FontSize',.4,...
        'Visible','on',...
        'FontWeight','normal',...
        'Callback',@selectEffFilePath);
    
    %% Output Directory Text
    labelStr = 'Output Directory for visEffort Outputs';
    btnPos=[x(1) y(5)-ybuff w/2 h];
    REMORA.cc.verify.oDirTxt = uicontrol(REMORA.fig.cc.vis,...
       'Style','text',...
       'Units','normalized',...
       'Position',btnPos,...
       'String',sprintf(labelStr,'Interpreter','tex'),...
       'FontUnits','normalized', ...
       'Visible','on',...
       'TooltipString',sprintf(REMORA.cc.params_help.oDirHelp));%   'BackgroundColor',bgColor3,...

    % Output Folder Editable Text
    labelStr=num2str(REMORA.cc.vis.oDir);
    btnPos=[x(1)+w/2 y(5) w h];
    REMORA.cc.verify.oDir = uicontrol(REMORA.fig.cc.vis,...
        'Style','edit',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor,...
        'HorizontalAlignment','left',...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'Visible','on',...
        'Callback','cc_vis_control(''setoDir'')');

    % Change Output Directory Button
    labelStr = 'Select';
    btnPos=[x(1)+w*1.6 y(5) w/4 h];

    REMORA.cc.verify.oDirSel = uicontrol(REMORA.fig.cc.vis,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor3,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'FontSize',.4,...
        'Visible','on',...
        'FontWeight','normal',...
        'Callback',@selectOutputDir);
    

    %% Make visEffort Outputs File Button
    labelStr = 'Make visEffort Outputs';
    btnPos=[x(2)-w/2 y(13) w h];

    REMORA.cc.verify.visTxt = uicontrol(REMORA.fig.cc.vis,...
        'Style','pushbutton',...
        'Units','normalized',...
        'Position',btnPos,...
        'BackgroundColor',bgColor3,...
        'String',labelStr,...
        'FontUnits','normalized', ...
        'FontSize',.5,...
        'Visible','on',...
        'FontWeight','bold',...
        'Callback','cc_vis_control(''runvis'')');
end

function selectGPSFilePath(~, ~)
    global REMORA
    [file, path] = uigetfile('*.csv', 'Select GPS Track File');
    if ischar(file)
        REMORA.cc.vis.GPSFilePath = fullfile(path, file);
        set(REMORA.cc.verify.GPSFilePath, 'String', REMORA.cc.vis.GPSFilePath);
    end
end

function selectEffFilePath(~, ~)
    global REMORA
    [file, path] = uigetfile('*.txt', 'Select Concatenated File');
    if ischar(file)
        REMORA.cc.vis.effFilePath = fullfile(path, file);
        set(REMORA.cc.verify.effFilePath, 'String', REMORA.cc.vis.effFilePath);
    end
end

function selectOutputDir(~, ~)
    global REMORA
    path = uigetdir('', 'Select Output Directory');
    if ischar(path)
        REMORA.cc.vis.oDir = path;
        set(REMORA.cc.verify.oDir, 'String', REMORA.cc.vis.oDir);
    end
end
