function MT_speed_gui
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% sh_init_batch_gui.m
%
% Verify settings in GUI before running on entire drive.
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
global REMORA

defaultPos = [0.25,0.25,0.3,0.6];
REMORA.fig.MT.speed = figure( ...
    'NumberTitle','off', ...
    'Name','Tag Viewer_speed calculation - v1.0',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on');

% button grid layouts
% 14 rows, 4 columns
r = 14; % rows      (extra space for separations btw sections)
c = 2;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
xbuff = w*.1;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;

% colors
bgColor = [1 1 1];  % white
bgColorGrayLight = [.92 .92 .92];  % gray
bgColorGray = [.86 .86 .86];  % gray

REMORA.MT_verify = [];
labelStr = 'Calculate speed from accelerometer';
btnPos=[x(1) y(2) w*5 h];
REMORA.MT_verify.headtext = uicontrol(REMORA.fig.MT.speed, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');


% Set paths and strings
%***********************************

% High pass filter Text
labelStr = 'High-pass filter';
btnPos=[x(1)+xbuff  y(3) w dy];
REMORA.MT_verify.highpassTxt = uicontrol(REMORA.fig.MT.speed,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% High pass filter Editable Text
labelStr=num2str(REMORA.MT.settings.highpass);
btnPos=[x(2) y(3) w dy];
REMORA.MT_verify.highpassEdTxt = uicontrol(REMORA.fig.MT.speed,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','MT_control(''sethighpass'')');


% Low pass filter Text
labelStr = 'Low-pass filter';
btnPos=[x(1)+xbuff  y(4) w dy];
REMORA.MT_verify.lowpassTxt = uicontrol(REMORA.fig.MT.speed,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Low pass filter Editable Text
labelStr=num2str(REMORA.MT.settings.lowpass);
btnPos=[x(2) y(4) w dy];
REMORA.MT_verify.lowpassEdTxt = uicontrol(REMORA.fig.MT.speed,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','MT_control(''setlowpass'')');

% Bin size Text
labelStr = 'Bin size';
btnPos=[x(1)+xbuff y(5) w dy];
REMORA.MT_verify.binsizeTxt = uicontrol(REMORA.fig.MT.speed,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized',...
    'Visible','on');

% Bin size Editable Text
labelStr=num2str(REMORA.MT.settings.bin);
btnPos=[x(2) y(5) w dy];
REMORA.MT_verify.binsizeEdTxt = uicontrol(REMORA.fig.MT.speed,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized',...
    'Visible','on',...
    'Callback','MT_control(''setBinsize'')');

%  Target sample rate Text
labelStr = 'Target sample rate';
btnPos=[x(1)+xbuff y(6)-ybuff w*2 dy];
REMORA.MT_verify.fsText = uicontrol(REMORA.fig.MT.speed,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Target sample rate Editable Text
labelStr=num2str(REMORA.MT.settings.fs);
btnPos=[x(2) y(6) w dy];
REMORA.MT_verify.fsEdText = uicontrol(REMORA.fig.MT.speed,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_control(''setFs'')');

% Filter size text
 labelStr= 'Filter size';
 btnPos =[x(1)+xbuff y(7)-ybuff*2 w*2 h];
 REMORA.MT_verify.FilterText = uicontrol(REMORA.fig.MT.speed,...
      'Style','text',...
      'Units','normalized',...
     'HorizontalAlignment','left',...
     'Position',btnPos,...
     'String',sprintf(labelStr,'Interpreter','tex'),...
     'FontUnits','normalized',...
     'FontWeight','bold',...
     'Visible','on');

%Filter size Editable text
labelStr=num2str(REMORA.MT.settings.filter);
btnPos=[x(2) y(7) w dy];
REMORA.MT_verify.filterEdText = uicontrol(REMORA.fig.MT.speed,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','MT_control(''setFilter'')');

% Minimum Depth text
labelStr = 'Minimum Depth';
btnPos =[x(1)+xbuff y(8)-ybuff w dy];
REMORA.MT_verify.minDepthText = uicontrol(REMORA.fig.MT.speed,...
     'Style','text',...
     'Units','normalized',...
     'HorizontalAlignment','left',...
     'Position',btnPos,...
     'String',sprintf(labelStr,'Interpreter','tex'),...
     'FontUnits','normalized',...
     'Visible','on');

%Minimum Depth Editable text
labelStr=num2str(REMORA.MT.settings.minDepth);
btnPos=[x(2) y(8) w dy];
REMORA.MT_verify.minDepthEdText = uicontrol(REMORA.fig.MT.speed,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','MT_control(''setMinDepth'')');

% Minimum Pitch text
labelStr = 'Minimum Pitch';
btnPos =[x(1)+xbuff y(9)-ybuff w dy];
REMORA.MT_verify.minPitchText = uicontrol(REMORA.fig.MT.speed,...
     'Style','text',...
     'Units','normalized',...
     'HorizontalAlignment','left',...
     'Position',btnPos,...
     'String',sprintf(labelStr,'Interpreter','tex'),...
     'FontUnits','normalized',...
     'Visible','on');

%Minimum Pitch Editable text
labelStr=num2str(REMORA.MT.settings.minPitch);
btnPos=[x(2) y(9) w dy];
REMORA.MT_verify.minPitchEdText = uicontrol(REMORA.fig.MT.speed,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','MT_control(''setMinPitch'')');

% Minimum Speed text
labelStr = 'Minimum Speed';
btnPos =[x(1)+xbuff y(10)-ybuff w dy];
REMORA.MT_verify.minSpeedText = uicontrol(REMORA.fig.MT.speed,...
     'Style','text',...
     'Units','normalized',...
     'HorizontalAlignment','left',...
     'Position',btnPos,...
     'String',sprintf(labelStr,'Interpreter','tex'),...
     'FontUnits','normalized',...
     'Visible','on');

%Minimum Speed Editable text
labelStr=num2str(REMORA.MT.settings.minSpeed);
btnPos=[x(2) y(10) w dy];
REMORA.MT_verify.minSpeedEdText = uicontrol(REMORA.fig.MT.speed,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','MT_control(''setMinSpeed'')');

% Minimum Time text
labelStr = 'Minimum Time';
btnPos =[x(1)+xbuff y(11)-ybuff w dy];
REMORA.MT_verify.minTimeText = uicontrol(REMORA.fig.MT.speed,...
     'Style','text',...
     'Units','normalized',...
     'HorizontalAlignment','left',...
     'Position',btnPos,...
     'String',sprintf(labelStr,'Interpreter','tex'),...
     'FontUnits','normalized',...
     'Visible','on');

%Minimum Time Editable text
labelStr=num2str(REMORA.MT.settings.minTime);
btnPos=[x(2) y(11) w dy];
REMORA.MT_verify.minTimeEdText = uicontrol(REMORA.fig.MT.speed,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','MT_control(''setMinTime'')');

% Run button
labelStr = 'Run Detector';
btnPos=[x(2)-1/2*w y(13) w*1.5 h];
REMORA.MT_verify.RunDetectorEdTxt = uicontrol(REMORA.fig.MT.speed,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',[.47,.67,.19],...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','MT_control(''RunSpeedCalc'')');



