function mypsd_gui
global REMORA

% New Color Scheme (Professional Blue-Gray Theme)
bgColor       = [0.90, 0.94, 0.98];   % Main background
textColor     = [0.1, 0.2, 0.4];      % Label text
editBoxColor  = [1, 1, 1];            % White input boxes
buttonColor   = [0.2, 0.4, 0.7];      % Buttons: darker blue
buttonFontColor = [1, 1, 1];          % White button text

% Create main GUI figure (taller to accommodate all inputs)
REMORA.mypsd.gui.fig = figure('Name', 'Hybrid-millidecade Products', ...
    'NumberTitle', 'off', 'MenuBar', 'none', ...
    'ToolBar', 'none', 'Color', bgColor, ...
    'Position', [300, 50, 900, 1000]);
tabGroup = uitabgroup(REMORA.mypsd.gui.fig);



%% === TAB 1: Metadata Compiler ===
tab1 = uitab(tabGroup, 'Title', 'Metadata Compiler');
set(tab1, 'BackgroundColor', bgColor);

fontSize = 12;

% Define metadata fields
longFields = {'title', 'summary', 'history', 'source', 'acknowledgements'};
shortFields = {
    'citation', 'comment', 'conventions', 'creator_name', 'creator_role', ...
    'geospatial_bounds', 'id', 'infoUrl', 'institution', ...
    'instrument', 'keywords', 'keywords_vocabulary', 'license', ...
    'naming_authority', 'product_version', 'project', ...
    'publisher_name', 'publisher_type', 'reference', ...
    'standard_name_vocabulary'
    };

% Layout parameters
longLabelX = 30; longEditX = 160; longEditWidth = 660;
longFieldHeight = 55;
label_width = 120; edit_width = 240; edit_height = 25;
col1_x = 30; col2_x = 450;
spacing = 30;
yPos = 950;

% Add title to Tab 1
uicontrol(tab1, 'Style', 'text', ...
    'String', 'HARP HMD Metadata', ...
    'Position', [250, yPos-30, 400, 30], ...
    'FontSize', 16, 'FontWeight', 'bold', ...
    'BackgroundColor', bgColor, ...
    'ForegroundColor', textColor, ...
    'HorizontalAlignment', 'center');

yPos = yPos - 60;

% Long multi-line fields
for i = 1:length(longFields)
    field = longFields{i};
    switch field
        case 'title'
            defaultStr = {'Hybrid Millidecade Band Sound Pressure Levels Computed at 1 Minute Resolution from Oceanic Passive Acoustic Monitoring Recordings at the XXXXX'};
        case 'summary'
            defaultStr = {[
                'To understand natural and anthropogenic sound in the ocean, and to compare underwater soundscapes globally, ', ...
                'standard methods of analysis must be applied to passive acoustic monitoring (PAM) data. Methods that balance ', ...
                'constrained volume and adequate resolution of acoustic spectra have recently been published (Martin et al., 2021a,b). ', ...
                'A community effort supported by NOAA, BOEM, U.S. Navy, and ONR was initiated to apply these methods to PAM datasets ', ...
                'from around the world. This record represents the hybrid millidecade band (HMB) spectra of sound levels derived from ', ...
                'calibrated PAM data. Daily HMB spectra at 1 minute resolution were created using the SoundScape Remora in Triton (vXXX).';
                ]};

        case 'acknowledgements'
            defaultStr = {'The original audio recordings were supported by the Southern California Ocean Observing System'};
        case 'history'
            defaultStr = {'Original hybrid millidecade spectra were produced by the Marine Bioacoustics Research Collaborative (MBARC)'};
        case 'source'
            defaultStr = {['Data analysis was performed using the Soundscape Remora in Triton, to produce HMD spectra of sound ', ...
                'levels from oceanic audio recordings. Processing utilized MATLAB code provided as supplemental material in ',...
                'Martin et al. (2021b). Power spectral density (PSD) levels were computed from 1-minute segments of audio ',...
                'data. Frequency-dependent calibrations are included in the HMD. By applying fast Fourier transform (FFT) ',...
                'with length equal to the sample rate, using Hann window and 50% overlap, PSD estimates (V^2/Hz) were ', ...
                'computed with a frequency resolution of 1 Hz and a temporal resolution of 1 second. The 1 second PSD estimates ', ...
                'from each 1-minute segment were averaged, and the average spectrum for each minute was further processed to an ',...
                'HMD spectrum following Martin et al. (2021b).']}
        otherwise
            defaultStr = '';
    end



    uicontrol(tab1, 'Style', 'text', ...
        'String', [strrep(field, '_', ' '), ':'], ...
        'Position', [longLabelX, yPos, label_width, 20], ...
        'BackgroundColor', bgColor, ...
        'ForegroundColor', textColor, ...
        'HorizontalAlignment', 'left', 'FontWeight', 'bold', ...
        'FontSize', fontSize);

    REMORA.mypsd.meta.(field) = uicontrol(tab1, 'Style', 'edit', ...
        'Max', 3, 'Min', 0, ...
        'Position', [longEditX, yPos - longFieldHeight + 10, longEditWidth, longFieldHeight], ...
        'FontSize', 10, ...
        'HorizontalAlignment', 'left', 'String', defaultStr);
    yPos = yPos - longFieldHeight - spacing;
end

% Adjust base for short fields
shortFieldStartY = yPos - 20;
rowSpacing = 40; % tighter than 50
% Short fields in 2 columns

for i = 1:length(shortFields)
    field = shortFields{i};
    switch field

        case 'Conventions'
            defaultStr = {[]};
        case 'keywords'
            defaultStr = {[]};
        case 'keywords_vocabulary'
            defaultStr = {[]};
        case 'source'
            defaultStr = {[]};
        otherwise
            defaultStr = '';
    end

    col = mod(i-1, 2);
    row = floor((i-1)/2);
    x = col1_x + col * (col2_x - col1_x);
    y = yPos - row * 50;

    uicontrol(tab1, 'Style', 'text', ...
        'String', [strrep(field, '_', ' '), ':'], ...
        'Position', [x, y, label_width, 20], ...
        'BackgroundColor', bgColor, ...
        'ForegroundColor', textColor, ...
        'FontSize', fontSize, ...
        'HorizontalAlignment', 'left', 'FontWeight', 'bold');

    REMORA.mypsd.meta.(field) = uicontrol(tab1, 'Style', 'edit', ...
        'Position', [x + label_width + 5, y, edit_width, edit_height], ...
        'FontSize', 10, ...
        'HorizontalAlignment', 'left', 'String', '');
end


%% === TAB 2: HMD Controls ===
tab2 = uitab(tabGroup, 'Title', 'HMD Processing');
set(tab2, 'BackgroundColor', bgColor);

yStep = 50;
yBase = 800;

uicontrol(tab2, 'Style', 'text', ...
    'String', 'HARP Hybrid-millidecade Products', ...
    'Position', [100, 900, 600, 40], ...
    'FontSize', 14, 'FontWeight', 'bold', ...
    'BackgroundColor', bgColor, ...
    'ForegroundColor', textColor, ...
    'HorizontalAlignment', 'center');

% Input Directory
uicontrol(tab2, 'Style', 'text', 'String', 'Input Directory:', ...
    'Position', [30, yBase, 120, 25], ...
    'BackgroundColor', bgColor, 'ForegroundColor', textColor, ...
    'HorizontalAlignment', 'left', 'FontWeight', 'bold');

REMORA.mypsd.gui.inputDir = uicontrol(tab2, 'Style', 'edit', ...
    'Position', [160, yBase, 500, 28], 'HorizontalAlignment', 'left', ...
    'String', 'Y:\CINMS\CINMS_B_49\CINMS_B_49_disk01_df100');

uicontrol(tab2, 'Style', 'pushbutton', 'String', 'Browse', ...
    'Position', [670, yBase, 90, 28], ...
    'BackgroundColor', buttonColor, 'ForegroundColor', buttonFontColor, ...
    'FontWeight', 'bold', ...
    'Callback', @(~,~) set(REMORA.mypsd.gui.inputDir, 'String', uigetdir));

% Output Directory
yBase = yBase - yStep;
uicontrol(tab2, 'Style', 'text', 'String', 'Output Directory:', ...
    'Position', [30, yBase, 120, 25], ...
    'BackgroundColor', bgColor, 'ForegroundColor', textColor, ...
    'HorizontalAlignment', 'left', 'FontWeight', 'bold');

REMORA.mypsd.gui.outputDir = uicontrol(tab2, 'Style', 'edit', ...
    'Position', [160, yBase, 500, 28], 'HorizontalAlignment', 'left', ...
    'String', 'D:\HMD');

uicontrol(tab2, 'Style', 'pushbutton', 'String', 'Browse', ...
    'Position', [670, yBase, 90, 28], ...
    'BackgroundColor', buttonColor, 'ForegroundColor', buttonFontColor, ...
    'FontWeight', 'bold', ...
    'Callback', @(~,~) set(REMORA.mypsd.gui.outputDir, 'String', uigetdir));

% Transfer Function File
yBase = yBase - yStep;
uicontrol(tab2, 'Style', 'text', 'String', 'Transfer Function File:', ...
    'Position', [30, yBase, 120, 25], ...
    'BackgroundColor', bgColor, 'ForegroundColor', textColor, ...
    'HorizontalAlignment', 'left', 'FontWeight', 'bold');
REMORA.mypsd.gui.tfFilePath = uicontrol(tab2, 'Style', 'edit', ...
    'Position', [160, yBase, 500, 28], 'HorizontalAlignment', 'left', ...
    'String', 'G:\Shared drives\MBARC_TF\800-899\856\856_170215_B_HARP.tf');

uicontrol(tab2, 'Style', 'pushbutton', 'String', 'Browse', ...
    'Position', [670, yBase, 90, 28], ...
    'BackgroundColor', buttonColor, 'ForegroundColor', buttonFontColor, ...
    'FontWeight', 'bold', ...
    'Callback', @(~,~) select_tf_file_callback(REMORA.mypsd.gui.tfFilePath));

% Organization
yBase = yBase - yStep;
uicontrol(tab2, 'Style', 'text', 'String', 'Organization:', ...
    'Position', [30, yBase, 120, 25], ...
    'BackgroundColor', bgColor, 'ForegroundColor', textColor, ...
    'HorizontalAlignment', 'left', 'FontWeight', 'bold');

REMORA.mypsd.gui.organization = uicontrol(tab2, 'Style', 'edit', ...
    'Position', [160, yBase, 500, 28], 'HorizontalAlignment', 'left', ...
    'String', 'MBARC');

% Project
yBase = yBase - yStep;
uicontrol(tab2, 'Style', 'text', 'String', 'Project:', ...
    'Position', [30, yBase, 120, 25], ...
    'BackgroundColor', bgColor, 'ForegroundColor', textColor, ...
    'HorizontalAlignment', 'left', 'FontWeight', 'bold')

REMORA.mypsd.gui.project = uicontrol(tab2, 'Style', 'edit', ...
    'Position', [160, yBase, 500, 28], 'HorizontalAlignment', 'left', ...
    'String', 'CINMS');

% Site Name
yBase = yBase - yStep;
uicontrol(tab2, 'Style', 'text', 'String', 'Site Name:', ...
    'Position', [30, yBase, 120, 25], ...
    'BackgroundColor', bgColor, 'ForegroundColor', textColor, ...
    'HorizontalAlignment', 'left', 'FontWeight', 'bold');

REMORA.mypsd.gui.site = uicontrol(tab2, 'Style', 'edit', ...
    'Position', [160, yBase, 500, 28], 'HorizontalAlignment', 'left', ...
    'String', 'B');

% Start Frequency
yBase = yBase - yStep;
uicontrol(tab2, 'Style', 'text', 'String', 'Start Frequency (Hz)', ...
    'Position', [30, yBase, 90, 25], ...
    'BackgroundColor', bgColor, 'ForegroundColor', textColor, ...
    'HorizontalAlignment', 'left', 'FontWeight', 'bold');
REMORA.mypsd.gui.startFreq = uicontrol(tab2, 'Style', 'edit', ...
    'Position', [160, yBase, 90, 25], 'HorizontalAlignment', 'left', ...
    'String', '10');

% End Frequency
yBase = yBase - yStep;
uicontrol(tab2, 'Style', 'text', 'String', 'End Frequency (Hz)', ...
    'Position', [30, yBase, 90, 25], ...
    'BackgroundColor', bgColor, 'ForegroundColor', textColor, ...
    'HorizontalAlignment', 'left', 'FontWeight', 'bold');

REMORA.mypsd.gui.endFreq = uicontrol(tab2, 'Style', 'edit', ...
    'Position', [160, yBase, 90, 28], 'HorizontalAlignment', 'left', ...
    'String', '1000');



% Compute Button
uicontrol(tab2, 'Style', 'pushbutton', ...
    'String', 'Compute HMD', ...
    'Position', [330, 20, 140, 40], ...
    'BackgroundColor', [0.1, 0.4, 0.7], ...
    'ForegroundColor', buttonFontColor, ...
    'FontWeight', 'bold', 'FontSize', 11, ...
    'Callback', @mypsd_compute_callback);
end
