function ec_id_init_window

global REMORA

defaultPos = [0.25,0.25,0.3,0.2];
if isfield(REMORA.fig, 'ec')
    % check if the figure already exists. If so, don't move it.
    if isfield(REMORA.fig.ec, 'id_settings') && isvalid(REMORA.fig.ec.id_settings)
        defaultPos = get(REMORA.fig.ec.id_settings,'Position');
    else
        REMORA.fig.ec.id_settings = figure;
    end
else
    REMORA.fig.ec.id_settings = figure;
end

set(REMORA.fig.ec.id_settings,'NumberTitle','off', ...
    'Name','Make ID File from EchoDet Output',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on',...
    'ToolBar', 'none');

figure(REMORA.fig.ec.id_settings)

% button grid layouts
% 10 rows, 4 columns
r = 6; % rows      (extra space for separations btw sections)
c = 2;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;


% colors
bgColor = [1 1 1];  % white
bgColorGreen = [0.0 0.2 0.0];

REMORA.ec.id_verify = [];
%% Input folder
btnPos=[x(1)-w*.2 y(2)-2*ybuff w h];
loadFileStr = 'Input Folder';
REMORA.ec.id_verify.loadFileStr = uicontrol(REMORA.fig.ec.id_settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadFileStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

%actual input part
labelStr=num2str(REMORA.ec.id_params.inDir);
btnPos=[x(2)-w*0.55 y(2) w*1.4 h*.8];
REMORA.ec.id_verify.filePathTxt = uicontrol(REMORA.fig.ec.id_settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','ec_id_control(''setfilePath'')');

%% run on subfolders 
btnPos=[x(1)+w*0.3 y(3) w h];
loadFileStr = 'Run on subfolders';
REMORA.ec.id_verify.runonSub = uicontrol(REMORA.fig.ec.id_settings, ...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadFileStr,'Interpreter','tex'),...
    'Value',REMORA.ec.id_params.runonSub,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','ec_id_control(''runonSub'')');

%% output name
if REMORA.ec.id_params.runonSub
    showoutName = 'off';
    showPref = 'on';
else
    showoutName = 'on';
    showPref = 'off';
end

btnPos=[x(2)-w*.2 y(3)-2*ybuff w*0.5 h];
outFileStr = 'Output File Name';
REMORA.ec.id_verify.outFileStr = uicontrol(REMORA.fig.ec.id_settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(outFileStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible',showoutName);

%actual input part
labelStr=num2str(REMORA.ec.id_params.outName);
btnPos=[x(3)-w*0.7 y(3) w*0.5 h*.8];
REMORA.ec.id_verify.outFileTxt = uicontrol(REMORA.fig.ec.id_settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible',showoutName,...
    'Callback','ec_id_control(''setoutName'')');

%% input file prefix
btnPos=[x(1)-w*.2 y(4)-2*ybuff w h];
inPrefStr = 'Subfolder Prefix';
REMORA.ec.id_verify.inPrefStr = uicontrol(REMORA.fig.ec.id_settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(inPrefStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible',showPref);

%actual input part
labelStr=num2str(REMORA.ec.id_params.inPref);
btnPos=[x(2)-w*0.55 y(4) w h*.8];
REMORA.ec.id_verify.inPrefTxt = uicontrol(REMORA.fig.ec.id_settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible',showPref,...
    'Callback','ec_id_control(''setsubfolderPref'')');

%% output folder
btnPos=[x(1)-w*.2 y(5)-2*ybuff w h];
outFoldStr = 'Output Folder';
REMORA.ec.id_verify.outFoldStr = uicontrol(REMORA.fig.ec.id_settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(outFoldStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

%actual input part
labelStr=num2str(REMORA.ec.id_params.outDir);
btnPos=[x(2)-w*0.55 y(5) w h*.8];
REMORA.ec.id_verify.outFoldTxt = uicontrol(REMORA.fig.ec.id_settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','ec_id_control(''setoutFolder'')');
%% Run button
labelStr = 'Create ID file';
btnPos=[x(2)-w/2 y(6)-2*ybuff w h];

REMORA.ec.id_verify.runTxt = uicontrol(REMORA.fig.ec.id_settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorGreen,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.4,...
    'Visible','on',...
    'FontWeight','bold',...
    'ForegroundColor',bgColor,...
    'Callback','ec_id_control(''runIt'')');

