function ec_init_window

global REMORA


defaultPos = [0.25,0.25,0.38,0.5];
if isfield(REMORA.fig, 'ec')
    % check if the figure already exists. If so, don't move it.
    if isfield(REMORA.fig.ec, 'settings') && isvalid(REMORA.fig.ec.settings)
        defaultPos = get(REMORA.fig.ec.settings,'Position');
    else
        REMORA.fig.ec.settings = figure;
    end
else
    REMORA.fig.ec.settings = figure;
end

set(REMORA.fig.ec.settings,'NumberTitle','off', ...
    'Name','Run Echosounder Detector',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on',...
    'ToolBar', 'none');

figure(REMORA.fig.ec.settings)

% button grid layouts
% 10 rows, 4 columns
r = 13; % rows      (extra space for separations btw sections)
c = 5;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;


% colors
bgColor = [1 1 1];  % white
bgColorPink = [0.8 0 0];
bgColorOrange = [1.0 0.8 0.0];
bgColorGreen = [0.0 0.2 0.0];

REMORA.ec.ec_paramsHelp = ec_getHelp_strings;

REMORA.ec.ec_verify = [];
labelStr = 'Echosounder Detector Settings';
btnPos=[x(1) y(2)-ybuff 5*w h];
REMORA.ec.ec_verify.headtext = uicontrol(REMORA.fig.ec.settings, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');  %'BackgroundColor',bgColor3,...

btnPos=[x(1) y(3)+3*ybuff 5*w h*.6];
loadSaveStr = 'Load/Save Paths';
REMORA.ec.ec_verify.loadSaveTxt = uicontrol(REMORA.fig.ec.settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadSaveStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'ForegroundColor',bgColor,...
    'Visible','on',...
    'BackgroundColor',bgColorGreen);

%% Input folder
btnPos=[x(1) y(4)+2*ybuff w h];
loadFileStr = 'Input Folder';
REMORA.ec.ec_verify.loadFileStr = uicontrol(REMORA.fig.ec.settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadFileStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

%actual input part
labelStr=num2str(REMORA.ec.ec_params.dataFilePath);
btnPos=[x(2) y(4)+3*ybuff (w*4)*.95 h*.8];
REMORA.ec.ec_verify.filePathTxt = uicontrol(REMORA.fig.ec.settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','ec_control(''setfilePath'')');

%% output folder
btnPos=[x(1) y(4)-3*ybuff w h];
loadFileStr = 'Output Folder';
REMORA.ec.ec_verify.loadFileStr = uicontrol(REMORA.fig.ec.settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadFileStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

%actual output part
labelStr=num2str(REMORA.ec.ec_params.outDir);
btnPos=[x(2) y(4)-ybuff (w*4)*.95 h*.8];
REMORA.ec.ec_verify.outPathTxt = uicontrol(REMORA.fig.ec.settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','ec_control(''setoutPath'')');

%% template path
btnPos=[x(1) y(4)-7*ybuff w h];
loadFileStr = 'Echosounder Template';
REMORA.ec.ec_verify.loadFileStr = uicontrol(REMORA.fig.ec.settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadFileStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

%actual template part
labelStr=num2str(REMORA.ec.ec_params.templateFilePath);
btnPos=[x(2) y(4)-5*ybuff (w*4)*.95 h*.8];
REMORA.ec.ec_verify.tempPathTxt = uicontrol(REMORA.fig.ec.settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'TooltipString',sprintf(REMORA.ec.ec_paramsHelp.echTemp),...
    'Callback','ec_control(''settempPath'')');


%% TF path
btnPos=[x(1) y(4)-11*ybuff w h];
loadFileStr = 'Transfer Function';
REMORA.ec.ec_verify.loadFileStr = uicontrol(REMORA.fig.ec.settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadFileStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

%actual template part
labelStr=num2str(REMORA.ec.ec_params.TFpath);
btnPos=[x(2) y(4)-9*ybuff (w*4)*.95 h*.8];
REMORA.ec.ec_verify.TFpathTxt = uicontrol(REMORA.fig.ec.settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','ec_control(''setTFPath'')');

%% deployment name
btnPos=[x(1) y(4)-15*ybuff w h];
loadFileStr = 'Deployment Name';
REMORA.ec.ec_verify.loadFileStr = uicontrol(REMORA.fig.ec.settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadFileStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

%actual input part
labelStr=num2str(REMORA.ec.ec_params.depName);
btnPos=[x(2) y(4)-13*ybuff (w*4)*.95 h*.8];
REMORA.ec.ec_verify.depNameTxt = uicontrol(REMORA.fig.ec.settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'TooltipString',sprintf(REMORA.ec.ec_paramsHelp.depName),...
    'Callback','ec_control(''setdepName'')');

%% thresholds
btnPos=[x(1) y(8)+2*ybuff 5*w h*.6];
loadSaveStr = 'Thresholds';
REMORA.ec.ec_verify.loadSaveTxt = uicontrol(REMORA.fig.ec.settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadSaveStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on',...
    'ForegroundColor',bgColor,...
    'BackgroundColor',bgColorPink);

%% bandpass filter thresholds
btnPos=[x(1) y(9) w h];
loadFileStr = 'Low Frequency Cutoff (Hz)';
REMORA.ec.ec_verify.loadFileStr = uicontrol(REMORA.fig.ec.settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadFileStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

%actual input
labelStr=num2str(REMORA.ec.ec_params.lowF);
btnPos=[x(2) y(9)+2*ybuff w h*.8];
REMORA.ec.ec_verify.lowFTxt = uicontrol(REMORA.fig.ec.settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'TooltipString',sprintf(REMORA.ec.ec_paramsHelp.lowF),...
    'Callback','ec_control(''setLowF'')');

%high frequency cutoff
btnPos=[x(1) y(10)+ybuff w h];
loadFileStr = 'High Frequency Cutoff (Hz)';
REMORA.ec.ec_verify.loadFileStr = uicontrol(REMORA.fig.ec.settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadFileStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

%actual input
labelStr=num2str(REMORA.ec.ec_params.highF);
btnPos=[x(2) y(10)+3*ybuff w h*.8];
REMORA.ec.ec_verify.HighFTxt = uicontrol(REMORA.fig.ec.settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'TooltipString',sprintf(REMORA.ec.ec_paramsHelp.highF),...
    'Callback','ec_control(''setHighF'')');

%% correlation thresholds
btnPos=[x(1) y(11) w h];
loadFileStr = 'Corr Thresh(perc)';
REMORA.ec.ec_verify.loadFileStr = uicontrol(REMORA.fig.ec.settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadFileStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

%actual input
labelStr=num2str(REMORA.ec.ec_params.prcTh);
btnPos=[x(2) y(11)+2*ybuff w h*.8];
REMORA.ec.ec_verify.percThTxt = uicontrol(REMORA.fig.ec.settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'TooltipString',sprintf(REMORA.ec.ec_paramsHelp.prcTh),...
    'Callback','ec_control(''setprcTh'')');

%csq threshold
btnPos=[x(1) y(12)+ybuff w h];
loadFileStr = 'Corr Thresh (Csq Value)';
REMORA.ec.ec_verify.loadFileStr = uicontrol(REMORA.fig.ec.settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadFileStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

%actual input
labelStr=num2str(REMORA.ec.ec_params.thresholdC);
btnPos=[x(2) y(12)+3*ybuff w h*.8];
REMORA.ec.ec_verify.threshCTxt = uicontrol(REMORA.fig.ec.settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'TooltipString',sprintf(REMORA.ec.ec_paramsHelp.thresholdC),...
    'Callback','ec_control(''setthresholdC'')');

%% ICI thresholds
btnPos=[x(3)+w/2 y(9) w h];
loadFileStr = 'ICI Range (sec)';
REMORA.ec.ec_verify.loadFileStr = uicontrol(REMORA.fig.ec.settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadFileStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

%actual input
labelStr=num2str(REMORA.ec.ec_params.lowICI);
btnPos=[x(4)+w*0.6 y(9)+2*ybuff w/3 h*.8];
REMORA.ec.ec_verify.lowICITxt = uicontrol(REMORA.fig.ec.settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'TooltipString',sprintf(REMORA.ec.ec_paramsHelp.ICI_range),...
    'Callback','ec_control(''setICIlow'')');

%high
btnPos=[x(5) y(9) w/5 h];
loadFileStr = 'to';
REMORA.ec.ec_verify.loadFileStr = uicontrol(REMORA.fig.ec.settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadFileStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

%actual input
labelStr=num2str(REMORA.ec.ec_params.highICI);
btnPos=[x(5)+w*0.3 y(9)+2*ybuff w*0.3 h*.8];
REMORA.ec.ec_verify.highICITxt = uicontrol(REMORA.fig.ec.settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'Callback','ec_control(''setICIhigh'')');


%gap limitation
btnPos=[x(3)+w/2 y(10)+ybuff w h];
loadFileStr = 'ICI Mode Pad (sec)';
REMORA.ec.ec_verify.loadFileStr = uicontrol(REMORA.fig.ec.settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadFileStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

%actual input
labelStr=num2str(REMORA.ec.ec_params.ICIpad);
btnPos=[x(4)+w*0.6 y(10)+3*ybuff w h*.8];
REMORA.ec.ec_verify.ICIpadTxt = uicontrol(REMORA.fig.ec.settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'TooltipString',sprintf(REMORA.ec.ec_paramsHelp.ICIpad),...
    'Callback','ec_control(''setICIpad'')');

%% other settings- probably don't modify
btnPos=[x(3)+w/2 y(11) w h];
loadFileStr = 'Detection Gap (sec)';
REMORA.ec.ec_verify.loadFileStr = uicontrol(REMORA.fig.ec.settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadFileStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

%actual input
labelStr=num2str(REMORA.ec.ec_params.gapT);
btnPos=[x(4)+w*0.6 y(11)+2*ybuff w h*.8];
REMORA.ec.ec_verify.detgapTxt = uicontrol(REMORA.fig.ec.settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'TooltipString',sprintf(REMORA.ec.ec_paramsHelp.gapT),...
    'Callback','ec_control(''setDetgap'')');

% set threshold PP
btnPos=[x(3)+w/2 y(12)+ybuff w h];
loadFileStr = 'RL Threshold';
REMORA.ec.ec_verify.loadFileStr = uicontrol(REMORA.fig.ec.settings, ...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(loadFileStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

%actual input
labelStr=num2str(REMORA.ec.ec_params.threshPP);
btnPos=[x(4)+w*0.6 y(12)+3*ybuff w h*.8];
REMORA.ec.ec_verify.threshPPTxt = uicontrol(REMORA.fig.ec.settings,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'HorizontalAlignment','left',...
    'Visible','on',...
    'TooltipString',sprintf(REMORA.ec.ec_paramsHelp.threshPP),...
    'Callback','ec_control(''setthreshPP'')');

%% Run button
labelStr = 'Run Echosounder Detector';
btnPos=[x(2)+w/2 y(13)+ybuff w*2 h];

REMORA.ec.ec_verify.runTxt = uicontrol(REMORA.fig.ec.settings,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorOrange,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.4,...
    'Visible','on',...
    'FontWeight','bold',...
    'TooltipString',sprintf(REMORA.ec.ec_paramsHelp.runIt),...
    'Callback','ec_control(''runDetector'')');

