% Add main menu to Triton Remora
REMORA.mypsd.menu = uimenu(HANDLES.remmenu, ...
    'Label', 'Hybrid Millidecade Products');

% Add "Compute" submenu
REMORA.mypsd.compute = uimenu(REMORA.mypsd.menu, ...
    'Label', 'Compute', ...
    'Callback', 'mypsd_run(''compute'')');

% Add "Visualize" submenu
REMORA.mypsd.visualize = uimenu(REMORA.mypsd.menu, ...
    'Label', 'Visualize', ...
    'Callback', 'mypsd_run(''visualize'')');