% Add main menu to Triton Remora
REMORA.mypsd.menu = uimenu(HANDLES.remmenu, ...
    'Label', 'TriHyb');

% Add "Compute" submenu
REMORA.mypsd.compute = uimenu(REMORA.mypsd.menu, ...
    'Label', 'Compute HMD Products', ...
    'Callback', 'mypsd_run(''Compute HMD Products'')');
% 
% % Add "Visualize" submenu
% REMORA.mypsd.visualize = uimenu(REMORA.mypsd.menu, ...
%     'Label', 'Visualize HMD Products', ...
%     'Callback', 'mypsd_run(''Visualize HMD Products'')');