function bm_optimthresh_gui

global REMORA

defaultPos = [0.25, 0.25, 0.3, 0.3];
REMORA.fig.bm.thresh = figure(...
    'NumberTitle','off', ...
    'Name','Kernel calculator',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on');

% button grid layouts
% 3 rows, 2 columns
r = 8; % rows      (extra space for separations btw sections)
c = 2;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
xbuff = w*.1;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;

% colors
bgColor = [1 1 1];  % white
bgColorGrayLight = [.92 .92 .92];  % gray
bgColorGray = [.86 .86 .86];  % gray

REMORA.bm.thresh_verify = [];
labelStr = 'Calculate optimal threshold';
btnPos=[x(1) y(2) w*2 h];
REMORA.bm.thresh_verify.headtext = uicontrol(REMORA.fig.bm.thresh, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');

% Set paths and strings
%***********************************

% Input Folder Text
labelStr = 'Input Folder';
btnPos=[x(1)+xbuff  y(3) w dy];
REMORA.bm.thresh_verify.inDirTxt = uicontrol(REMORA.fig.bm.thresh,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Input Folder Editable Text
labelStr=num2str(REMORA.bm.settings.inDir);
btnPos=[x(2)-xbuff y(3) w dy];
REMORA.bm.thresh_verify.inDirEdTxt = uicontrol(REMORA.fig.bm.thresh,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_thresh_control(''setInDir'')');

% Output Folder Text
labelStr = 'Output Folder';
btnPos=[x(1)+xbuff  y(4) w dy];
REMORA.bm.thresh_verify.outDirTxt = uicontrol(REMORA.fig.bm.thresh,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Output Folder Editable Text
labelStr=num2str(REMORA.bm.settings.outDir);
btnPos=[x(2)-xbuff y(4) w dy];
REMORA.bm.thresh_verify.outDirEdTxt = uicontrol(REMORA.fig.bm.thresh,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_thresh_control(''setOutDir'')');

% Start frequency text
labelStr = 'Start frequencies';
btnPos =[x(1)+xbuff y(5) w*0.8 dy];
REMORA.bm.thresh_verify.SpeciesText = uicontrol(REMORA.fig.bm.thresh,...
     'Style','text',...
     'Units','normalized',...
     'HorizontalAlignment','left',...
     'Position',btnPos,...
     'String',sprintf(labelStr,'Interpreter','tex'),...
     'FontUnits','normalized',...
     'Visible','on');

%Start frequency 1 editable text
labelStr=num2str(REMORA.bm.settings.startF(1,1));
btnPos=[x(2)-xbuff y(5) w/5 dy];
REMORA.bm.thresh_verify.StartF1EdText = uicontrol(REMORA.fig.bm.thresh,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_thresh_control(''setStartF1'')');

%Start frequency 2 editable text
labelStr=num2str(REMORA.bm.settings.startF(1,2));
btnPos=[x(2)+xbuff*1.5 y(5) w/5 dy];
REMORA.bm.thresh_verify.StartF2EdText = uicontrol(REMORA.fig.bm.thresh,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_thresh_control(''setStartF2'')');
    
%Start frequency 3 editable text
labelStr=num2str(REMORA.bm.settings.startF(1,3));
btnPos=[x(2)+xbuff*4.25 y(5) w/5 dy];
REMORA.bm.thresh_verify.StartF3EdText = uicontrol(REMORA.fig.bm.thresh,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_thresh_control(''setStartF3'')');

%Start frequency 4 editable text
labelStr=num2str(REMORA.bm.settings.startF(1,4));
btnPos=[x(2)+xbuff*7 y(5) w/5 dy];
REMORA.bm.thresh_verify.StartF4EdText = uicontrol(REMORA.fig.bm.thresh,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_thresh_control(''setStartF4'')');

% End frequency text
labelStr = 'End frequencies';
btnPos =[x(1)+xbuff y(6) w*0.8 dy];
REMORA.bm.thresh_verify.SpeciesText = uicontrol(REMORA.fig.bm.thresh,...
     'Style','text',...
     'Units','normalized',...
     'HorizontalAlignment','left',...
     'Position',btnPos,...
     'String',sprintf(labelStr,'Interpreter','tex'),...
     'FontUnits','normalized',...
     'Visible','on');

%End frequency 1 editable text
labelStr=num2str(REMORA.bm.settings.endF(1,1));
btnPos=[x(2)-xbuff y(6) w/5 dy];
REMORA.bm.thresh_verify.EndF1EdText = uicontrol(REMORA.fig.bm.thresh,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_thresh_control(''setEndF1'')');

%End frequency 2 editable text
labelStr=num2str(REMORA.bm.settings.endF(1,2));
btnPos=[x(2)+xbuff*1.5 y(6) w/5 dy];
REMORA.bm.thresh_verify.EndF2EdText = uicontrol(REMORA.fig.bm.thresh,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_thresh_control(''setEndF2'')');

%End frequency 3 editable text
labelStr=num2str(REMORA.bm.settings.endF(1,3));
btnPos=[x(2)+xbuff*4.25 y(6) w/5 dy];
REMORA.bm.thresh_verify.EndF3EdText = uicontrol(REMORA.fig.bm.thresh,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_thresh_control(''setEndF3'')');

%End frequency 4 editable text
labelStr=num2str(REMORA.bm.settings.endF(1,4));
btnPos=[x(2)+xbuff*7 y(6) w/5 dy];
REMORA.bm.thresh_verify.EndF4EdText = uicontrol(REMORA.fig.bm.thresh,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_thresh_control(''setEndF4'')');

% Threshold range Text
labelStr = 'Threshold range';
btnPos=[x(1)+xbuff  y(7) w dy];
REMORA.bm.thresh_verify.rangeTxt = uicontrol(REMORA.fig.bm.thresh,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Threshold minimum Text
labelStr = 'From';
btnPos=[x(2)-xbuff*2  y(7)-ybuff w/5 dy];
REMORA.bm.thresh_verify.tminTxt = uicontrol(REMORA.fig.bm.thresh,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

%Threshold minimum Editible Text
labelStr=num2str(REMORA.bm.settings.tmin);
btnPos=[x(2)-xbuff*0.5 y(7) w/5 dy];
REMORA.bm.thresh_verify.tminEdTxt = uicontrol(REMORA.fig.bm.thresh,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_thresh_control(''setTMin'')');

% Threshold maximum Text
labelStr = 'To';
btnPos=[x(2)+xbuff*2  y(7)-ybuff w/5 dy];
REMORA.bm.thresh_verify.tmaxTxt = uicontrol(REMORA.fig.bm.thresh,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Threshold maximum Editable Text
labelStr=num2str(REMORA.bm.settings.tmax);
btnPos=[x(2)+xbuff*3 y(7) w/5 dy];
REMORA.bm.thresh_verify.tmaxEdTxt = uicontrol(REMORA.fig.bm.thresh,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_thresh_control(''setTMax'')');

% Stepsize Text
labelStr = 'Stepsize';
btnPos=[x(2)+xbuff*5  y(7)-ybuff w/5 dy];
REMORA.bm.thresh_verify.stsizeTxt = uicontrol(REMORA.fig.bm.thresh,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Stepsize Editable Text
labelStr=num2str(REMORA.bm.settings.stsize);
btnPos=[x(2)+xbuff*7 y(7) w/5 dy];
REMORA.bm.thresh_verify.stsizeEdTxt = uicontrol(REMORA.fig.bm.thresh,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_thresh_control(''setStSize'')');

% Run button
labelStr = 'Plot curve';
btnPos=[x(1)+1/2*w y(8) w h];
REMORA.bm.thresh_verify.RunCalcEdTxt = uicontrol(REMORA.fig.bm.thresh,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',[.47,.67,.19],...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','bm_thresh_control(''RunThreshCalc'')');
