function nn_ui_train_net_window(hObject,eventdata)

global REMORA

if ~isfield(REMORA.nn,'train_net')
    nn_ui_init_train_net
end

defaultPos = [0.35,.45,.3,.25];
initAxes = 0;
if isfield(REMORA.fig, 'nn')
    % check if the figure already exists. If so, don't move it.
    if isfield(REMORA.fig.nn, 'train_net') && isvalid(REMORA.fig.nn.train_net.figH)
        defaultPos = get(REMORA.fig.nn.train_net.figH,'Position');
    else
        initAxes = 1;
    end
else 
    initAxes = 1;
end

if initAxes
    REMORA.fig.nn.train_net.figH = figure;
    
    set(REMORA.fig.nn.train_net.figH,...
        'Units','normalized',...
        'ToolBar', 'none',...
        'MenuBar','none',...
        'NumberTitle','off','Name',...
        'Neural Net Tool - v1.0: Train Network',...
        'Position',defaultPos,...
        'Visible','on');
end

clf(REMORA.fig.nn.train_net.figH)

%% Title
labelStr = 'Network Design Options';
btnPos=[0 .9 1 .1];
REMORA.fig.nn.train_net.headText = uicontrol(REMORA.fig.nn.train_net.figH, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontSize',12,...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');

%% Not using: Bin or Det level checks 
% btnPos=[0 .8 1 .1];
% REMORA.fig.nn.train_net.backgrnd = uicontrol(REMORA.fig.nn.train_net.figH, ...
%     'Style','text', ...
%     'Units','normalized', ...
%     'HorizontalAlignment','Left',...
%     'Position',btnPos, ...
%     'BackgroundColor',[.68,.92,.1],...
%     'FontSize',11,...
%     'FontUnits','normalized', ...
%     'FontWeight','bold',...
%     'Visible','on');  
% 
% labelStr = '  Data Type: ';
% btnPos=[0.03 .8 .4 .08];
% REMORA.fig.nn.train_net.headText = uicontrol(REMORA.fig.nn.train_net.figH, ...
%     'Style','text', ...
%     'Units','normalized', ...
%     'HorizontalAlignment','Left',...
%     'Position',btnPos, ...
%     'BackgroundColor',[.68,.92,.1],...
%     'String',labelStr, ...
%     'FontSize',11,...
%     'FontUnits','normalized', ...
%     'FontWeight','bold',...
%     'Visible','on');  
% 
% %% Bin Level Text
% labelStr = 'Bin Level';
% btnPos=[.3 .8 .25 .1];
% REMORA.fig.nn.train_net.binCheckTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
%     'Style','checkbox',...
%     'Units','normalized',...
%     'Position',btnPos,...
%     'HorizontalAlignment','Right',...
%     'BackgroundColor',[.68,.92,.1],...
%     'String',sprintf(labelStr,'Interpreter','tex'),...
%     'FontWeight','bold',...
%     'FontSize',10,...
%     'FontUnits','normalized', ...
%     'Visible','on',...
%     'Callback',{@nn_ui_train_net_control,'setBinLevel'});
% 
% %% Click Level Text
% labelStr = 'Detection Level';
% btnPos=[.6 .8 .25 .1];
% REMORA.fig.nn.train_net.clickCheckTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
%     'Style','checkbox',...
%     'Units','normalized',...
%     'Position',btnPos,...
%     'HorizontalAlignment','Right',...
%     'BackgroundColor',[.68,.92,.1],...
%     'String',sprintf(labelStr,'Interpreter','tex'),...
%     'FontWeight','bold',...
%     'FontSize',10,...
%     'FontUnits','normalized', ...
%     'Visible','on',...
%     'Callback',{@nn_ui_train_net_control,'setClickLevel'});

%% Train File
labelStr = 'Train Data File';
btnPos=[.02 .73 .2 .1];
REMORA.fig.nn.train_net.trainFileTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','Right',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on');

btnPos=[.3 .77 .6 .08];
REMORA.fig.nn.train_net.trainFileEdTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'String',REMORA.nn.train_net.trainFile,...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@nn_ui_train_net_control,'setTrainFile'});

%% Test File Text
labelStr = 'Test Data File';
btnPos=[.02 .63 .2 .1];
REMORA.fig.nn.train_net.testFileTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','Right',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on');

btnPos=[.3 .67 .6 .08];
REMORA.fig.nn.train_net.testFileEdTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'String',REMORA.nn.train_net.testFile,...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@nn_ui_train_net_control,'setTestFile'});

%% Output Folder
labelStr = 'Output Folder';
btnPos=[.02 .53 .2 .1];
REMORA.fig.nn.train_net.outDirTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','Right',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on');

btnPos=[.3 .57 .6 .08];
REMORA.fig.nn.train_net.outDirEdTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'String',REMORA.nn.train_net.outDir,...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@nn_ui_train_net_control,'setOutDir'});

%% NNet Config Banner
btnPos=[0 .47 1 .07];
REMORA.fig.nn.train_net.configBanner = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','Center',...
    'BackgroundColor',[.93, .69,.13],...
    'String','Network Configuration',...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on');

%% Number of hidden layers
labelStr = 'Hidden Layers';
btnPos=[.02 .33 .25 .1];
REMORA.fig.nn.train_net.nHiddenTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','Right',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on');

btnPos=[.3 .37 .1 .08];
REMORA.fig.nn.train_net.nHiddenEdTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','center',...
    'String',REMORA.nn.train_net.nHiddenLayers,...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@nn_ui_train_net_control,'setNHidden'});

%% Layer size
labelStr = 'Hidden Layer Size';
btnPos=[.02 .23 .25 .1];
REMORA.fig.nn.train_net.hLayerSizeTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','Right',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on');

btnPos=[.3 .27 .1 .08];
REMORA.fig.nn.train_net.hLayerSizeEdTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','center',...
    'string',REMORA.nn.train_net.hLayerSize,...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@nn_ui_train_net_control,'setHiddenLayerSize'});

%% Batch Size
labelStr = 'Batch Size';
btnPos=[.52 .33 .2 .1];
REMORA.fig.nn.train_net.batchSizeTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','Right',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on');

btnPos=[.75 .37 .1 .08];
REMORA.fig.nn.train_net.batchSizeEdTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','center',...
    'string',REMORA.nn.train_net.batchSize,...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@nn_ui_train_net_control,'setBatchSize'});

%% Number of Epochs
labelStr = 'Epochs';
btnPos=[.52 .23 .2 .1];
REMORA.fig.nn.train_net.nEpochsTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','Right',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on');

btnPos=[.75 .27 .1 .08];
REMORA.fig.nn.train_net.nEpochsEdTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','center',...
    'string',REMORA.nn.train_net.nEpochs,...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@nn_ui_train_net_control,'setNEpochs'});

%% Dropout Probability
labelStr = 'Dropout Rate';
btnPos=[.02 .13 .25 .1];
REMORA.fig.nn.train_net.dropoutTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','Right',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on');

btnPos = [.3 .17 .1 .08];
REMORA.fig.nn.train_net.dropoutEdTxt = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','center',...
    'string',REMORA.nn.train_net.dropout,...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@nn_ui_train_net_control,'setDropout'});

btnPos = [.4 .07 .2 .1];
REMORA.fig.nn.train_net.runBtn = uicontrol(REMORA.fig.nn.train_net.figH,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',[.68,.92,0],...
    'HorizontalAlignment','center',...
    'string','Run',...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@nn_ui_train_net_control,'Run'});

figure(REMORA.fig.nn.train_net.figH)

function nn_ui_init_train_net
global REMORA

if isfield(REMORA.nn,'train_test_set')
    % should make this change with bin vs det modes
    if isfield(REMORA.nn.train_test_set,'savedTrainFile_bin')
        REMORA.nn.train_net.trainFile = REMORA.nn.train_test_set.savedTrainFile_bin;
        REMORA.nn.train_net.testFile = REMORA.nn.train_test_set.savedTestFile_bin;
    else
        REMORA.nn.train_net.trainFile = '';
        REMORA.nn.train_net.testFile = '';
    end
else
    REMORA.nn.train_net.trainFile  = '';
    REMORA.nn.train_net.testFile  = '';
end

REMORA.nn.train_net.outDir = '';
REMORA.nn.train_net.nHiddenLayers = 4;
REMORA.nn.train_net.hLayerSize = 128;
REMORA.nn.train_net.batchSize = 50;
REMORA.nn.train_net.nEpochs = 15;
REMORA.nn.train_net.dropout = 50;