function nn_ui_post_classification_window


global REMORA
% Shows some options for things you can do with clusters after you are
% done.
% if ~isfield(REMORA.nn,'CC') || ~isfield(REMORA.ct.CC,'output')
%     warning('No composite clusters loaded')
%     ct_load_composite_clusters
% end

initAxes = 0;
default_pos = [.25,.35,.2,.4];
if isfield(REMORA.fig, 'nn')
    % check if the figure already exists. If so, don't move it.
    if isfield(REMORA.fig.nn, 'nn_post_class') && isvalid(REMORA.fig.nn.nn_post_class)
        defaultPos = get(REMORA.fig.nn.nn_post_class,'Position');
    else
        initAxes = 1;
    end
else
    initAxes = 1;
end

if initAxes
    REMORA.fig.nn.nn_post_class = figure;
    
    set(REMORA.fig.nn.nn_post_class,...
        'Units','normalized','Position',default_pos,...
        'ToolBar', 'none',...
        'MenuBar','none',...
        'NumberTitle','off','Name',...
        'Neural Net Tool - v1.0: Post-Classification',...
        'Visible','on');
end

figure(REMORA.fig.nn.nn_post_class)
clf
currentH = REMORA.fig.nn.nn_post_class;
t1 = uicontrol(currentH,'Style','text',...
    'String','Post-Classification Actions',...
    'Units','normalized',...
    'Position',[0.1,.85,.8,.1],...
    'HandleVisibility','on',...
    'Visible','on',...
    'FontSize',11);

bg = uibuttongroup(currentH,'Visible','on',...
    'Position',[0.02 0.02 .96 .85],...
    'Units','normalized',...
    'SelectionChangeFcn',@bselection);

b1 = uicontrol(bg,'Style','pushbutton',...
    'String','Export Labels for Tethys',...
    'Units','normalized',...
    'Position',[0.1 .9 .8 .1],...
    'HandleVisibility','off',...
    'FontSize',10,...
    'Visible','off',...
    'Callback',@nn_ui_export_to_Tethys);

b2 = uicontrol(bg,'Style','pushbutton',...
    'String','Export DetEdit Labels',...
    'Units','normalized',...
    'Position',[0.1 .78 .8 .1],...
    'HandleVisibility','off',...
    'FontSize',10,...
    'Callback',@nn_ui_export_zID);

b3 = uicontrol(bg,'Style','pushbutton',...
    'String','Convert DetEdit to Tethys Format',...
    'Units','normalized',...
    'Position',[0.1 .66 .8 .1],...
    'HandleVisibility','off',...
    'FontSize',10,...
    'Visible','off',...
    'Callback',@nn_ui_zID_to_Tethys);



bg.Visible = 'on';


