function nn_ui_train_test_from_TPWS(hObject,eventdata)

% Set up a gui for making training and test sets from labeled TPWS files
% rather than unsupervised approach.

global REMORA

if ~isfield(REMORA.nn,'train_test_set_TPWS')
    nn_ui_init_train_test_set_TPWS
end

defaultPos = [0.35,.45,.3,.25];
initAxes = 0;
if isfield(REMORA.fig, 'nnTPWS')
    % check if the figure already exists. If so, don't move it.
    if isfield(REMORA.fig.nn, 'nn_train_test_set_TPWS') && isvalid(REMORA.fig.nn.nn_train_test_set_TPWS.figH)
        defaultPos = get(REMORA.fig.nn.nn_train_test_set_TPWS.figH,'Position');
    else
        initAxes = 1;
    end
else 
    initAxes = 1;
end



if initAxes
    REMORA.fig.nn.nn_train_test_set_TPWS.figH = figure;
    
    set(REMORA.fig.nn.nn_train_test_set_TPWS.figH,...
        'Units','normalized',...
        'ToolBar', 'none',...
        'MenuBar','none',...
        'NumberTitle','off','Name',...
        'Neural Net Tool - v1.0: Train/Test Set from TPWS options',...
        'Position',defaultPos,...
        'Visible','on');
end

clf


% Title
labelStr = 'Make Train and Test Sets from Manual Labels';
btnPos=[0 .9 1 .1];
REMORA.fig.nn.nn_train_test_set_TPWS.headText = uicontrol(REMORA.fig.nn.nn_train_test_set_TPWS.figH, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontSize',12,...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');  %'BackgroundColor',bgColor3,...


%% Input Folder Text
labelStr = 'Input Base Folder';
btnPos=[.02 .63 .25 .1];
REMORA.fig.nn.nn_train_test_set_TPWS.inDirTxt = uicontrol(REMORA.fig.nn.nn_train_test_set_TPWS.figH,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','Right',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on');

btnPos=[.3 .67 .6 .08];
REMORA.fig.nn.nn_train_test_set_TPWS.inDirEdTxt = uicontrol(REMORA.fig.nn.nn_train_test_set_TPWS.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'String',REMORA.nn.nn_train_test_set_TPWS.inDir,...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@nn_ui_train_test_set_control,'setInDirTPWS'});

%% Output Folder Text
labelStr = 'Output Folder';
btnPos=[.02 .53 .25 .1];
REMORA.fig.nn.nn_train_test_set_TPWS.saveDirTxt = uicontrol(REMORA.fig.nn.nn_train_test_set_TPWS.figH,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','Right',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on');

btnPos=[.3 .57 .6 .08];
REMORA.fig.nn.nn_train_test_set_TPWS.saveDirEdTxt = uicontrol(REMORA.fig.nn.nn_train_test_set_TPWS.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'String',REMORA.nn.nn_train_test_set_TPWS.outDir,...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@nn_ui_train_test_set_control,'setSaveDirTPWS'});

%% Output File Name Text
labelStr = 'Output File Name';
btnPos=[.02 .43 .25 .1];
REMORA.fig.nn.nn_train_test_set_TPWS.saveNameTxt = uicontrol(REMORA.fig.nn.nn_train_test_set_TPWS.figH,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','Right',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on');

btnPos=[.3 .47 .3 .08];
REMORA.fig.nn.nn_train_test_set.saveNameEdTxt = uicontrol(REMORA.fig.nn.nn_train_test_set.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','left',...
    'String',REMORA.nn.train_test_set.saveName,...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@nn_ui_train_test_set_control,'setSaveNameTPWS'});

% trainPercent

%% Training Percentage Text
labelStr = '%% of Dataset for Training';
btnPos=[.02 .33 .25 .1];
REMORA.fig.nn.nn_train_test_set.trainPercTxt = uicontrol(REMORA.fig.nn.nn_train_test_set.figH,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','Right',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on');

btnPos = [.3 .37 .1 .08];
REMORA.fig.nn.nn_train_test_set.trainPercEdTxt = uicontrol(REMORA.fig.nn.nn_train_test_set.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','center',...
    'string',num2str(REMORA.nn.train_test_set.trainPerc),...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@nn_ui_train_test_set_control,'setTrainPercTPWS'});

%% Number of training examples 
labelStr = 'Max Training Set Size';
btnPos=[.45 .33 .17 .1];
REMORA.fig.nn.nn_train_test_set.trainSizeTxt = uicontrol(REMORA.fig.nn.nn_train_test_set.figH,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','Right',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on');

btnPos = [.65 .37 .1 .08];
REMORA.fig.nn.nn_train_test_set_TPWS.trainSizeEdTxt = uicontrol(REMORA.fig.nn.nn_train_test_set_TPWS.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','center',...
    'string',num2str(REMORA.nn.nn_train_test_set_TPWS.trainSize),...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@nn_ui_train_test_set_control,'setTrainSizeTPWS'});

%% Bout Gap 
labelStr = 'Bout Gap (minutes)';
btnPos=[.02 .23 .25 .1];
REMORA.fig.nn.nn_train_test_set_TPWS.boutGapTxt = uicontrol(REMORA.fig.nn.nn_train_test_set_TPWS.figH,...
    'Style','text',...
    'Units','normalized',...
    'Position',btnPos,...
    'HorizontalAlignment','Right',...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on');

btnPos = [.3 .27 .1 .08];
REMORA.fig.nn.nn_train_test_set_TPWS.boutGapEdTxt = uicontrol(REMORA.fig.nn.nn_train_test_set_TPWS.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor','white',...
    'HorizontalAlignment','center',...
    'string',num2str(REMORA.nn.train_test_set.boutGap),...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback',{@nn_ui_train_test_set_control,'setBoutGapTPWS'});

REMORA.fig.nn.nn_train_test_set_TPWS.runButton = uicontrol(REMORA.fig.nn.nn_train_test_set_TPWS.figH,...
    'Style','pushbutton',...
    'String','Run',...
    'Units','normalized',...
    'Position',[.3 .07 .4 .1],...
    'HandleVisibility','off',...
    'FontSize',10,...
    'Callback',{@nn_ui_train_test_set_control,'RunTPWS'});

function nn_ui_init_train_test_set_TPWS
global REMORA
REMORA.nn.nn_train_test_set_TPWS.inDir = '';
REMORA.nn.nn_train_test_set_TPWS.outDir = '';
REMORA.nn.nn_train_test_set_TPWS.saveName = '';
REMORA.nn.nn_train_test_set_TPWS.trainPerc = 66;
REMORA.nn.nn_train_test_set_TPWS.trainSize = 1000;
REMORA.nn.nn_train_test_set_TPWS.boutGap = 15;