function nnHelpStrings = nn_ui_get_help_strings

nnHelpStrings.dataType = ['Neural nets can be trained to classify binned detections or\n',...
                        'individual detections.  Bin-level classifications are typically\n',... 
                        'more accurate but they will not give you a label for every single\n',... 
                        'detection.'];
nnHelpStrings.baseDir = ['Base folder containing directory structure of files to use for\n',... 
                         'training and testing. See online wiki for details on expected\n',... 
                         'file structure.'];
nnHelpStrings.outDir  = 'Folder where output files should be saved';
nnHelpStrings.saveName = ['String to use when naming output files. You may end up with\n',... 
                          'multiple versions of training and test data, so pick something\n',... 
                          'that will remind you of the parameters you used in this case.'];

nnHelpStrings.trainPerc = ['What percentage of the data should be used for training purposes?\n',...
                           'The remainder will be used for testing. More training data gives the\n',...
                           'network more to learn from, but less testing data means poorer\n',...
                           'estimation of how the network will perform on novel data.'];
nnHelpStrings.trainSize = ['Maximum number of events (bins or detections as appropriate) to aggregate\n',... 
                           'for each data type. Currently one training file and one testing file are\n',...
                           'saved, therefore consider the maximum file size your computer can handle.\n',... 
                           'For reference 2 million 200-sample detections create a 5GB file.\n',...
                           'See the online wiki for further info.\n'];
                        
nnHelpStrings.boutGap = ['Minimum time gap between detections in minutes required for\n',...  
                        'two encounters to be considered independent events.'];