function nn_ui_classify_window

global REMORA

if ~isfield(REMORA.nn, 'classify')
    REMORA.nn.classify = [];
end
defaultPos = [0.35,.45,.3,.25];
initAxes = 0;
if isfield(REMORA.fig, 'nn')
    % check if the figure already exists. If so, don't move it.
    if isfield(REMORA.fig.nn, 'classify') && isvalid(REMORA.fig.nn.classify.figH)
        defaultPos = get(REMORA.fig.nn.classify.figH,'Position');
    else
        initAxes = 1;
    end
else
    initAxes = 1;
end

if initAxes
    REMORA.fig.nn.classify.figH = figure;
    
    set(REMORA.fig.nn.classify.figH,...
        'Units','normalized',...
        'ToolBar', 'none',...
        'MenuBar','none',...
        'NumberTitle','off','Name',...
        'Neural Net Tool - v1.0: Classify',...
        'Position',defaultPos,...
        'Visible','on');
else
    clf(REMORA.fig.nn.classify.figH)
end

%% button grid layouts
% 14 rows, 4 columns
r = 15; % rows      (extra space for separations btw sections)
c = 4;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;

% colors
bgColor = [1 1 1];  % white
bgColorRed = [1 .6 .6];  % red
bgColorGray = [.86 .86 .86];  % gray
bgColor3 = [.47 .67 .19]; % a green
bgColor4 = [.76 .87 .78]; % light blue

%% Title
labelStr = 'Classification Options';
btnPos=[0 .9 1 .1];

REMORA.fig.nn.classify.headText = uicontrol(REMORA.fig.nn.classify.figH, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontSize',12,...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');

btnPos=[x(1) y(4) w*4 dy*2];
REMORA.fig.nn.classify.bg = uibuttongroup('Visible','on',...
    'Position',btnPos,...
    'BorderType','etchedin');%'SelectionChangedFcn',{@ct_cc_control},...


if ~isfield(REMORA.nn.classify,'binsTF')
    REMORA.nn.classify.binsTF = 1;
end
% Create 2 radio buttons in the button group.
btnPos=[0.25,0 .4 1];
REMORA.fig.nn.classify.bg_r1 = uicontrol(REMORA.fig.nn.classify.bg ,'Style','radiobutton',...
    'Units','normalized',...
    'String','Bins',...
    'Position',btnPos,...
    'HandleVisibility','on',...
    'Value',REMORA.nn.classify.binsTF,...
    'Callback','nn_ui_classify_control(''setBinTF'')');

REMORA.nn.classify.detsTF = ~REMORA.nn.classify.binsTF;
if REMORA.nn.classify.binsTF
    REMORA.fig.nn.classify.binsVisible = 'on';
    REMORA.fig.nn.classify.detsVisible = 'off';
else
    REMORA.fig.nn.classify.binsVisible = 'off';
    REMORA.fig.nn.classify.detsVisible = 'on';
end
btnPos=[0.6,0 .4 1];
REMORA.fig.nn.classify.bg_r2 = uicontrol(REMORA.fig.nn.classify.bg ,'Style','radiobutton',...
    'Units','normalized',...
    'String','Detections',...
    'Position',btnPos,...
    'HandleVisibility','on',...
    'Value',REMORA.nn.classify.detsTF,...
    'Callback','nn_ui_classify_control(''setDetTF'')');

%If bin: "Location of 'Cluster Bins' output"
if strcmp(REMORA.fig.nn.classify.binsVisible,'on')
    REMORA.nn.classify.inDirTxt = 'Location of ''Cluster Bins'' output:';
else
    REMORA.nn.classify.inDirTxt = 'Location of TPWS files:';
end

btnPos=[x(1)+w/8 y(5)-ybuff 3*w h];
REMORA.fig.nn.classify.inDirTxt = uicontrol(REMORA.fig.nn.classify.figH,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(REMORA.nn.classify.inDirTxt,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

if ~isfield(REMORA.nn.classify,'inDir')
    REMORA.nn.classify.inDir = 'C:\';
end
btnPos=[x(1)+w/4 y(6) .85 h];
REMORA.fig.nn.classify.inDirEdTxt = uicontrol(REMORA.fig.nn.classify.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',REMORA.nn.classify.inDir,...
    'HorizontalAlignment','left',...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_classify_control(''setInDir'')');

if ~isfield(REMORA.fig.nn,'searchIcon')
    REMORA.fig.nn.searchIcon = nn_ui_search_icon;
end

btnPos=[.92 y(6) w/5 h];
REMORA.fig.nn.classify.inDirPathBtn = uicontrol(REMORA.fig.nn.classify.figH,...
    'Style','pushbutton',...
    'Units','normalized',...
    'CData',REMORA.fig.nn.searchIcon,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_classify_control(''selectInDir'')');%   'BackgroundColor',bgColor3,...


if ~isfield(REMORA.nn.classify,'searchSubDirsTF')
    REMORA.nn.classify.searchSubDirsTF = 0;
end
%Search subfolders checkbox?
labelStr = 'Search subfolders';
btnPos=[x(1)+w/4 y(7) w*2 dy];
REMORA.fig.nn.classify.searchSubDirsCheck = uicontrol(REMORA.fig.nn.classify.figH,...
    'Style','checkbox',...
    'Units','normalized',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'Value',REMORA.nn.classify.searchSubDirsTF,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_classify_control(''setSearchSubDirsTF'')');

btnPos=[.35 y(7)-ybuff 3*w h];
REMORA.fig.nn.classify.wildcardTxt = uicontrol(REMORA.fig.nn.classify.figH,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String','Filename Wildcard (optional)',...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

if ~isfield(REMORA.nn.classify,'wildcard')
    REMORA.nn.classify.wildcard = '';
end
btnPos=[.65 y(7) .262 h];
REMORA.fig.nn.classify.wildcardEdTxt = uicontrol(REMORA.fig.nn.classify.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',REMORA.nn.classify.wildcard,...
    'HorizontalAlignment','left',...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_classify_control(''setWildcard'')');


%Location of network to use
btnPos=[x(1)+w/8 y(9) 3*w h];
REMORA.fig.nn.classify.networkPathTxt = uicontrol(REMORA.fig.nn.classify.figH,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String','Trained Network File Path:',...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

btnPos=[.92 y(10) w/5 h];
REMORA.fig.nn.classify.networkPathBtn = uicontrol(REMORA.fig.nn.classify.figH,...
    'Style','pushbutton',...
    'Units','normalized',...
    'CData',REMORA.fig.nn.searchIcon,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_classify_control(''selectNetworkPath'')');%   'BackgroundColor',bgColor3,...

if ~isfield(REMORA.nn.classify,'networkPath')
    REMORA.nn.classify.networkPath = [];
end
btnPos=[x(1)+w/4 y(10) .85 h];
REMORA.fig.nn.classify.networkPathEdTxt = uicontrol(REMORA.fig.nn.classify.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',REMORA.nn.classify.networkPath,...
    'HorizontalAlignment','left',...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_classify_control(''setNetworkPath'')');

%Location to save labels
btnPos=[x(1)+w/8 y(12)-ybuff 3*w h];
REMORA.fig.nn.classify.saveDirTxt = uicontrol(REMORA.fig.nn.classify.figH,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String','Output Folder:',...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

if ~isfield(REMORA.nn.classify,'saveDir')
    REMORA.nn.classify.saveDir = 'C:\';
end

btnPos=[x(1)+w/4 y(13) .85 h];
REMORA.fig.nn.classify.saveDirEdTxt = uicontrol(REMORA.fig.nn.classify.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',REMORA.nn.classify.saveDir,...
    'HorizontalAlignment','left',...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_classify_control(''setSaveDir'')');

btnPos=[.92 y(13) w/5 h];
REMORA.fig.nn.classify.saveDirBtn = uicontrol(REMORA.fig.nn.classify.figH,...
    'Style','pushbutton',...
    'Units','normalized',...
    'CData',REMORA.fig.nn.searchIcon,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_classify_control(''selectSaveDir'')');%   'BackgroundColor',bgColor3,...

btnPos=[.4 y(15) .2 h*1.15];
REMORA.fig.nn.classify.runBtn = uicontrol(REMORA.fig.nn.classify.figH,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor3,...
    'String','Run',...
    'FontUnits','normalized', ...
    'FontSize',.8,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','nn_ui_classify_control(''Run'')');


figure(REMORA.fig.nn.classify.figH);