function nn_ui_export_to_Tethys

% if bin: need to iterate through bin files

global REMORA

if ~isfield(REMORA.nn, 'exportToTethys')
    REMORA.nn.exportToTethys = [];
end
defaultPos = [0.35,.45,.3,.4];
initAxes = 0;
if isfield(REMORA.fig, 'nn')
    % check if the figure already exists. If so, don't move it.
    if isfield(REMORA.fig.nn, 'exportToTethys') && isvalid(REMORA.fig.nn.exportToTethys.figH)
        defaultPos = get(REMORA.fig.nn.exportToTethys.figH,'Position');
    else
        initAxes = 1;
    end
else
    initAxes = 1;
end

% need one spreadsheet for each deployment.

% need to get effort info

% specify effort manually


if initAxes
    REMORA.fig.nn.exportToTethys.figH = figure;
    
    set(REMORA.fig.nn.exportToTethys.figH,...
        'Units','normalized',...
        'ToolBar', 'none',...
        'MenuBar','none',...
        'NumberTitle','off','Name',...
        'Neural Net Tool - v1.0: Export to Tethys',...
        'Position',defaultPos,...
        'Visible','on');
else
    clf(REMORA.fig.nn.exportToTethys.figH)
end

%% button grid layouts
% 14 rows, 4 columns
r = 20; % rows      (extra space for separations btw sections)
c = 4;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;

% colors
bgColor = [1 1 1];  % white
bgColorRed = [1 .6 .6];  % red
bgColorGray = [.86 .86 .86];  % gray
bgColor3 = [.68,.92,0]; % a green
bgColor4 = [.75 .875 1]; % light blue 

%% Title
labelStr = 'Export Network Labels to Tethys Format';
btnPos=[0 .9 1 .1];

REMORA.fig.nn.exportToTethys.headText = uicontrol(REMORA.fig.nn.exportToTethys.figH, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontSize',12,...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');

btnPos=[x(1) y(4) w*4 dy*2];
REMORA.fig.nn.exportToTethys.bg = uibuttongroup('Visible','on',...
    'Position',btnPos,...
    'BorderType','etchedin');%'SelectionChangedFcn',{@ct_cc_control},...


if ~isfield(REMORA.nn.exportToTethys,'binsTF')
    REMORA.nn.exportToTethys.binsTF = 1;
end
% Create 2 radio buttons in the button group.
btnPos=[0.25,0 .4 1];
REMORA.fig.nn.exportToTethys.bg_r1 = uicontrol(REMORA.fig.nn.exportToTethys.bg ,'Style','radiobutton',...
    'Units','normalized',...
    'String','Bins',...
    'Position',btnPos,...
    'HandleVisibility','on',...
    'Value',REMORA.nn.exportToTethys.binsTF,...
    'Callback','nn_ui_exportToTethys_control(''setBinTF'')');

REMORA.nn.exportToTethys.detsTF = ~REMORA.nn.exportToTethys.binsTF;
if REMORA.nn.exportToTethys.binsTF
    REMORA.fig.nn.exportToTethys.binsVisible = 'on';
    REMORA.fig.nn.exportToTethys.detsVisible = 'off';
else
    REMORA.fig.nn.exportToTethys.binsVisible = 'off';
    REMORA.fig.nn.exportToTethys.detsVisible = 'on';
end

btnPos=[0.6,0 .4 1];
REMORA.fig.nn.exportToTethys.bg_r2 = uicontrol(REMORA.fig.nn.exportToTethys.bg ,'Style','radiobutton',...
    'Units','normalized',...
    'String','Detections',...
    'Position',btnPos,...
    'HandleVisibility','on',...
    'Value',REMORA.nn.exportToTethys.detsTF,...
    'Callback','nn_ui_exportToTethys_control(''setDetTF'')');

%If bin: "Location of 'Cluster Bins' output"
if strcmp(REMORA.fig.nn.exportToTethys.binsVisible,'on')
    REMORA.nn.exportToTethys.inDirTxt = 'Folder of Network Classifications (bin):';
else
    REMORA.nn.exportToTethys.inDirTxt = 'Folder of Network Classifications (det):';
end


btnPos=[x(1)+w/8 y(5)-ybuff 3*w h];
REMORA.fig.nn.exportToTethys.inDirTxt = uicontrol(REMORA.fig.nn.exportToTethys.figH,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(REMORA.nn.exportToTethys.inDirTxt,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

if ~isfield(REMORA.nn.exportToTethys,'inDir')
    REMORA.nn.exportToTethys.inDir = 'C:\';
end

btnPos=[x(1)+w/4 y(6) .85 h];
REMORA.fig.nn.exportToTethys.inDirEdTxt = uicontrol(REMORA.fig.nn.exportToTethys.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',REMORA.nn.exportToTethys.inDir,...
    'HorizontalAlignment','left',...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_exportToTethys_control(''setInDir'')');


if ~isfield(REMORA.fig.nn,'searchIcon')
    REMORA.fig.nn.searchIcon = nn_ui_search_icon;
end

btnPos=[.92 y(6) w/5 h];
REMORA.fig.nn.exportToTethys.inDirPathBtn = uicontrol(REMORA.fig.nn.exportToTethys.figH,...
    'Style','pushbutton',...
    'Units','normalized',...
    'CData',REMORA.fig.nn.searchIcon,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_exportToTethys_control(''selectInDir'')');%   'BackgroundColor',bgColor3,...

%% Optional wildcard
btnPos=[.35 y(7)-ybuff 3*w h];
REMORA.fig.nn.exportToTethys.wildcardTxt = uicontrol(REMORA.fig.nn.exportToTethys.figH,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String','Filename Wildcard (optional)',...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

if ~isfield(REMORA.nn.exportToTethys,'wildcard')
    REMORA.nn.exportToTethys.wildcard = '';
end
btnPos=[.65 y(7) .262 h];
REMORA.fig.nn.exportToTethys.wildcardEdTxt = uicontrol(REMORA.fig.nn.exportToTethys.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',REMORA.nn.exportToTethys.wildcard,...
    'HorizontalAlignment','left',...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_exportToTethys_control(''setWildcard'')');

%% Location to save spreadsheet
btnPos=[x(1)+w/8 y(8)-ybuff 3*w h];
REMORA.fig.nn.exportToTethys.saveDirTxt = uicontrol(REMORA.fig.nn.exportToTethys.figH,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String','Output Folder:',...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

if ~isfield(REMORA.nn.exportToTethys,'saveDir')
    if isfield(REMORA.nn,'classify') && isfield(REMORA.nn.classify,'saveDir')
        REMORA.nn.exportToTethys.saveDir = REMORA.nn.classify.saveDir;
    else
        REMORA.nn.exportToTethys.saveDir = 'C:\';
    end
end

btnPos=[x(1)+w/4 y(9) .85 h];
REMORA.fig.nn.exportToTethys.saveDirEdTxt = uicontrol(REMORA.fig.nn.exportToTethys.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',REMORA.nn.exportToTethys.saveDir,...
    'HorizontalAlignment','left',...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_exportToTethys_control(''setSaveDir'')');

btnPos=[.92 y(9) w/5 h];
REMORA.fig.nn.exportToTethys.saveDirBtn = uicontrol(REMORA.fig.nn.exportToTethys.figH,...
    'Style','pushbutton',...
    'Units','normalized',...
    'CData',REMORA.fig.nn.searchIcon,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_exportToTethys_control(''selectSaveDir'')');%   'BackgroundColor',bgColor3,...

%% Name to give spreadsheet
btnPos=[x(1)+w/8 y(10)-ybuff 3*w h];
REMORA.fig.nn.exportToTethys.saveNameTxt = uicontrol(REMORA.fig.nn.exportToTethys.figH,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String','Output File Name:',...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

if ~isfield(REMORA.nn.exportToTethys,'saveName')
    REMORA.nn.exportToTethys.saveName = '';
end

btnPos=[x(1)+w/4 y(11) .85 h];
REMORA.fig.nn.exportToTethys.saveNameEdTxt = uicontrol(REMORA.fig.nn.exportToTethys.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',REMORA.nn.exportToTethys.saveName,...
    'HorizontalAlignment','left',...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_exportToTethys_control(''setSaveName'')');

%% Metadata
labelStr = 'Enter Deployment Metadata';
btnPos=[0 y(14) 1 .05];

REMORA.fig.nn.exportToTethys.headText = uicontrol(REMORA.fig.nn.exportToTethys.figH, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'String',labelStr, ...
    'FontSize',10,...
    'FontUnits','normalized', ...
    'BackgroundColor',bgColor4,...
    'FontWeight','bold',...
    'Visible','on');

%% Metadata: User ID
bgColor5 = [.93 .69 .13]; % orange
btnPos=[x(1) y(15)-ybuff w h-ybuff];
REMORA.fig.nn.exportToTethys.userIDTxt = uicontrol(REMORA.fig.nn.exportToTethys.figH,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','center',...
    'Position',btnPos,...
    'String','User ID',...
    'BackgroundColor',bgColor5,...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

if ~isfield(REMORA.nn.exportToTethys,'userID')
    REMORA.nn.exportToTethys.userID = '';
end

btnPos=[x(2) y(15)-ybuff w h-ybuff];
REMORA.fig.nn.exportToTethys.userIDEdTxt = uicontrol(REMORA.fig.nn.exportToTethys.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',REMORA.nn.exportToTethys.userID,...
    'HorizontalAlignment','left',...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_exportToTethys_control(''setUserID'')');

%% Metadata: Project
btnPos=[x(1) y(16)-ybuff w h-ybuff];
REMORA.fig.nn.exportToTethys.projectTxt = uicontrol(REMORA.fig.nn.exportToTethys.figH,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','center',...
    'Position',btnPos,...
    'String','Project',...
    'BackgroundColor',bgColor5,...
    'FontUnits','normalized', ...
    'Visible','on');%   'BackgroundColor',bgColor3,...

if ~isfield(REMORA.nn.exportToTethys,'project')
    REMORA.nn.exportToTethys.project = '';
end

btnPos=[x(2) y(16)-ybuff w h-ybuff];
REMORA.fig.nn.exportToTethys.projectEdTxt = uicontrol(REMORA.fig.nn.exportToTethys.figH,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',REMORA.nn.exportToTethys.project,...
    'HorizontalAlignment','left',...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','nn_ui_exportToTethys_control(''setProject'')');

