function batchLTSA_init_figure

global REMORA

defaultPos = [0.25,0.25,0.3,0.6];
REMORA.fig.batchLTSA = figure( ...
    'NumberTitle','off', ...
    'Name','Batch Create LTSAs',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Visible', 'on');

end

