function batchLTSA_init_gui
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% batchLTSA_init_gui.m
%
% Verify settings in GUI before running on entire drive.
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
global REMORA

% button grid layouts
% 8 rows, 5 columns
r = 8; % rows      (extra space for separations btw sections)
c = 5;  % columns
h = 1/r;
w = 1/c;
ph = h * 0.8; % padded height for buttons/boxes leaves a bit of padding
pw = w * 0.9; % padded width
ybuff = h*.2;
ycenter = h*.25;
xbuff = w*.1;
% y position (relative units)
y = 1:-h:0;
% x position (relative units)
x = 0:w:1;

% colors
bgColor = [1 1 1];  % white
bgColorGrayLight = [.92 .92 .92];  % gray
bgColorGray = [.86 .86 .86];  % gray

%% Set Directory Section

REMORA.batchLTSA_verify = [];
labelStr = 'Set Directory';
btnPos=[x(1) y(2) w*5 ph];
REMORA.batchLTSA_verify.headtext = uicontrol(REMORA.fig.batchLTSA, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',12,...
    'Visible','on');

%***********************************
% Set Path
%***********************************
% Input Folder Text
labelStr = 'Input Folder';
btnPos=[x(1)+xbuff y(3)-ycenter pw ph];
REMORA.batchLTSA_verify.inDirTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'BackgroundColor', bgColor,...
    'Visible','on');

% Input Folder Editable Text
labelStr=num2str(REMORA.batchLTSA.settings.inDir);
btnPos=[x(2)+xbuff y(3) w*3-xbuff*2 ph];
REMORA.batchLTSA_verify.inDirEdTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','batchLTSA_control(''setInDir'')');

% Input Folder Browse Button
labelStr = 'Browse';
btnPos = [x(5) y(3) pw ph];
REMORA.batchLTSA_verify.inDirBrowse = uicontrol(REMORA.fig.batchLTSA,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorGray,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','batchLTSA_control(''browseInDir'')');

% ***********************************
% Set File Type
% ***********************************
% File Type Text
labelStr = 'Data File Type';
btnPos=[x(1)+xbuff y(4)-ycenter pw ph];
REMORA.batchLTSA_verify.inDirTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'BackgroundColor', bgColor,...
    'Visible','on');

% Make radiobutton group
REMORA.fig.dataType_buttongroup = uibuttongroup('Visible','off',...
    'Position',[x(2)+xbuff y(4) w*4-xbuff*2 ph],...
    'SelectionChangedFcn','batchLTSA_control(''setDataType'')',...
    'Visible', 'on');

% set radio button options
labelStr = 'XWAV Data';
relBtnPos = [40 12 120 20];
REMORA.batchLTSA_verify.XWAVRadioButton = uicontrol(REMORA.fig.dataType_buttongroup,...
    'Style', 'radiobutton',...
    'Position',relBtnPos,...
    'String',labelStr,...
    'Value',true,...
    'Tag','XWAV',...
    'FontUnits','normalized', ...
    'Visible','on');

labelStr = 'WAV Data';
relBtnPos=[165 12 120 20];
REMORA.batchLTSA_verify.WAVRadioButton = uicontrol(REMORA.fig.dataType_buttongroup,...
    'Style','radiobutton',...
    'Position',relBtnPos,...
    'String',labelStr,...
    'Tag','WAV',...
    'FontUnits','normalized', ...
    'Visible','on');

labelStr = 'FLAC Data';
relBtnPos=[290 12 120 20];
REMORA.batchLTSA_verify.FLACRadioButton = uicontrol(REMORA.fig.dataType_buttongroup,...
    'Style','radiobutton',...
    'Position',relBtnPos,...
    'String',labelStr,...
    'Tag','FLAC',...
    'FontUnits','normalized', ...
    'Visible','on');

%***********************************
% Set LTSA Settings
%***********************************
labelStr = 'LTSA Settings';
btnPos=[x(1) y(5) w*5 ph];
REMORA.batchLTSA_verify.headtext = uicontrol(REMORA.fig.batchLTSA, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',12,...
    'Visible','on');

%***********************************
% Set Time Average
%***********************************
% tave text
labelStr = 'tave\n[time average]';
btnPos=[x(1)+xbuff y(6)-ycenter/2 pw ph];
REMORA.batchLTSA_verify.taveTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'BackgroundColor', bgColor,...
    'Visible','on');

% tave editable Text
labelStr=num2str(REMORA.batchLTSA.settings.tave);
btnPos=[x(2) y(6) pw ph];
REMORA.batchLTSA_verify.taveEdTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','batchLTSA_control(''settave'')');

%***********************************
% Set Frequency Settings
%***********************************
% dfreq Text
labelStr = 'dfreq\n[frequency average]';
btnPos=[x(4)-w/2 y(6)-ycenter/2 pw ph];
REMORA.batchLTSA_verify.dfreqTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'BackgroundColor', bgColor,...
    'Visible','on');

% dreq Editable Text
labelStr=num2str(REMORA.batchLTSA.settings.dfreq);
btnPos=[x(5)-w/2 y(6) pw ph];
REMORA.batchLTSA_verify.dfreqEdTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','batchLTSA_control(''setdfreq'')');

%***********************************
% Create LTSAs
%***********************************
labelStr = 'Batch Create LTSAs';
btnPos=[x(1)+1/2*w y(8) w*4 h];
REMORA.batchLTSA_verify.BatchLTSAEdTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',[.47,.67,.19],...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','batchLTSA_control(''RunBatchLTSA'')');




