function batchLTSA_init_gui
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% batchLTSA_init_gui.m
%
% Verify settings in GUI before running on entire drive.
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
global REMORA

% button grid layouts
% 10 rows, 5 columns
r = 10; % rows      (extra space for separations btw sections)
c = 5;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8; % height for buttons/boxes leaves a bit of padding
% dx = 0.008;
ybuff = h*.2;
xbuff = w*.1;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;

% colors
bgColor = [1 1 1];  % white
bgColorGrayLight = [.92 .92 .92];  % gray
bgColorGray = [.86 .86 .86];  % gray

%% Set Directory Section

REMORA.batchLTSA_verify = [];
labelStr = 'Set Directory';
btnPos=[x(1) y(2) w*5 h];
REMORA.batchLTSA_verify.headtext = uicontrol(REMORA.fig.batchLTSA, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');

%***********************************
% Set Path
%***********************************
% Input Folder Text
labelStr = 'Input Folder';
btnPos=[x(1)+xbuff  y(3) w*.8 dy];
REMORA.batchLTSA_verify.inDirTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Input Folder Editable Text
labelStr=num2str(REMORA.batchLTSA.settings.inDir);
btnPos=[x(2) y(3) w*3-w/8 dy];
REMORA.batchLTSA_verify.inDirEdTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','batchLTSA_control(''setInDir'')');

% Input Folder Browse Button
labelStr = 'Browse';
btnPos = [x(5) y(3) w*.9 dy];
REMORA.batchLTSA_verify.inDirBrowse = uicontrol(REMORA.fig.batchLTSA,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorGray,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','batchLTSA_control(''browseInDir'')');

% ***********************************
% Set File Type
% ***********************************
% File Type Text
labelStr = 'Data File\n  Type';
btnPos=[x(1)+xbuff y(4) w*.8 dy];
REMORA.batchLTSA_verify.inDirTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Make radiobutton group
REMORA.fig.batchLTSA.dataType_buttongroup = uibuttongroup('Visible','off',...
                  'Position',[x(2) y(4) w*4-w/8 dy],...
                  'SelectionChangedFcn','batchLTSA_control(''setDataType'')',... 
                  'Visible', 'on');

% set radio button options
labelStr = 'XWAV Data';
relBtnPos = [20 10 100 20];
REMORA.batchLTSA_verify.XWAVRadioButton = uicontrol(REMORA.fig.batchLTSA.dataType_buttongroup,...
   'Style', 'radiobutton',...
   'Position',relBtnPos,...
   'String',labelStr,...
   'Value',true,...
   'Tag','XWAV',...
   'FontUnits','normalized', ...
   'Visible','on');

labelStr = 'WAV Data';
relBtnPos=[140 10 100 20];
REMORA.batchLTSA_verify.WAVRadioButton = uicontrol(REMORA.fig.batchLTSA.dataType_buttongroup,...
   'Style','radiobutton',...
   'Position',relBtnPos,...
   'String',labelStr,...
   'Tag','WAV',...
   'FontUnits','normalized', ...
   'Visible','on');
              
labelStr = 'FLAC Data';
relBtnPos=[260 10 100 20];
REMORA.batchLTSA_verify.FLACRadioButton = uicontrol(REMORA.fig.batchLTSA.dataType_buttongroup,...
   'Style','radiobutton',...
   'Position',relBtnPos,...
   'String',labelStr,...
   'Tag','FLAC',...
   'FontUnits','normalized', ...
   'Visible','on');

%***********************************
% Set LTSA Settings
%***********************************
labelStr = 'LTSA Settings';
btnPos=[x(1) y(5)-ybuff w*5 h];
REMORA.batchLTSA_verify.headtext = uicontrol(REMORA.fig.batchLTSA, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');

%***********************************
% Set Time Average
%***********************************
% tave text
labelStr = 'tave\n[time average]';
btnPos=[x(1)+xbuff y(6)-ybuff w dy];
REMORA.batchLTSA_verify.taveTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% tave editable Text
labelStr=num2str(REMORA.batchLTSA.settings.tave);
btnPos=[x(2)+xbuff*2 y(6)-ybuff w*.6 dy];
REMORA.batchLTSA_verify.taveEdTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','batchLTSA_control(''settave'')');

%***********************************
% Set Frequency Settings
%***********************************
% dfreq Text
labelStr = 'dfreq\n[frequency average]';
btnPos=[x(4) y(6)-ybuff w dy];
REMORA.batchLTSA_verify.dfreqTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% dreq Editable Text
labelStr=num2str(REMORA.batchLTSA.settings.dfreq);
btnPos=[x(5)+xbuff y(6)-ybuff w*.6 dy];
REMORA.batchLTSA_verify.dfreqEdTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','batchLTSA_control(''setdfreq'')');

%***********************************
% Create LTSAs
%***********************************
labelStr = 'Batch Create LTSAs';
btnPos=[x(1)+1/2*w y(10) w*4 h];
REMORA.batchLTSA_verify.BatchLTSAEdTxt = uicontrol(REMORA.fig.batchLTSA,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',[.47,.67,.19],...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','batchLTSA_control(''RunBatchLTSA'')');




