function mdLTSA_init_batch_figure

global REMORA

bgColorGray = [.86 .86 .86];  % gray
bgColorGrayLight = [.92 .92 .92];  % gray

defaultPos = [0.25,0.25,0.3,0.6];
REMORA.fig.mdLTSA.batch = figure( ...
    'NumberTitle','off', ...
    'Name','Batch Create LTSAs',...
    'Units','normalized',...
    'MenuBar','none',...
    'Position',defaultPos, ...
    'Color',bgColorGrayLight,... 
    'Visible', 'on');

