function mdLTSA_init_batch_gui
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% mdLTSA_init_batch_gui.m
%
% Verify settings in GUI before running on entire drive.
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
global REMORA

% button grid layouts
% 10 rows, 5 columns
r = 10; % rows      (extra space for separations btw sections)
c = 5;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
xbuff = w*.1;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;

% colors
bgColor = [1 1 1];  % white
bgColorGrayLight = [.92 .92 .92];  % gray
bgColorGray = [.86 .86 .86];  % gray

%% Set Directory Section

REMORA.mdLTSA_verify = [];
labelStr = 'Set Directory';
btnPos=[x(1) y(2) w*5 h];
REMORA.mdLTSA_verify.headtext = uicontrol(REMORA.fig.mdLTSA.batch, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');

%***********************************
% Set Path
%***********************************
% Input Folder Text
labelStr = 'Input Folder';
btnPos=[x(1)+xbuff  y(3) w dy];
REMORA.mdLTSA_verify.inDirTxt = uicontrol(REMORA.fig.mdLTSA.batch,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Input Folder Editable Text
labelStr=num2str(REMORA.mdLTSA.settings.inDir);
btnPos=[x(2)-w/4 y(3) w*3 dy];
REMORA.mdLTSA_verify.inDirEdTxt = uicontrol(REMORA.fig.mdLTSA.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','mdLTSA_control(''setInDir'')');

% Input Folder Browse Button
labelStr = 'Browse';
btnPos = [x(5)-w/4 y(3) w dy];
REMORA.mdLTSA_verify.inDirBrowse = uicontrol(REMORA.fig.mdLTSA.batch,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColorGray,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','mdLTSA_control(''browseInDir'')');

% ***********************************
% Set File Type
% ***********************************
% File Type Text
labelStr = 'Data File Type';
btnPos=[x(1)+xbuff y(4)-ybuff w dy];
REMORA.mdLTSA_verify.inDirTxt = uicontrol(REMORA.fig.mdLTSA.batch,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Make radiobutton group
REMORA.fig.mdLTSA.dataType_buttongroup = uibuttongroup('Visible','off',...
                  'Position',[x(2)+xbuff y(4)-ybuff/2 w*4-(xbuff*2) h],...
                  'SelectionChangedFcn','mdLTSA_control(''setDataType'')',... 
                  'Visible', 'on');

% set radio button options
labelStr = 'XWAV Data';
relBtnPos = [30 15 100 20];
REMORA.mdLTSA_verify.XWAVRadioButton = uicontrol(REMORA.fig.mdLTSA.dataType_buttongroup,...
   'Style', 'radiobutton',...
   'Position',relBtnPos,...
   'String',labelStr,...
   'Value',true,...
   'Tag','XWAV',...
   'FontUnits','normalized', ...
   'Visible','on');

labelStr = 'WAV or FLAC Data';
relBtnPos=[180 15 150 20];
REMORA.mdLTSA_verify.WAVRadioButton = uicontrol(REMORA.fig.mdLTSA.dataType_buttongroup,...
   'Style','radiobutton',...
   'Position',relBtnPos,...
   'String',labelStr,...
   'Tag','WAV',...
   'FontUnits','normalized', ...
   'Visible','on');
              

% %***don't think I need this but leaving it just in case***
% % Regdate style
% labelStr = 'Date format filename';
% btnPos=[x(1)+xbuff y(4) w dy];
% REMORA.mdLTSA_verify.regdateTxt = uicontrol(REMORA.fig.mdLTSA.batch,...
%     'Style','text',...
%     'Units','normalized',...
%     'HorizontalAlignment','left',...
%     'Position',btnPos,...
%     'String',sprintf(labelStr,'Interpreter','tex'),...
%     'FontUnits','normalized',...
%     'Visible','on');
% 
% % Regdate Editable Text
% labelStr=num2str(REMORA.mdLTSA.settings.regdate);
% btnPos=[x(3)-w/4 y(4) w*3 dy];
% REMORA.mdLTSA_verify.regdateEdTxt = uicontrol(REMORA.fig.mdLTSA.batch,...
%     'Style','edit',...
%     'Units','normalized',...
%     'Position',btnPos,...
%     'BackgroundColor',bgColor,...
%     'HorizontalAlignment','left',...
%     'String',labelStr,...
%     'FontUnits','normalized',...
%     'Visible','on',...
%     'Callback','mdLTSA_control(''setRegDate'')');

%***********************************
% Set LTSA Settings
%***********************************

labelStr = 'LTSA Settings';
btnPos=[x(1) y(5)-ybuff w*5 h];
REMORA.mdLTSA_verify.headtext = uicontrol(REMORA.fig.mdLTSA.batch, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');

% GOAL: set basic settings (if they are the same across all dirs) so that
% they don't have to be typed in later!! 
% SO leaving in here just as a place holder so I can modify if needed
%***********************************
% Threshold Text
%***********************************

% %  Threshold Text
% labelStr = 'Threshold (dB)';
% btnPos=[x(1)+xbuff*2 y(8)-ybuff w*2 dy];
% REMORA.bm_verify.ThreshText = uicontrol(REMORA.fig.bm.batch,...
%     'Style','text',...
%     'Units','normalized',...
%     'HorizontalAlignment','left',...
%     'Position',btnPos,...
%     'String',sprintf(labelStr,'Interpreter','tex'),...
%     'FontUnits','normalized', ...
%     'Visible','on');
% 
% % Threshold Editable Text
% labelStr=num2str(REMORA.bm.settings.thresh(1,1));
% btnPos=[x(4)-w/2 y(8) w dy];
% REMORA.bm_verify.ThreshEdText = uicontrol(REMORA.fig.bm.batch,...
%     'Style','edit',...
%     'Units','normalized',...
%     'Position',btnPos,...
%     'BackgroundColor',bgColor,...
%     'String',labelStr,...
%     'FontUnits','normalized', ...
%     'Visible','on',...
%     'Callback','bm_control(''setThresh'')');
% 


%%%%%%%%%%%%%%%%%%%%%%%%%%% Data as check boxes
% labelStr = 'XWAV Data';
% btnPos=[x(1)+xbuff*4 y(6)-ybuff*2 w*1.5 h];
% REMORA.mdLTSA_verify.XWAVRadioButton = uicontrol(REMORA.fig.mdLTSA.batch,...
%    'Style', 'radiobutton',...
%    'Units','normalized',...
%    'Position',btnPos,...
%    'String',labelStr,...
%    'Value',REMORA.mdLTSA.settings.XWAVdata,...
%    'FontUnits','normalized', ...
%    'Visible','on',...
%    'Callback','mdLTSA_control(''setXWAVdata'')');
% 
% labelStr = 'WAV or FLAC Data';
% btnPos=[x(4) y(6)-ybuff*2 w*1.5 h];
% REMORA.mdLTSA_verify.WAVRadioButton = uicontrol(REMORA.fig.mdLTSA.batch,...
%    'Style','radiobutton',...
%    'Units','normalized',...
%    'Position',btnPos,...
%    'String',labelStr,...
%    'Value',REMORA.mdLTSA.settings.WAVdata,...
%    'FontUnits','normalized', ...
%    'Visible','on',...
%    'Callback','mdLTSA_control(''setWAVdata'')');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


% Create LTSAs
labelStr = 'Batch Create LTSAs';
btnPos=[x(1)+1/2*w y(10) w*4 h];
REMORA.mdLTSA_verify.BatchLTSAEdTxt = uicontrol(REMORA.fig.mdLTSA.batch,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',[.47,.67,.19],...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','mdLTSA_control(''RunBatchLTSA'')');




