function mdLTSA_init_batch_gui
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% mdLTSA_init_batch_gui.m
%
% Verify settings in GUI before running on entire drive.
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
global REMORA

% button grid layouts
% 14 rows, 4 columns
r = 13; % rows      (extra space for separations btw sections)
c = 5;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
xbuff = w*.1;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;

% colors
bgColor = [1 1 1];  % white
bgColorGrayLight = [.92 .92 .92];  % gray
bgColorGray = [.86 .86 .86];  % gray

REMORA.mdLTSA_verify = [];
labelStr = 'Set Directory';
btnPos=[x(1) y(2) w*5 h];
REMORA.mdLTSA_verify.headtext = uicontrol(REMORA.fig.mdLTSA.batch, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');


% Set paths and strings
%***********************************

% Input Folder Text
labelStr = 'Input Folder';
btnPos=[x(1)+xbuff  y(3) w dy];
REMORA.mdLTSA_verify.inDirTxt = uicontrol(REMORA.fig.mdLTSA.batch,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Input Folder Editable Text
labelStr=num2str(REMORA.mdLTSA.settings.inDir);
btnPos=[x(3)-w/4 y(3) w*3 dy];
REMORA.mdLTSA_verify.inDirEdTxt = uicontrol(REMORA.fig.mdLTSA.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','mdLTSA_control(''setInDir'')');

% % Output Folder Text
% labelStr = 'Output Folder';
% btnPos=[x(1)+xbuff  y(4) w dy];
% REMORA.bm_verify.outDirTxt = uicontrol(REMORA.fig.bm.batch,...
%     'Style','text',...
%     'Units','normalized',...
%         'HorizontalAlignment','left',...
%     'Position',btnPos,...
%     'String',sprintf(labelStr,'Interpreter','tex'),...
%     'FontUnits','normalized', ...
%     'Visible','on');

% % Output Folder Editable Text
% labelStr=num2str(REMORA.bm.settings.outDir);
% btnPos=[x(3)-w/4 y(4) w*3 dy];
% REMORA.bm_verify.outDirEdTxt = uicontrol(REMORA.fig.bm.batch,...
%     'Style','edit',...
%     'Units','normalized',...
%     'Position',btnPos,...
%     'BackgroundColor',bgColor,...
%     'HorizontalAlignment','left',...
%     'String',labelStr,...
%     'FontUnits','normalized', ...
%     'Visible','on',...
%     'Callback','bm_control(''setOutDir'')');


%***don't think I need this but leaving it just in case***
% Regdate style
labelStr = 'Date format filename';
btnPos=[x(1)+xbuff y(5) w dy];
REMORA.mdLTSA_verify.regdateTxt = uicontrol(REMORA.fig.mdLTSA.batch,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized',...
    'Visible','on');

% Regdate Editable Text
labelStr=num2str(REMORA.mdLTSA.settings.regdate);
btnPos=[x(3)-w/4 y(5) w*3 dy];
REMORA.mdLTSA_verify.regdateEdTxt = uicontrol(REMORA.fig.mdLTSA.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized',...
    'Visible','on',...
    'Callback','mdLTSA_control(''setRegDate'')');
%%
% LTSA settings
% GOAL: set basic settings (if they are the same across all dirs) so that
% they don't have to be typed in later!! 
% SO leaving in here just as a place holder so I can modify if needed

labelStr = 'LTSA Settings';
btnPos=[x(1) y(6)-ybuff w*5 h];
REMORA.mdLTSA_verify.headtext = uicontrol(REMORA.fig.mdLTSA.batch, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');

%***********************************
% Threshold Text
%***********************************

%  Threshold Text
labelStr = 'Threshold (dB)';
btnPos=[x(1)+xbuff*2 y(8)-ybuff w*2 dy];
REMORA.bm_verify.ThreshText = uicontrol(REMORA.fig.bm.batch,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Threshold Editable Text
labelStr=num2str(REMORA.bm.settings.thresh(1,1));
btnPos=[x(4)-w/2 y(8) w dy];
REMORA.bm_verify.ThreshEdText = uicontrol(REMORA.fig.bm.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_control(''setThresh'')');

%***********************************
% Kernel settings
%***********************************

% Start frequency text
labelStr = 'Start frequencies';
btnPos =[x(1)+xbuff*2 y(10)-ybuff w*0.8 dy];
REMORA.bm_verify.SpeciesText = uicontrol(REMORA.fig.bm.batch,...
     'Style','text',...
     'Units','normalized',...
     'HorizontalAlignment','left',...
     'Position',btnPos,...
     'String',sprintf(labelStr,'Interpreter','tex'),...
     'FontUnits','normalized',...
     'Visible','on');

%Start frequency 1 editable text
labelStr=num2str(REMORA.bm.settings.startF(1,1));
btnPos=[x(2) y(10) w*0.8 dy];
REMORA.bm_verify.StartF1EdText = uicontrol(REMORA.fig.bm.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_control(''setStartF1'')');

%Start frequency 2 editable text
labelStr=num2str(REMORA.bm.settings.startF(1,2));
btnPos=[x(3) y(10) w*0.8 dy];
REMORA.bm_verify.StartF2EdText = uicontrol(REMORA.fig.bm.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_control(''setStartF2'')');
    
%Start frequency 3 editable text
labelStr=num2str(REMORA.bm.settings.startF(1,3));
btnPos=[x(4) y(10) w*0.8 dy];
REMORA.bm_verify.StartF3EdText = uicontrol(REMORA.fig.bm.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_control(''setStartF3'')');

%Start frequency 4 editable text
labelStr=num2str(REMORA.bm.settings.startF(1,4));
btnPos=[x(5) y(10) w*0.8 dy];
REMORA.bm_verify.StartF4EdText = uicontrol(REMORA.fig.bm.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_control(''setStartF4'')');

% ***********************************
% File type Text
% ***********************************
labelStr = 'XWAV Data';
btnPos=[x(1)+xbuff*2 y(9) w h];
REMORA.mdLTSA_verify.XWAVCheckbox = uicontrol(REMORA.fig.mdLTSA.batch,...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'Value',REMORA.mdLTSA.settings.XWAV,...
   'FontUnits','normalized', ...
   'Visible','on',...
   'Callback','mdLTSA_control(''setXWAVdata'')');

labelStr = 'WAV or FLAC Data';
btnPos=[x(2) y(9) w h];
REMORA.mdLTSA_verify.WAVCheckbox = uicontrol(REMORA.fig.mdLTSA.batch,...
   'Style','checkbox',...
   'Units','normalized',...
   'Position',btnPos,...
   'String',labelStr,...
   'Value',REMORA.mdLTSA.settings.WAV,...
   'FontUnits','normalized', ...
   'Visible','on',...
   'Callback','mdLTSA_control(''setWAVdata'')');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


% Create LTSAs
labelStr = 'Batch Create LTSAs';
btnPos=[x(2)+1/2*w y(13) w*2 h];
REMORA.mdLTSA_verify.BatchLTSAEdTxt = uicontrol(REMORA.fig.mdLTSA.batch,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',[.47,.67,.19],...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','mdLTSA_control(''RunBatchLTSA'')');



