function report = xwavdir2flac(indir, varargin)
%XWAVDIR2FLAC  Compress a folder of x.wav to x.flac, verifying each one.
%
%   xwavdir2flac('E:\HARP\SiteA')                        % dry run: what would happen
%   xwavdir2flac('E:\HARP\SiteA', 'go', true)            % convert, keep the x.wavs
%   xwavdir2flac('E:\HARP\SiteA', 'go', true, 'keepXwav', false)   % and delete them
%   xwavdir2flac(d, 'go', true, 'outdir', 'F:\flac')     % write somewhere else
%
% Options
%   'go'          actually do it. Defaults to FALSE, so a bare call reports
%                 what it would convert and how much space it would save
%                 without touching anything.
%   'keepXwav'    keep the originals (default true). Only ever set false once
%                 a dry run and a spot check look right.
%   'outdir'      where to write; default alongside each source file, keeping
%                 the folder structure
%   'recursive'   walk subfolders (default true)
%   'flac'        path to the flac tool; found automatically if omitted
%   'skipExisting' don't redo files that already have an x.flac (default true)
%
% For converting an existing archive. Every file is converted with
% --verify, and its preserved harp header is compared byte for byte with the
% header of the x.wav before that x.wav is removed, so a file whose header did
% not survive is reported and its original kept. See xwav2flac for what that
% check catches and why it matters.
%
% Nothing is deleted unless BOTH 'go' is true AND 'keepXwav' is false. A
% failure part-way through leaves everything converted so far in place and the
% rest untouched; running it again picks up where it stopped.
%
% Expect 50-70% saved on HARP recordings. The compression is lossless: the
% x.wav can be regenerated byte for byte with
%
%   flac -d --keep-foreign-metadata-if-present file.x.flac
%
% though with Triton reading x.flac directly, that is rarely needed.
%
% Returns a struct with .converted, .failed, .skipped and the byte totals.
%
% See also XWAV2FLAC, CK_XFLAC_METADATA, RDXFLACHD.

p = inputParser;
addParameter(p,'go',false);
addParameter(p,'keepXwav',true);
addParameter(p,'outdir','');
addParameter(p,'recursive',true);
addParameter(p,'flac','');
addParameter(p,'skipExisting',true);
parse(p,varargin{:});
opt = p.Results;

if ~exist(indir,'dir'); error('no such directory: %s', indir); end

[exe, why] = flac_exe(opt.flac);
if isempty(exe); error('%s', why); end
opt.flac = exe;

if opt.recursive
    listing = dir(fullfile(indir,'**','*.x.wav'));
else
    listing = dir(fullfile(indir,'*.x.wav'));
end
listing = listing(~[listing.isdir]);

report = struct('converted',{{}}, 'failed',{{}}, 'skipped',{{}}, ...
                'bytesIn',0, 'bytesOut',0);

fprintf('\n%s\n', repmat('-',1,68));
if opt.go
    fprintf('Converting x.wav to x.flac in %s\n', indir);
    if opt.keepXwav
        fprintf('  originals will be KEPT\n');
    else
        fprintf('  originals will be DELETED once each conversion is verified\n');
    end
else
    fprintf('DRY RUN -- nothing will be written. Pass ''go'',true to convert.\n');
    fprintf('  %s\n', indir);
end
fprintf('  %d x.wav files found\n%s\n\n', numel(listing), repmat('-',1,68));

if isempty(listing); return; end

for k = 1:numel(listing)
    src = fullfile(listing(k).folder, listing(k).name);
    [~, stem] = fileparts(listing(k).name);          % name.x
    if isempty(opt.outdir)
        thisOut = listing(k).folder;
    else
        % keep the folder structure under outdir
        rel = strrep(listing(k).folder, indir, '');
        rel = regexprep(rel, '^[\\/]+', '');
        thisOut = fullfile(opt.outdir, rel);
        if opt.go && ~exist(thisOut,'dir'); mkdir(thisOut); end
    end
    dst = fullfile(thisOut, [stem '.flac']);

    if opt.skipExisting && exist(dst,'file')
        report.skipped{end+1} = src; %#ok<AGROW>
        fprintf('  skip   %-52s (x.flac already there)\n', listing(k).name);
        continue
    end

    if ~opt.go
        report.bytesIn = report.bytesIn + listing(k).bytes;
        fprintf('  would  %-52s %8.1f MB\n', listing(k).name, listing(k).bytes/1e6);
        continue
    end

    [ok, out, msg] = xwav2flac(src, 'outdir', thisOut, ...
        'keepXwav', opt.keepXwav, 'flac', opt.flac);
    if ~ok
        report.failed{end+1} = struct('file',src,'why',msg); %#ok<AGROW>
        fprintf('  FAIL   %-52s %s\n', listing(k).name, msg);
        continue
    end
    a = dir(out);
    report.converted{end+1} = out; %#ok<AGROW>
    report.bytesIn  = report.bytesIn  + listing(k).bytes;
    report.bytesOut = report.bytesOut + a.bytes;
    fprintf('  ok     %-52s %8.1f -> %6.1f MB\n', listing(k).name, ...
        listing(k).bytes/1e6, a.bytes/1e6);
end

fprintf('\n%s\n', repmat('-',1,68));
if opt.go
    fprintf('  converted : %d\n', numel(report.converted));
    fprintf('  failed    : %d\n', numel(report.failed));
    fprintf('  skipped   : %d\n', numel(report.skipped));
    if report.bytesIn > 0
        fprintf('  %.1f GB -> %.1f GB (%.1f%% saved)\n', ...
            report.bytesIn/1e9, report.bytesOut/1e9, ...
            100*(1 - report.bytesOut/report.bytesIn));
    end
    if ~isempty(report.failed)
        fprintf('\n  The files below were NOT converted and their x.wav is untouched:\n');
        for k = 1:numel(report.failed)
            [~,n,e] = fileparts(report.failed{k}.file);
            fprintf('    %s\n      %s\n', [n e], report.failed{k}.why);
        end
    end
else
    fprintf('  %d files, %.1f GB\n', numel(listing), report.bytesIn/1e9);
    fprintf('  HARP recordings usually compress by 50-70%%, so expect\n');
    fprintf('  roughly %.1f-%.1f GB afterwards.\n', ...
        report.bytesIn*0.30/1e9, report.bytesIn*0.50/1e9);
    fprintf('\n  Re-run with ''go'',true to convert.\n');
end
fprintf('%s\n\n', repmat('-',1,68));
end
