function bm_init_batch_gui
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% sh_init_batch_gui.m
%
% Verify settings in GUI before running on entire drive.
%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
global REMORA

% button grid layouts
% 14 rows, 4 columns
r = 13; % rows      (extra space for separations btw sections)
c = 5;  % columns
h = 1/r;
w = 1/c;
dy = h * 0.8;
% dx = 0.008;
ybuff = h*.2;
xbuff = w*.1;
% y position (relative units)
y = 1:-h:0;

% x position (relative units)
x = 0:w:1;

% colors
bgColor = [1 1 1];  % white
bgColorGrayLight = [.92 .92 .92];  % gray
bgColorGray = [.86 .86 .86];  % gray

REMORA.bm_verify = [];
labelStr = 'Verify Detector Options';
btnPos=[x(1) y(2) w*5 h];
REMORA.bm_verify.headtext = uicontrol(REMORA.fig.bm.batch, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','points', ...
    'FontWeight','bold',...
    'FontSize',10,...
    'Visible','on');


% Set paths and strings
%***********************************

% Input Folder Text
labelStr = 'Input Folder';
btnPos=[x(1)+xbuff  y(3) w dy];
REMORA.bm_verify.inDirTxt = uicontrol(REMORA.fig.bm.batch,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Input Folder Editable Text
labelStr=num2str(REMORA.bm.settings.inDir);
btnPos=[x(3)-w/4 y(3) w*3 dy];
REMORA.bm_verify.inDirEdTxt = uicontrol(REMORA.fig.bm.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_control(''setInDir'')');

% Output Folder Text
labelStr = 'Output Folder';
btnPos=[x(1)+xbuff  y(4) w dy];
REMORA.bm_verify.outDirTxt = uicontrol(REMORA.fig.bm.batch,...
    'Style','text',...
    'Units','normalized',...
        'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Output Folder Editable Text
labelStr=num2str(REMORA.bm.settings.outDir);
btnPos=[x(3)-w/4 y(4) w*3 dy];
REMORA.bm_verify.outDirEdTxt = uicontrol(REMORA.fig.bm.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'HorizontalAlignment','left',...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_control(''setOutDir'')');


% Detector settings
labelStr = 'Adjustable Detector Settings';
btnPos=[x(1) y(6) w*5 h];
REMORA.bm_verify.headtext = uicontrol(REMORA.fig.bm.batch, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGray,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');


% col names
labelStr='Parameter';
btnPos=[x(1) y(7) w h];
REMORA.bm_verify.headtext = uicontrol(REMORA.fig.bm.batch, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGrayLight,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');

labelStr='Value';
btnPos=[x(3)-w/2 y(7) w*3 h];
REMORA.bm_verify.headtext = uicontrol(REMORA.fig.bm.batch, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',btnPos, ...
    'BackgroundColor',bgColorGrayLight,...
    'String',labelStr, ...
    'FontUnits','normalized', ...
    'FontWeight','bold',...
    'Visible','on');


%***********************************
% Threshold Text
%***********************************

%  Threshold Text
labelStr = 'Threshold (dB)';
btnPos=[x(1)+xbuff*2 y(8)-ybuff w*2 dy];
REMORA.bm_verify.ThreshText = uicontrol(REMORA.fig.bm.batch,...
    'Style','text',...
    'Units','normalized',...
    'HorizontalAlignment','left',...
    'Position',btnPos,...
    'String',sprintf(labelStr,'Interpreter','tex'),...
    'FontUnits','normalized', ...
    'Visible','on');

% Threshold Editable Text
labelStr=num2str(REMORA.bm.settings.thresh(1,1));
btnPos=[x(4)-w/2 y(8) w dy];
REMORA.bm_verify.ThreshEdText = uicontrol(REMORA.fig.bm.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_control(''setThresh'')');

%***********************************
% Kernel settings
%***********************************

% Kernel text
 labelStr= 'Kernel settings';
 btnPos =[x(1)+xbuff*2 y(9)-ybuff*2 w*2 h];
 REMORA.bm_verify.SpeciesText = uicontrol(REMORA.fig.bm.batch,...
      'Style','text',...
      'Units','normalized',...
     'HorizontalAlignment','left',...
     'Position',btnPos,...
     'String',sprintf(labelStr,'Interpreter','tex'),...
     'FontUnits','normalized',...
     'FontWeight','bold',...
     'Visible','on');

% Start frequency text
labelStr = 'Start frequencies';
btnPos =[x(1)+xbuff*2 y(10)-ybuff w*0.8 dy];
REMORA.bm_verify.SpeciesText = uicontrol(REMORA.fig.bm.batch,...
     'Style','text',...
     'Units','normalized',...
     'HorizontalAlignment','left',...
     'Position',btnPos,...
     'String',sprintf(labelStr,'Interpreter','tex'),...
     'FontUnits','normalized',...
     'Visible','on');

%Start frequency 1 editable text
labelStr=num2str(REMORA.bm.settings.startF(1,1));
btnPos=[x(2) y(10) w*0.8 dy];
REMORA.bm_verify.StartF1EdText = uicontrol(REMORA.fig.bm.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_control(''setStartF1'')');

%Start frequency 2 editable text
labelStr=num2str(REMORA.bm.settings.startF(1,2));
btnPos=[x(3) y(10) w*0.8 dy];
REMORA.bm_verify.StartF2EdText = uicontrol(REMORA.fig.bm.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_control(''setStartF2'')');
    
%Start frequency 3 editable text
labelStr=num2str(REMORA.bm.settings.startF(1,3));
btnPos=[x(4) y(10) w*0.8 dy];
REMORA.bm_verify.StartF3EdText = uicontrol(REMORA.fig.bm.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_control(''setStartF3'')');

%Start frequency 4 editable text
labelStr=num2str(REMORA.bm.settings.startF(1,4));
btnPos=[x(5) y(10) w*0.8 dy];
REMORA.bm_verify.StartF4EdText = uicontrol(REMORA.fig.bm.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_control(''setStartF4'')');

% End frequency text
labelStr = 'End frequencies';
btnPos =[x(1)+xbuff*2 y(11)-ybuff w dy];
REMORA.bm_verify.SpeciesText = uicontrol(REMORA.fig.bm.batch,...
     'Style','text',...
     'Units','normalized',...
     'HorizontalAlignment','left',...
     'Position',btnPos,...
     'String',sprintf(labelStr,'Interpreter','tex'),...
     'FontUnits','normalized',...
     'Visible','on');

%End frequency 1 editable text
labelStr=num2str(REMORA.bm.settings.endF(1,1));
btnPos=[x(2) y(11) w*0.8 dy];
REMORA.bm_verify.EndF1EdText = uicontrol(REMORA.fig.bm.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_control(''setEndF1'')');

%End frequency 2 editable text
labelStr=num2str(REMORA.bm.settings.endF(1,2));
btnPos=[x(3) y(11) w*0.8 dy];
REMORA.bm_verify.EndF2EdText = uicontrol(REMORA.fig.bm.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_control(''setEndF2'')');

%End frequency 3 editable text
labelStr=num2str(REMORA.bm.settings.endF(1,3));
btnPos=[x(4) y(11) w*0.8 dy];
REMORA.bm_verify.EndF3EdText = uicontrol(REMORA.fig.bm.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_control(''setEndF3'')');

%End frequency 4 editable text
labelStr=num2str(REMORA.bm.settings.endF(1,4));
btnPos=[x(5) y(11) w*0.8 dy];
REMORA.bm_verify.EndF4EdText = uicontrol(REMORA.fig.bm.batch,...
    'Style','edit',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',bgColor,...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'Visible','on',...
    'Callback','bm_control(''setEndF4'')');

%Start frequency editable text
% labelStr=num2str(REMORA.bm.settings.startF(2,1));
% btnPos=[x(2)+w/4 y(10)-ybuff w/4 h];
% REMORA.bm_verify.ThreshEdText = uicontrol(REMORA.fig.bm.batch,...
%     'Style','edit',...
%     'Units','normalized',...
%     'Position',btnPos,...
%     'BackgroundColor',bgColor,...
%     'String',labelStr,...
%     'FontUnits','normalized', ...
%     'Visible','on',...
%     'Callback','bm_control(''setStartF2'')');

%***********************************
% Species detection
%***********************************
%   Species text
% labelStr= 'Species';
% btnPos =[x(1)+xbuff*2 y(10)-ybuff w*2 h];
% REMORA.bm_verify.SpeciesText = uicontrol(REMORA.fig.bm.batch,...
%     'Style','text',...
%     'Units','normalized',...
%     'HorizontalAlignment','left',...
%     'Position',btnPos,...
%     'String',sprintf(labelStr,'Interpreter','tex'),...
%     'FontUnits','normalized',...
%     'Visible','on');

%   Species drop-down box
% labelStr = {'Blue whale','Fin whale'};
% btnPos =[x(2) y(10) w/2 h];
% REMORA.bm_verify.SpeciesChoice = uicontrol(REMORA.fig.bm.batch,...
%     'Style','popup',...
%     'Units','normalized',...
%     'Position',btnPos,...
%     'BackgroundColor',bgColor,...
%     'String',labelStr,...
%     'FontUnits','normalized',...
%     'Visible','on',...
%     'Callback','bm_control(''setSpecies'')');

%***********************************
% File type Text
%***********************************
%labelStr = 'HARP Data';
%btnPos=[x(1)+xbuff*2 y(9) w h];
%REMORA.bm_verify.HARPdataCheckbox = uicontrol(REMORA.fig.bm.batch,...
%    'Style','checkbox',...
%    'Units','normalized',...
%    'Position',btnPos,...
%    'String',labelStr,...
%    'Value',REMORA.bm.settings.HARPdata,...
%    'FontUnits','normalized', ...
%    'Visible','on',...
%    'Callback','bm_control(''setHARPdata'')');

%labelStr = 'Sound Trap Data';
%btnPos=[x(2) y(9) w h];
%REMORA.bm_verify.SoundTrapdataCheckbox = uicontrol(REMORA.fig.bm.batch,...
%    'Style','checkbox',...
%    'Units','normalized',...
%    'Position',btnPos,...
%    'String',labelStr,...
%    'Value',REMORA.bm.settings.SoundTrap,...
%    'FontUnits','normalized', ...
%    'Visible','on',...
%    'Callback','bm_control(''setSoundTrapdata'')');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%***********************************
% Save .tlab file Checkbox
%***********************************
%labelStr = 'Create .csv Output File';
%btnPos=[x(1)+xbuff*2 y(10) w h];
%REMORA.bm_verify.csvCheckbox = uicontrol(REMORA.fig.bm.batch,...
%    'Style','checkbox',...
%    'Units','normalized',...
%    'Position',btnPos,...
%    'String',labelStr,...
%    'Value',REMORA.bm.settings.saveCsv,...
%    'FontUnits','normalized', ...
%    'Visible','on',...
%    'Callback','bm_control(''setCsvFile'')');

% Run button
labelStr = 'Run Detector';
btnPos=[x(2)+1/2*w y(13) w*2 h];
REMORA.bm_verify.RunDetectorEdTxt = uicontrol(REMORA.fig.bm.batch,...
    'Style','pushbutton',...
    'Units','normalized',...
    'Position',btnPos,...
    'BackgroundColor',[.47,.67,.19],...
    'String',labelStr,...
    'FontUnits','normalized', ...
    'FontSize',.5,...
    'Visible','on',...
    'FontWeight','bold',...
    'Callback','bm_control(''RunBatchDetection'')');



